### ISSUE TITLE
Bring back withRouter?

### ISSUE THREAD

**Issue by cristian-sima** [ReactTraining/react-router#3847]
![image](https://cloud.githubusercontent.com/assets/12199042/18511058/4817306a-7a8a-11e6-85b0-6645334799a0.png)

**Comment by timdorr** [comment]
That's correct. There is no withRouter in this version. The API is completely different.

**Comment by cristian-sima** [comment]
I've seen that. Any workaround to implement `withRouter` in v4?

**Comment by timdorr** [comment]
No, because you don't need to access it anymore. That's not how the API works in 4.0

**Comment by cristian-sima** [comment]
Good. And let's say I need to access router.push inside my React code?

**Comment by cristian-sima** [comment]
@timdorr Do I miss something?

**Comment by timdorr** [comment]
Without seeing your particular use case, it's hard to tell. However, under the new paradigms of 4.0, you shouldn't have to reach out to imperative code. You should just render a `<Redirect>`. Look at the auth example for guidance.

**Comment by just-boris** [comment]
Hello! I have checked out auth example from docs and I'd like to summarize why `withRouter` solution was better.

Here is what we had before in v2:

```js
class Login extends React.Component {
  login = () => {
    auth.authenticate().then(
       () => this.props.router.replace('/')
    );
  }
}
export default withRouter(Login);
```

And how it should be updated to use v4:

```js
class Login extends React.Component {
  state = {
    shouldRedirect: true
  }

  login = () => {
    auth.authenticate().then(
       () => this.setState({shouldRedirect: true})
    );
  }

  render() {
    if (this.state.shouldRedirect) {
      return <Redirect to="/" />;
    }
  }
}
export default withRouter(Login);
```

Look, now there is more code that does exactly the same. Also in v2 you could change the current location whenever you want with a single line of code, now this logic is spread among the whole component and this probably causes a lot of frustration from developers.

**Comment by ryanflorence** [comment]
add contextTypes: { router } and it's all yours, even wrap it up in your
own withRouter.

**Comment by just-boris** [comment]
Well, that's good that I can write my own withRouter and solve this.
But this is contrary to @timdorr's answer:

> No, because you don't need to access it anymore. That's not how the API works in 4.0

Can I think that access to the context via HOC is a recommended solution to simplify redirect logic when it is possible?

**Comment by Nimelrian** [comment]
I am missing withRouter in the API as well. What if I have nested components far below the original Match component, but want to have a Link to a route below the current path.

Example:
/machines/{id} renders a MachineDetailsContainer. Somewhere in it's component subtree I have a component which should link me to /machines/{id}/logs, where only the logs of this specific machine are displayed.

I could solve this by either passing down the router props all the way from MachineDetailsContainer (which would lead to the ugly situation of components in the subtree only passing the props down without using them), or by passing only the id down and then building a new absolute route path `/machines/${id}/logs` (not that nice either, since I'd have to change this route building if I move the main component).

Or is there any way to do this that I missed while reading the docs?

**Comment by Aourin** [comment]
I hope its not just stubborness and I am still trying to get used to the new API approach, but its just odd that you have to render something to cause a state change.

Under the hood, it looks like Link does a transitionTo on the router, so why would that not imply that is how you should navigate between views?

Example to some of those questions above, i assume (and I may be completely wrong so forgive me), but if you say want to click a button to transition to another view, you have to

1. Handle the button click.
2. Do something that  renders out a Redirect.

**Comment by ryanflorence** [comment]
router is on context, you can use it.

**Comment by Aourin** [comment]
@ryanflorence i think part of my own confusion was the push from switching from using the context.router to using withRouter and really recommending that, so it my assumption was that you shouldn't mess with the context.router. My bad.

**Comment by mjackson** [comment]
Re-opening this because Facebook still warns people against using context directly.

**Comment by timdorr** [comment]
Want me to port the withRouter wrapper into 4.0? Should be pretty simple to do.

**Comment by Aourin** [comment]
withRouter does the same thing anyhow and accesses the.context, doesn't it? I guess if it's generally agreed with you guys/gals that it is acceptable to do so and stops users from doing accessing themselves, it is probably the best option.

**Comment by timdorr** [comment]
Yes, but that's abstracted away from you, so you don't have to worry about it. That way, if the API were to change for some reason, then we could patch over those changes without you having to adjust your code at all.

**Comment by Aourin** [comment]
Completely agreed @timdorr

**Comment by mjackson** [comment]
I'm not 100% that `withRouter` is the solution. Wanna think about it some more.

**Comment by Aourin** [comment]
Another option is providing some router via react-router and decouples routing from a view. However, that is probably against your heart around the new API.

Regardless of withRouter or not, you either provide routing through props, or you import it in. 
withRouter was the way to go before because it wasn't automatically there. I don't know what assumptions you should make about providing on the route automagically, so then that leaves you with providing an optional way to get it. If you want to stick with declarative nature of comps, you could also have a route match prop that will give the view the router or not and thus fully abstracting out any need to import something separate.

**Comment by alisd23** [comment]
Any idea how to access `goBack( )` in v4? Doesn't seem to exist on `context.router`.

**Comment by alisd23** [comment]
Anyone wondering about `goBack` and the other history methods, `history` is actually exposed on the context by [react-history](https://github.com/ReactTraining/react-history/blob/master/modules/History.js#L11).

```js
class App extends React.Component {
  render() {
    const { push } = this.context.history;
    return <a onClick={() => push('/somewhere')}>Go</a>
  }
}

App.contextTypes = {
  history: React.PropTypes.object
};
```

**Comment by timdorr** [comment]
@alisd23 Yep, that's correct. Maybe we should wrap up a `withRouter` that also grabs `history` off context?

**Comment by alisd23** [comment]
@timdorr I think it is worthwhile, even though it's literally a 10 line function. It's common enough that people would be adding it to many of their projects so we may as well give it them for free.

**Comment by edygar** [comment]
I'm trying to learn React-Router v4 and I'm really enjoying, so far. I see it as a paradigm shift and so I don't mind do things differently if there's sense on it. I think the [given example](https://github.com/ReactTraining/react-router/issues/3847#issuecomment-247786797) was very contrived and unexplained, the transitioning state ( pending, error ) were completely ignored there, my suggestion would be:

```jsx
export default class Login extends React.Component {
  tryAuthenticate = () => {
    this.setState({ auth: auth.authenticate() });
  }

  componentWillMount() {
    this.tryAuthenticate();
  }

  render() {
    return (
      <Subscribe
        to={this.state.auth}

        pending={<Spinner />}
        resolved={<Redirect to="/" />}
        rejected={() =>
          /* Opportunity to retry with User Interaction */
          <button onClick={this.tryAuthenticate}>It failed…try Again?</button>
        }
      />
    )
      return <Redirect to="/" />;
    }
  }
}
```

And yes, far more code, but here we have view flow completely explained and a reusable component for manage future values and composability.

**Comment by alisd23** [comment]
What do we think `withRouter` should pass down as props? I suppose the `router` and `history` context is a definite. I would also consider moving the location property out of history as a top level prop, because I think the current location is fairly important information.

The props from `withRouter` would then look like this:

![image](https://cloud.githubusercontent.com/assets/5804010/19349802/e1559630-914c-11e6-8cda-8469c47218c5.png)

Thoughts?

**Comment by mbrevda** [comment]
Just to clarify: the only way to call `goBack` is to manually include react-history?

**Comment by alisd23** [comment]
@mbrevda see this comment - https://github.com/ReactTraining/react-router/issues/3847#issuecomment-252966037

**Comment by alisd23** [comment]
React-history is already depended on by React-router, no need to install its

**Comment by mbrevda** [comment]
thanks @alisd23 its working for me now

**Comment by levithomason** [comment]
>React-history is already depended on by React-router, no need to install it

Importing extraneous packages is bad practice.  If the goal is to import `react-history` through `react-router`, I would think `react-router` would provide something like:

```jsx
import { history } from 'react-router'
// or
import history from 'react-router/history'
```

This way, we aren't importing our dependencies' dependencies.

**Comment by ryanflorence** [comment]
follow #4044
