### ISSUE TITLE
How work with local site version without server?

### ISSUE THREAD

**Issue by Slavenin** [ReactTraining/react-router#3943]
Hi!
I try use react router with local version app after build them. Browser open file as link 

> file://app/dir/index.html

But router throw 404 error. How i can setting up router fo work with local version site?
[repo](https://github.com/Slavenin/DisQwerty-browser/tree/react-version)
Tnx!

**Comment by timdorr** [comment]
You have to use a hash history to use a local file. Browser histories don't work without a server.

**Comment by tomprogers** [comment]
I don't think this will work.

Although it's possible to create routing configuration that enables the index route to load when the app is served over the `file://` protocol, navigation around the app breaks down immediately.

The reason navigation fails is that react-router -- like many single-page-app routing modules -- is ultimately built on top of the [Web History API](https://developer.mozilla.org/en-US/docs/Web/API/Window/history). The Web History API is implemented natively in browsers, and it cares about `document.origin` (a read-only property that is specially set to `null` when viewing a page loaded over the `file://` protocol). Core History methods apparently throw exceptions when invoked within documents whose origin is `null`, which prevents react-router from actually carrying out navigation changes. This problem seems to apply whether the router is configured with a `browserHistory` or a `hashHistory`; a fatal exception is thrown when `pushState` is invoked on history.

**Comment by timdorr** [comment]
You can use a hash history on a local file just fine. [We use it in our test suite.](https://github.com/ReactTraining/react-router/blob/6eeb7ad358f987520f5b519e48bdd31f725cbade/modules/__tests__/Link-test.js#L68) Make sure you've configured things correctly.

**Comment by Slavenin** [comment]
@tomprogers, i use hashHistory and this work fine
