### ISSUE TITLE
result.missed is false without miss component | v4

### ISSUE THREAD

**Issue by seeden** [ReactTraining/react-router#3952]
## Version
4.0.0 alpha 3

## Steps to reproduce
```js
<Match exactly pattern="/" component={Index} />
<Match pattern="/graphql" component={GraphQL} />

const result = context.getResult();
expect(result.missed).toBe(true);
```

I am trying to open for example /non-existing-route

## Expected Behavior
result.missed === true

## Actual Behavior
result.missed === false

When I add <Miss> component everything works correctly but I guess that result.missed must be true when I am not using Miss component as well.

**Comment by timdorr** [comment]
This is as designed. That property indicates no Match triggered. It's independent of Miss being used at all.

**Comment by seeden** [comment]
Maybe you don't understand me. It is not an independent as you mentioned. Result.missed === true only when I use Miss component otherwise it is always === false.

**Comment by timdorr** [comment]
Ugh, sorry. I misspoke. 

However, the behavior is still correct. We need to track misses separately from matches, as they can occur out of order during rendering (they require two passes to render). And because of two passes being needed, we need to communicate that back to the context so that you can do a second renderToString(). However, if a miss doesn't occur, then youll have a valid render tree and don't have to re-render. So, that flag basically says "you should or should not render things again".

**Comment by seeden** [comment]
I understand but I am not able to handle missed because after first render is result.missed === true and this is wrong.
