### ISSUE TITLE
is the Match render prop superfluous (v4)?

### ISSUE THREAD

**Issue by mking-clari** [ReactTraining/react-router#3987]
I think we can just pass a functional component as the Match component prop.

```
<Match pattern="..." render={props => <div />} />

// same effect
<Match pattern="..." component={props => <div />} />
```

**Comment by mjackson** [comment]
Great question! There is a subtle difference.

When you use `<Match component>`, we call `React.createElement` for you. If you're using an inline function (that you define on each render) instead of an actual component, React thinks that we're using a different component each time. It would be as if we were doing this:

```js
// first render
React.createElement(<A/>)

// second render
React.createElement(<B/>)

// and so on...
```

So React will actually go through the lifecycle on each render. In contrast, the `render` prop makes it a little more obvious that you're the one responsible for creating the elements, because it's just a function that we call at render time.

We *could* feasibly get rid of the `component` prop and just tell people who want to render a specific component to do `render={() => <TheComponent/>}`. But it's such a common use case that we give you your own prop for it.

Hope that helps!
