### ISSUE TITLE
Handle encoded URLs on initial load

### ISSUE THREAD

**Issue by bkniffler** [ReactTraining/react-router#4124]
I had posted a PR https://github.com/ReactTraining/react-router/pull/4120, but I think I wasn't on the right track there. @pshrmn already posted a few comments.

## Version
4.x

## Test Case
```
it('renders with encoded', () => {
      const Page = () => <div>{TEXT}</div>
      const loc = { pathname: '/%C3%BCber' }
      const html = renderToString(
        <Router intialEntries={[ loc ]}>
          <Match
            pattern="/über"
            component={Page}
          />
        </Router>
      )
      expect(html).toContain(TEXT)
})
```

## Steps to reproduce
Run the test above or try to match similarly in a real project. 

## Expected Behavior
Should decode URL somehow and match.

## Actual Behavior
First load will not match, but if using a <Link to="/über" />, it will match. This happens server and browser side.

**Comment by pshrmn** [comment]
I believe that calling `decodeURI` on the pathname will fix this. That will decode all of the non-reserved characters so that we have an [IRI](https://tools.ietf.org/html/rfc3987) to match against.

There are two locations where this might make sense to do. The first is in `createRouterLocation` and the second is the the `<StaticRouter>`'s `componentWillMount` call (this only works if we only ever need to decode the initial location).

**Comment by bkniffler** [comment]
Like @pshrmn, decoding with decodeURI in createRouterLocation helped me solve the problem. https://github.com/ReactTraining/react-router/pull/4160

**Comment by mjackson** [comment]
Thanks for the heads up, @bkniffler :) The current v4 branch doesn't actually do any URL encoding/decoding. It just takes whatever `location` object it gets from the `history` lib and goes from there. So it seems like this should be a non-issue now.

**Comment by mjackson** [comment]
On second look, this is actually an issue with the history lib, and I'm not 100% convinced it's one we want to "fix". In the OP, @bkniffler is manually populating a memory history's `entries` array using `<MemoryRouter initialEntries>`. In the case of memory history, you're in complete control of the URLs that get added to the history, so you could (should?) actually do the decoding *before* passing them in. With browser-based history objects (browser and hash) it's definitely our responsibility to decode URLs.

Closing for now due to lack of comment from the OP.

**Comment by bkniffler** [comment]
I'm sorry to not respond earlier @mjackson. But currently I've no clue where a solution should be implemented. You say its your responsibility to decode URLs, which I think is true since in the browser based history there is no way to control the initial location / decoding. What exact place do you think needs to be changed? Add a function to history that may manipulate the initial location? Make history accept a custom initial location?

**Comment by mjackson** [comment]
@bkniffler I'm saying you should provide decoded URLs in your `initialEntries` array. Is there any reason you can't?

**Comment by bkniffler** [comment]
Ah, I think I understand now: So I should substitute the BrowserRouter with MemoryRouter in my frontend and take care of initial route decoding via initialEntries and implement writing to the address bar manually? I could try that.

**Comment by mjackson** [comment]
No, don't try changing the URL manually. That's what `<BrowserRouter>` and `<HashRouter>` are for...

**Comment by bkniffler** [comment]
Sorry @mjackson, I don't get it. Only memoryRouter may set initialEntries, but memoryRouter obviously is not a replacement for browser routers (hash/browser). So please enlighten me, how can I get URLs with characters like Umlauts get to work on the initial load, since there doesn't seem to be any way to control the location that is initialized by the browser routers? Am I overseeing something obvious? It sure feels like it..

**Comment by mjackson** [comment]
In the example you provided, you were using `<MemoryRouter initialEntries>`. Are you saying you see URLs coming out of `<BrowserRouter>` that are not encoded properly?

**Comment by bkniffler** [comment]
Yeah, I might not have made it clear and I see the confusion due to my original post using memoryRouter. Originally, I thought this was a problem with the react-routers core functionality, lacking a way to handle this. Now, you made it clear that proper locations should be set upfront, which makes total sense for server/memory routers. 

So, what is the best way to handle URLs with special characters in the browser routers?

**Comment by bkniffler** [comment]
Okay, lets just leave this be and continue with #4319 which is more precise.
