### ISSUE TITLE
Match doesn't apply basename to its pattern

### ISSUE THREAD

**Issue by frux** [ReactTraining/react-router#4157]
## Version
4.0.0

## Test Case
```jsx
<BrowserRouter basename="/test">
    <Link to="/">Go home</Link>
    <Match pattern="/" exactly/>
</BrowserRouter>
```

## Expected Behavior
Both Link and Match have the same url extended by basename ``/test/``.

## Actual Behavior
Link extends its path but Match doesn't
Link ``/test/``
Match ``/``

**Comment by pshrmn** [comment]
It shouldn't. The location that is used for matching has had the basename stripped off of it [0]. Basenames just allow your application to be served from a non-root address, they have no internal effect on RR.

[0] https://github.com/mjackson/history/blob/master/modules/createBrowserHistory.js#L55-L56

**Comment by timdorr** [comment]
@pshrmn is correct here. [We append it for display purposes](https://github.com/ReactTraining/react-router/blob/v4/modules/StaticRouter.js#L45-L57), but it's matched without it.

**Comment by pkosenko** [comment]
The issue seems to have been closed, despite the behavior causing PROBLEMS in applications.  I do not see that a workaround is being offered for what is buggy behavior here.  So I am posting it again, since I have the same problem.

I am using React Router 2.8.1

******************************

Basename + <Link> nightmares in React Router module

I am just learning React and am having nightmares with generated <Link>s in my application, which is running in a subdirectory and has basename defined:

const history = useRouterHistory(createBrowserHistory)({
  basename: '/react_librivox_search'   
});

If I undefine basename, the application will not start up.  However, having basename defined destroys generated <Link>s and (despite navigating to the correct location) causes React Router to display a match() error:

Warning: [react-router] Location "book/140" did not match any routes

location.pathname SHOULD be showing as "react_librivox_search/book/140", NOT "book/140".  In otherwords, basename is not getting added to the front of pathname somewhere in React Router's processing of location after the <Link> is clicked.  AND this causes APPLICATION FAILURE.   I tried a variety of ways of finessing around this, all of which caused strange behaviors (React adds TWO basenames to the path; or it adds hostname in the middle of the path).

Something seems to be really screwed up with <Link> and whatever processing is being done with it.

If you have basename defined, and then try to generate <Link>s like the following, the Links will not work:

        <p><Link to={"book/" + bookObject.id} onClick={this.handleClick}>DISPLAY FULL BOOK 
DATA</Link></p>

I have looked under the hood at match() usage in CreateTransition.js, but I am not enlightened:

        match(location, function (error, redirectLocation, nextState) {
          if (error) {
            listener(error);
          } else if (redirectLocation) {
            history.replace(redirectLocation);
          } else if (nextState) {
            listener(null, nextState);
          } else {
            process.env.NODE_ENV !== 'production' ? (0, _routerWarning2.default)(false, 'Location "%s" did not 

match any routes', location.pathname + location.search + location.hash) : void 0;
          }
        });
      }

Thanks

Peter Kosenko

**Comment by pshrmn** [comment]
@pkosenko This issue had to do with v4 of React Router while yours is with v2/v3. Your problem would also probably be best addressed on Stack Overflow. I did take a quick look at your code, though, and you are providing a relative pathname to your `<Link>` but React Router doesn't handle relative pathnames. You should make sure that the `to` prop is given an absolute pathname. I don't know if that will solve your problem, but it is an issue with your code.

**Comment by pkosenko** [comment]
Thanks for the comment.  All of the documentation for React Router that I see online shows what you are calling "relative path" usage.  I did notice other posts that mentioned using absolute paths.  I have tried supplying them, but they introduce an EXTRA copy of basename into the path.  http://localhost:8083/react_librivox_search/react_librivox_search/book/141 , which causes failure.

So React-Router &t;Link&gt; is actually BROKEN for basename usage in either the case of relative or absolute paths.

So it is not a "stack overflow" user training issue that is needed, but something serious that needs to be looked at in the React-Router package.

**Comment by pkosenko** [comment]
The reason that I posted here is that this is "buggy" behavior.  Documentation is all messed up if indeed you have to use absolute paths (all examples show relative paths).  And your team needs to run tests on use of basename.

Here is an actual test of trying to construct an "absolute" <LINK> with basename defined.  As I think I mentioned, React-Router DISASSEMBLES the link and inserts basename.  But since basename is ALREADY in location, you get TWO copies of the subfolder.  This is bad news for trying to dynamically create links.  I can, of course, string subtract, but that is a weird workaround to HAVE to implement:

        <p><Link to={location + "/book" + bookObject.id} onClick={this.handleClick}>DISPLAY FULL BOOK DATA</Link></p>

http://jstest.dd:8083/react_librivox_search/react_librivox_search/book53

**Comment by pkosenko** [comment]
Does not work with absolute path.  &lt;LINK&gt; is extremely messed up when a basename is defined.  Here's another test:

    var linkRoot = location.href;  // can't use location.replace(), which is a redirection function
    linkRoot = linkRoot.replace("react_librivox_search/", ""); 
 
        <p><Link to={linkRoot + "book/" + bookObject.id} onClick={this.handleClick}>DISPLAY FULL BOOK DATA</Link></p>

GENERATED LINK:

http://jstest.dd:8083/react_librivox_search/book/140   (this is where I want the link to go)

This ERROR appears in the console when the &lt;LINK&gt; is generated.  It is demanding a relative link (pathname is relative), NOT an absolute link.

Warning: A path must be pathname + search + hash only, not a fully qualified URL like "http://jstest.dd:8083/book/140"

ERROR when clicked:

Warning: [react-router] Location "book/140" did not match any routes

**Comment by ryanflorence** [comment]
All of our examples use basename in 2.x and 3.x. Which version are you
using?

**Comment by pkosenko** [comment]
I think I posted this in an earlier post:  

react-router 2.8.1

$ npm list react-router
librivox_search@1.0.0 c:\Users\pkosenko\sites\devdesktop\jstest\react_librivox_search
`-- react-router@2.8.1

People keep telling me that I should be using some other redux-ified router module, but what baffles me is that all the documenation says that react-router should work even IF you are using Redux.

**Comment by pkosenko** [comment]
I think I have the problem identified.  I have been using browserHistory rather than hashHistory.  I am using Apache as a localhost server with the React app in a subfolder of the site (because I have multiple test and study projects in that site).  I set the .htaccess in my app root to the settings recommended by the documentation for browserHistory:

RewriteEngine On
RewriteBase /react_librivox_search
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.html [L]

Those settings apparently are NOT working (and I am not sure what yet will work).  I need to figure what will work when the app is in a subdirectory of the site (maybe add that to documentation, since Apache rules can be confusing?).

When I reset the app to use hashHistory, the component invoked by the path engaged (I have other things to fix about it, but at least it engaged).  So . . . the problem must be the .htaccess specification.

BUT . . . and here's why I still think that the issue belongs here . . . is there any way to get React-Router to give an INTELLIGENT error message that helps identify the problem?  "Cannot match route" is NOT a good error message (especially since the routes DO in fact match).  It is confusing and tends to send one on a wild goose chase trying to figure out what the BUG is in the software.  Unintelligent error messages are as bad as bugs.

I am not sure what the solution would be since I cannot really follow the call stack in the webpack bundle.js.  

But you might begin by testing whether the application is using browserHistory, then whether the paths do in fact  match (via some other mechanism?), then a message suggesting (possibly) that .htaccess redirection to the app page is not working?
