### ISSUE TITLE
history module not found error

### ISSUE THREAD

**Issue by jonballard-rev** [ReactTraining/react-router#4193]
## Version
4.0.0-alpha5
create-react-app 0.6.1 and 0.7.0
No problems with 4.0.0-alpha4

## Steps to reproduce
Create a brand new app using create-react-app.
> create-react-app rrv4test

Install latest react-router v4
> cd rrv4test
> npm install --save react-router@next

Start app
> npm start

Everything OK

Modify App.js and add any import from react-router
`import { BrowserRouter } from 'react-router'`

App reloads and gives compile error:
```
Failed to compile.

Error in ./~/react-router/~/history/createBrowserHistory.js
Module not found: 'warning' in /src/react/rrv4test/node_modules/react-router/node_modules/history

 @ ./~/react-router/~/history/createBrowserHistory.js 9:15-33
```

The console shows import errors from 'invariant' and 'resolve-pathname' as well.  The installation seems fine - everything in place at node_modules/react-router/node_modules/history

I don't see any problems like this with 4.0.0-alpha4 but I need some updates from alpha5.  Thanks for any help and let me know if I can improve this bug report somehow.

**Comment by DrugzZ** [comment]
Hey! 

According to https://react-router.now.sh/quick-start you should install 'react-router' and 'history' package separately. I was wandering why is that, because i did a clean install of an app today, without the history package and everything seems to work. But this may solve your problem. It's just a guess.

**Comment by jonballard-rev** [comment]
> According to https://react-router.now.sh/quick-start you should install 'react-router' and 'history' 

Thanks but that will install react-router 3.0.0.  I'm not sure why the v4 docs say this.  Maybe eventually it will be correct.  To get 4.x today you need to:
`npm install --save react-router@next`

See https://github.com/ReactTraining/react-router/releases/tag/v4.0.0-0 among other places.

**Comment by jonballard-rev** [comment]
BTW, if anyone else is running into this same issue, you can use prior working version
`npm install --save react-router@4.0.0-alpha.4`

**Comment by timdorr** [comment]
What does `npm ls warning` output? What version of npm are you running?

**Comment by jonballard-rev** [comment]
Hello.

With:
`npm install --save react-router@next`

I get

> rrv4test@0.1.0 /src/react/rrv4test
> └── (empty)
> 
> npm ERR! code 1

With:
`npm install --save react-router@next history`

it still won't compile, but I get

> rrv4test@0.1.0 /src/react/rrv4test
> └─┬ history@4.4.0
>   └── warning@3.0.0 

With:
`npm install --save react-router@4.0.0-alpha.4`

> rrv4test@0.1.0 /src/react/rrv4test
> └─┬ react-router@4.0.0-alpha.4
>   └─┬ react-history@0.14.1
>     └─┬ history@4.4.0
>       └── warning@3.0.0 

I'm running npm 2.15.9.  I'll try newer versions.  Thanks.

**Comment by jonballard-rev** [comment]
Upgraded to npm 3.10.8.  Same compile error, although `npm ls warning` gives a better report:

> rrv4test@0.1.0 /src/react/rrv4test
> └─┬ react-router@4.0.0-alpha.5
>   └─┬ history@4.3.0
>     └── UNMET DEPENDENCY warning@^3.0.0
> 
> npm ERR! missing: warning@^3.0.0, required by history@4.3.0

**Comment by timdorr** [comment]
You likely have a bad npm cache. Try running `npm cache clean`, blow away your node_modules, and redo everything to see if that clears it out.

To be honest, I don't know why this is happening, but it's definitely not a react-router issue. It's something with npm (either the cli or the registry). And we're not really the best place to be tracking this sort of issue. I would open up [an issue on their repo](https://github.com/npm/npm/issues/new) because they will have a better idea of what's going wrong. If there's some action we can take to fix things, feel free to tag me or one of the other maintainers and we'll do whatever is needed to get things fixed for you.

**Comment by jonballard-rev** [comment]
OK Tim.  Thank you.  This helped me understand the issue.  It *was* a problem with the older npm.  The old version was not properly installing all the dependencies, for either create-react-app or react-router.  I only had 4 modules under node_modules before.  I now have 30.

After updating npm, I should have tried from scratch with a brand new create-react-app app.  Or, like you said, blow away node_modules:

`rm -rf node_modules`
`npm install`

My app works fine now with the latest react-router.
