### ISSUE TITLE
Change the `to` props in Link while using transition()

### ISSUE THREAD

**Issue by MorganeLecurieux** [ReactTraining/react-router#4214]
Hey !
I am working on a project that will be used on a TV (but through a decoder-box). So __the "onClick" event isn't really appropriate__ since we need to listen to the remote event which are slightly different from the browser events.
Let say I have a component _Binder_ that can deal with the several events of the remote.
My problem is, I'd like to dinamically set the __to__ prop of the _Link_, or at least pass a location to the "transition" function like this : 
```js
<Link>
 {({transition}) => {
   return <Binder  
     onEnter={transition('next-page/enter')} 
     onBack={transition('next-page/back')}/>
 }}
</Link>
```
Which would be great and working (and avoid problems if not specified) : 
Leave the __to__ props required and use it, but if an argument is specified to the transition function, take this one instead.

Maybe I'm missing something and there is actually something already working for this ?
Otherwise, what do you think about implementing this ? I know this is kind of a peculiar case. But it might be useful to simplify some redirections : change the __to__ props of the link according to a state (if the user is certified go to 'forum/certified' otherwise go to 'doyouwanttocertify').

Thank you for your time and your great work !

**Comment by pshrmn** [comment]
If I understand correctly, you are only using a `<Link>` because it provides built-in navigation. I would recommend creating your own component that does navigation for you. Alpha 6 actually removed the `children` function prop, so your example would not work anymore.

Manual navigation is fairly straightforward and you can reference the `<Link>`'s source code if you need. Basically, you just need to add the `router` to the component's `context` and call either its `transitionTo` or `replaceWith` methods.

```js
class Binder extends React.Component {
  static contextTypes = {
    router: React.PropTypes.object
  }

  handleTransition(to) {
    const { router } = this.context
    router.transitionTo(to)
  }

  onEnter(event) {
    // determine the location to navigate to, then call this.handleTransition
  }

  render() {
    // ...
  }
}
```

**Comment by MorganeLecurieux** [comment]
Oh ok, that totally solve the problem.
Thank you for taking the time to give an example :)
