### ISSUE TITLE
Miss is broken

### ISSUE THREAD

**Issue by pshrmn** [ReactTraining/react-router#4221]
In ~~alpha 6~~ the big refactor, the `<Miss>` component is broken. This happens because when the location subscriber resets the match count when it is called, the components do not re-register themselves, so the `<Miss>` component sees the `matchCount` as `0`.

**Comment by timdorr** [comment]
Have you tried this against the latest v4 branch. @ryanflorence did a big refactor, so this might not be an issue now.

**Comment by pshrmn** [comment]
The issue is with the latest branch. I'll dig into it a little bit later, but I'm failing with the most basic example possible.

```js
import React from 'react'
import { render } from 'react-dom'

import { BrowserRouter as Router, Match, Link, Miss } from 'react-router'

const Home = props => (
  <div>Home</div>
)

const Nav = props => (
  <div>
    <Link to='/about'>About</Link>
    <Link to='/other'>Other</Link>
  </div>
)

const About = props => (
  <div>About</div>
)

const Missed = () => (
  <div>Miss</div>
)

const App = () => (
  <Router>
    <div>
      <Nav />
      <Match pattern='/' exactly component={Home} />
      <Match pattern='/about' component={About} />
      <Miss component={Missed} />
    </div>
  </Router>
)

export default App
```

**Comment by pshrmn** [comment]
My original thought that the components do not re-register themselves was not correct. Rather, it has to do with `<Match>` components' subscriber functions' order of execution. This does not affect the components rendered for the initial location.

`<Match>` components functions are being subscribed in the `componentDidMount` function, which means that child `<Match>` components's subscriber functions will be included in the `<StaticRouter>`'s `subscribers` array ahead of their parent's subscriber function.

Now, in the subscriber function, the `<Match>` resets the number of child matches that are registered with it. The subscriber function always registers itself with its parent `<Match>` (updating the parent `<Match>`'s `matchCount`). Unfortunately, because the child subscriber functions are called before the parent's subscriber function, this ends up meaning that any registering in the subscriber function gets wiped out when the parent's subscriber function is called and the parent's `matchCount` is reset to `0`.

At this point, nothing has actually re-rendered but the `<Match>` and `<Miss>` components are all set to re-render. When the `<Miss>` checks if it should render, it looks at its parent `<Match>`'s `matchCount`, and only; renders if the value if `0`. As stated before, the value will always be `0`, so the `<Miss>` will always render.

**Comment by r3verser** [comment]
Same thing, have tried to make auth from docs example, just refactored `const MatchWhenAuthorized` to class strucure, and Miss starts firing every time, so two components renders matched one and Miss. Is there any fix? [**react-router@4.0.0-alpha.6**]

```
<Match exactly pattern="/" component={Home}/>
<Match pattern="/login" component={Login}/>
<MatchAuth pattern="/dashboard" component={Dashboard}/>
<Miss render={({location}) => (
    <div>Nothing matched {location.pathname}.</div>
)}/>
```

```
class MatchAuth extends Component {
  render() {
    let { component: Component, ...rest } = this.props;
    return (
      <Match {...rest} render={
          (props) => (
            this.props.store.isAuthenticated ? (<Component {...props}/>) : (<Redirect to={{pathname: '/login',state: {from: props.location}}}/>)
          )
        }
      />
    )
  }
}
```

**Comment by jaydenseric** [comment]
Interestingly:

```jsx
render(
  <Page>
    <BrowserRouter>
      <Match pattern='/' exactly component={Home} />
      <Miss component={ErrorPage} />
    </BrowserRouter>
  </Page>,
  document.getElementById('root')
)
```

Results in `Uncaught Error: React.Children.only expected to receive a single React element child.`. This happens when adding more than one `Match` or `Miss`; replacing the `Miss` with `<Match pattern='/test' component={Test} />` results in the same error.

Adding a container element under `BrowserRouter` seems to fix the issues:

```jsx
render(
  <Page>
    <BrowserRouter>
      <div>
        <Match pattern='/' exactly component={Home} />
        <Miss component={ErrorPage} />
      </div>
    </BrowserRouter>
  </Page>,
  document.getElementById('root')
)
```

**Comment by dtipson** [comment]
Seeing the same thing here & when using the MatchWhenAuthorized component pattern as well (so maybe something racey caused by that using subcomponents).

I actually may be seeing a similar bit of weirdness with `componentWillMount` and `componentWillUnmount` on the subcomponents of what are two mutually exclusive routes.  When the first route (listed first) goes invalid and unmatches and the second one (listed second) matches and should load, the `componentWillUnmount` in a subcomponent from the first route ends up firing AFTER the `componentWillMount` of the subcomponent second.  If both of those overlapping mismatched methods modify, say, the same place of a redux store, then the state will end up as the unmounted component intended rather than the newly mounted component would have it.

**Comment by billscheidel** [comment]
Is there a build of 4.0 that doesn't exhibit these issues?  Does going back to alpha-5 work as expected?

**Comment by v12** [comment]
@billscheidel no, the issue is present in alpha 5 as well.

**Comment by pshrmn** [comment]
Mostly semantics, but I just realized that alpha 6 released before the refactor came out and there hasn't been a release for the new code. When I said that `<Miss>` is broken in alpha 6, I guess that what I actually meant is that it is broken in published but unreleased code.

**Comment by ryancole** [comment]
I may be encountering this issue.

I see that the current state of `v4` branch differs greatly from what the `4.0.0-alpha.6` release had. I'm unsure of how to clone `v4` and try it out, because `createServerRenderContext` was removed and based on the code changes it's unclear as to how to proceed without it. The tests seem to just use an empty object. I tried that, but then began encountering additional errors, so I've held off on trying to use `v4` branch for now. I'm curious if it fixes the `Miss` issues, though.

Currently, I'm experiencing a situation where if I hit a route that would cause `Miss` to render, everything works as you'd expect when navigating client-side via `Link`s. But, when using server rendering of that route that would render `Miss` I'm encountering a scenario where the client code is attempting to render something different than the server. In this case, the server is rendering the appropriate `Miss` component, but the client appears to be rendering an empty component there.

**Comment by Pajn** [comment]
I this issue still about the published version, or the rewrite?
We are experiencing problems with alpha 6 and are unsure how to proceed, is it still too early to try to use version 4?

**Comment by ryancole** [comment]
This issue is about the published alpha version. The current state of the
v4 branch is much different. It doesn't even have Miss anymore, etc.

I think the published version is too broken to use, at the moment.

**Comment by seeden** [comment]
@ryancole How you are going to handle missing route in the v4-alt version?

**Comment by ryancole** [comment]
@seeden no idea, I'm not familiar with the code for react router. I was just trying to skim over recent commits to `v4-alt` branch to see if I could figure out whether or not a new approach to `Miss` had been added. I couldn't quite figure it out on my own, though.

**Comment by timdorr** [comment]
Just so everyone knows, @ryanflorence and @mjackson are still finalizing the API. The `v4-alt` branch is some work by Michael to try out a different potential implementation. The `v4` branch is basically Ryan's version of things that has been the status quo for a while now. Neither of these are considered complete and the APIs are still very much in flux. Hence, the "alpha" release names, not beta or anything approaching a final version name. 

As with all alpha software, proceed at your own peril. Playing around with these versions and giving feedback is helpful to have us know more use cases and potential problems with the APIs chosen thus far. But please don't rely on this stuff for production software just yet. We're likely to pull the rug out from under you at some point during the process of nailing things down.

Getting back to the issue at hand, `<Miss>` is certainly a big pain point for the current API. `<Match>`/`<Route>` are easy by comparison. Getting the semantics and API right is important, but in some ways this is fighting against React best practices, so it's tough work. Please give the `v4` and `v4-alt` versions a try and let us know your feedback.

**Comment by just-boris** [comment]
> Please give the v4 and v4-alt versions a try and let us know your feedback.

@timdorr I'd like to try v4-alt, as far as I am already using v4-alpha.6, how can I install it?

**Comment by timdorr** [comment]
@seeden
> How you are going to handle missing route in the v4-alt version? I can see just Route without patter for NotFound components

"Miss"ing in the `v4-alt` branch is equivalent to <=3.x, you would use a `/*` pattern to catch-all any missing routes and provide a `<NotFound>` kind of component back.

**Comment by timdorr** [comment]
@just-boris
> I'd like to try v4-alt, as far as I am already using v4-alpha.6, how can I install it?
`git clone ReactTraining/react-router && cd react-router && npm install && npm link` should do the trick. Then `npm link react-router` in any of your projects to use the link'ed version.

**Comment by Pajn** [comment]
> "Miss"ing in the v4-alt branch is equivalent to <=3.x, you would use a /* pattern to catch-all any missing routes and provide a <NotFound> kind of component back.

If I understand correctly, in v4-alt and you can't have multiple routes matching at once. But instead you can nest multiple routers?

I have not been able to try v4-alt yet but one thing I try to deduce from the code is if sub-routers must concern themselves with the full url or just the part relative to the parent router (like in v4 with match). That compose-ability that v4 allows by only concerning children with only the part that is relative is quite amazing and it would be sad if that isn't kept.
If it is kept I don't have much to say for v4 vs v4-alt. Both have things going for them and the react-approach is really the nicest router API I have ever seen.

**Comment by dminkovsky** [comment]
> The current state of the v4 branch is much different. It doesn't even have Miss anymore, etc.

Confused by this. As of right now, the [v4 branch](https://github.com/ReactTraining/react-router/tree/553b56a750072641b532c1113336a706d6f62648/modules) has `Miss.js`.

It is, however, indeed require different from the latest published alpha.

**Comment by dminkovsky** [comment]
Oh, we're talking the v4-alt branch. My bad! Sorry for the spam.

**Comment by ryancole** [comment]
After writing my own basic code using `v4`'s approach, to help better understand the issues, I think that my current assumption is that it's not possible to determine a complete "route structure" using purely `Match` components, without performing some sort of up front render or some more manually-defined static route data structure.

The `v4` approach is a top-down, declarative react approach, in that you can't know what the rendered component tree will look like until you actually render. In order to see down past each component, you must render that component. Without rendering, or providing a static route structure, it's my understanding that doing things like server 404 are not possible.

I believe this is why `v4` branch requires two renders to properly server render. Issues surrounding this technical barrier may also contribute to why `Miss` is so broken.

While this component-based approach is amazing, it seems to me that it has a fundamental issue in that a render will be required in order to know what `Match` were actually rendered, or is a `Miss` was encountered, etc. That or some sort of static analysis step that builds that route structure for you (via babel or webpack maybe?), or manually defining that route structure (similar to react router versions 3 and older).

Without server rendering though, this approach is opened to a lot more options.

**Comment by pshrmn** [comment]
With the `<Miss>`-less `v4-alt` branch having been merged into `v4` and a beta [releasing soon](https://twitter.com/mjackson/status/817811006982238209), I think that it is safe to close this issue.
