### ISSUE TITLE
How to use replace() function in onEnter() function in <Route/>

### ISSUE THREAD

**Issue by hbarve1** [ReactTraining/react-router#4256]
hey I want to replace variable name to lowercase but I'm not finding any way to do so.

can anyone guide me on it?

**Comment by timdorr** [comment]
This is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux. Thanks!

**Comment by VladimirPal** [comment]
@timdorr The problem is that no one answered on this questions on Stack Overflow, i've found few questions that was pretty good described, but without answers.
For example https://github.com/ReactTraining/react-router/issues/2969 i have same issue, but can't find answer, all i can do is go deeper to the source code.
