### ISSUE TITLE
Bind getComponent cache to process.env.NODE_ENV

### ISSUE THREAD

**Issue by hitmands** [ReactTraining/react-router#4345]
The cool [HMR](https://webpack.js.org/guides/hmr-react/) webpack feature does not seem to pair with `<Route getComponent/>` api. More precisely that API seems to be based on an internal cache which skips additional async component fetching. Some people worked around this with [1](https://github.com/gaearon/react-hot-loader/issues/288#issuecomment-263241165) and [2](https://github.com/gaearon/react-hot-loader/issues/288#issuecomment-245988695).

My Idea is to bind the cache with a `config property` or `process.env.NODE_ENV` directly.

**Comment by timdorr** [comment]
[There is no caching in `getComponents`](https://github.com/ReactTraining/react-router/blob/master/modules/getComponents.js). I think the issue is the router isn't returning a new component instance on a hot reload, since the history location hasn't changed. That's just how React works, so it's not our doing nor is it something that can be "fixed". Instead, those workarounds with `getChildRoutes()` are probably your best bet.
