### ISSUE TITLE
Responsive Docs Website for Small Screens

### ISSUE THREAD

**Issue by pshrmn** [ReactTraining/react-router#4386]
**Note**: I have only tested this with Chrome Dev Tool's device mode, but as far as I am aware, the rendered content should be accurate.

Right now, the `<Examples>` and `<APIDocs>` do not display content legibly. Both of those components render a root `<B>` component (`display: block`). Changing those components to `<IB>` seems to fix them on small screens, but that also breaks the regular screen layout.

![examples](https://cloud.githubusercontent.com/assets/1127037/22430226/16c05bb2-e6d3-11e6-9359-eb98e6f71843.png)

![api docs](https://cloud.githubusercontent.com/assets/1127037/22430231/18fac020-e6d3-11e6-856f-81fdecbd7ef5.png)

Landscape mode looks better, so the site isn't unusable on small screens, but it definitely is not ideal.

**Comment by ryanflorence** [comment]
Yeah, we haven't taken a lot of time to consider mobile. Would love some layout ideas.

**Comment by timdorr** [comment]
I don't think the sticky sidebar is even needed on mobile. It's meant as a quick navigation element between the various components and parts of the API. On a mobile device, you generally don't include anchor-based navigation because screen real estate is at a premium. If you just hide it for certain screen sizes, that makes it a lot more usable right off the bat (just checked with Chrome 56 and it's like 90% there with that one change).

**Comment by pshrmn** [comment]
It would be nice to have a way to collapse the different API sections on mobile with a link at the head of each one to expand it (and expand the one that matches the hash on page load). Otherwise there would be a lot of scrolling required.

**Comment by pshrmn** [comment]
![mobile](https://cloud.githubusercontent.com/assets/1127037/22477287/0fcf62f2-e7ab-11e6-90cd-979d32621e5b.gif)

**Comment by ryanflorence** [comment]
FYI I've got designs and am working on them this week for the docs:

1. It emphasizes the environment (right now they were built with just web in mind)
2. It works great on mobile
