### ISSUE TITLE
Cannot update query on same location

### ISSUE THREAD

**Issue by tquetano-r7** [ReactTraining/react-router#4395]
## Version
3.0.2

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Steps to reproduce

```javascript
const {
  location,
  router
} = this.props;

router.push({
  ...location,
  query: {
    foo: 'bar'
  }
});
```

## Expected Behavior

Query string gets updated in-place

## Actual Behavior

Nothing at all. It works fine if I am going to a different `pathname`, however if I stay on the same `pathname` the querystring is never touched.

**Comment by timdorr** [comment]
Is this within your render method or some other lifecycle event? Since you didn't provide a test case as requested, it's hard to know what's going on. My best guess is that you're short circuiting with a shouldComponentUpdate that's not detecting the change because it's not doing a deep comparison. 

Regardless, usage questions like this should be put on Stack Overflow. This isn't a bug in the library.
