### ISSUE TITLE
Consider not polluting component props with router properties

### ISSUE THREAD

**Issue by magicmaaaaan** [ReactTraining/react-router#4424]
Version: 4.0.0-beta.3

Currently, [Route](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Route.js#L106-L108) and [withRouter](https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/withRouter.js#L26-L31) merges all router properties with component props. This includes 11 fairly generically named properties: action, block, createHref, go, goBack, goForward, length, listen, location, push, replace. It seems unnecessary to pollute props like this.

I propose router properties should remain under a single `router` context rather than spreading all the properties into component props.

**Comment by mjackson** [comment]
I'm not opposed to this idea, but what's the real benefit to keeping everything under a `router` prop? Seems like it just means you have to write more code.

```js
const MyComponent = ({ location, match }) => {
  // ...
}
```

vs.

```js
const MyComponent = ({ router: { location, match } }) => (
  // ...
)
```

**Comment by TomiS** [comment]
For example, prop `location` already collides in my app. So it's really possible it happens.

**Comment by timdorr** [comment]
Are you using `connect` on your route components? That (or another HoC) is the only way a prop would collide for the component prop on a Route. For the function child form, you have full control over the props you pass. 

But regardless, that represents a bad pattern of overloading your components with too much responsibility. I see a lot of people using Redux connected components as their route components. This puts a lot of code in one place and makes for really brittle systems. Components are cheap, so make separate ones for routing, state connection, etc. You not only avoid the problems this issue brings up, but you also reduce complexity and chances of creating bugs.

**Comment by TomiS** [comment]
@timdorr That's a solid point. And to be perfectly honest, I haven't yet had any actual collision issues. I just see the danger since we have `Location` as domain object in our app.

I also cheer for not changing the api all the time, so I guess having many props here might not be too bad after all. Hard to say.

**Comment by mjackson** [comment]
I'm interested to hear @ryanflorence' opinion on this. Honestly, I'm indifferent. I think @timdorr has a great point. Feels like this complaint is more about how people currently think about structuring their apps instead of an actual issue with our code.

**Comment by pshrmn** [comment]
I can provide an instance where this was an issue, but it isn't something most people would run into.

If a component that has a namespace collision with one of `context.router`'s properties is wrapped in `withRouter`, then the component's property will be lost because of the order in which the props are spread in `withRouter`. Unfortunately, reversing the order is not a great fix because then `context.router` properties with collisions could then be lost.

```js
const WrappedLink = withRouter(Link)

// this.props.replace will be a function instead of the expected boolean
<WrappedLink replace to='/some/page'>Some Page</WrappedLink>
```

I ran into this issue when I was writing a `whenActive` HOC factory (think `connect` but to make any component `<NavLink>`-like, [source](https://github.com/pshrmn/rrc/blob/master/src/components/whenActive.js)).

There were also other issues with this, such as needing to remove any `context.router` properties from props before spreading them to the wrapped component in case the wrapped component was a built in (`<div>`, etc.).

I am sure @ryanflorence would be glad to know that my solution ended up being to render a `<Route>`, but I would have preferred to use `withRouter`.

**Comment by IljaDaderko** [comment]
Supporting this, in usecases where you just need to pass router props down, you will also pass unnecessary ones that come from `withProps`, having them all under router object would be welcome 👍

**Comment by billyjanitsch** [comment]
@timdorr's point is certainly true for route components, but I think the original point is well-taken for any component wrapped in `withRouter`. Here's an example of the kind of issue this could cause:

```js
const Vacation = props =>
  <div>
    Take a sunny vacation to {props.location}!
  </div>

render(<Vacation location='California' />)
```

Later, I want to add some routing functionality:

```js
let Vacation = props =>
  <div>
    Take a sunny vacation to {props.location}!
    <button onClick={() => props.push('/flights')}>book flight now</button>
  </div>

Vacation = withRouter(Vacation)

render(<Vacation location='California' />)
// oops, location gets rewritten by withRouter :(
```

As @magicmaaaaan pointed out, this is fairly likely to happen with 11 generically named props. Passing just `router` leaves less overall surface area, with a less generic name.

**Comment by atoiv** [comment]
Components passing a load of props to the components that they render, without knowing what props those components expect, is generally a bad practice imho. When there's need to reserve/hijack props of the rendered component, it's better to be 1) explicit about that, and 2) try to minimize the amount of reserved props.

It's essentially about negotiating a deal between parent and a child component. In general case, when a parent component is rendering a specific child component, it's the parent component that is responsible for passing the right props to that child component, because it can **adjust** to the props required by the child component. But in situations like this case, when roles are reversed, and a library provides the parent component, and a developer is left to choose the child to pass to it, it is just courteous for the parent component to try to minimize the reserved footprint on the child components props.

In the latter case, this kind of forced props should also be part of the api documentation.

That being said, separating routed components from HOCed components, like @timdorr said, sounds like a good practice.

**Comment by ryanflorence** [comment]
I'm willing to discuss the tradeoffs here. Here's why we did it this way:

__1. It's easy to avoid collisions with container components:__

```jsx
// the component with a naming collision
const Facility = ({ location }) => <div>{location.city}</div>

// instead of
<Route component={Facility}/>
// do:
<Route render={(router) => (
  <Facility location={someLocation} routerLocation={router.location} />
)}/>

// instead of
const FacilityWithRouter = withRouter(Facility)
// do:
const FacilityWithRouter = withRouter((router) => (
  <Facility location={someLocation} routerLocation={router.location} />
))
```

__2. It's pretty simple to get the API we're talking about with composition__

For collisions with `Route`, you can unwrap it a bit:

```jsx
<Route render={(router) => <YourThing router={router}/>}/>
```

For collisions in `withRouter`, that's just a higher-order component problem, They "compose" but they have the exact same problem as context regarding naming collisions--which is one of the reasons I find component composition less problematic.

However, you can make a namespaced HOC to get the api you want pretty simply using the same composition:

```jsx
const withNamespacedRouter = (Comp) => (props) => (
  <Route render={(router) => (
    <Comp router={router} {...props}/>
  )}/>
)
```


__3. We did it for simpler identity checks in the lifecycle__

In many cases, especially for generic data loading and animations, it's useful to check the identity of `match` or `location` to know if the location changed.

```jsx
componentDidUpdate(prevProps) {
  if (prevProps.match !== this.props.match) {
     this.doTheStuff()
  }
}
```

Because the `router` object we're talking about is currently mutated so we get some performance (maybe negligible?) wins by not having to construct the thing for every part of the app that gets access to its properties.

If we passed in a `router` namespace to route components, then we'd need to construct a new object every render to avoid identity checks on `router.match` or `router.location` always returning `true`.

Additionally, we'd have to be mindful of `PureRender` implementations by not sending a new `router` object every render unless the location actually changed.

__4. We also did it for convenience__

This is ugly no matter how you slice it:

```jsx
const Thing = ({ router: { match : { params : { userId } } } }) => (
  <div>{userId}</div>
)
const Thing = (props) => (
  <div>{props.router.match.params.userId}</div>
)
```

It's convenient to have one less level of nesting.

__Summing up__

I'm not totally opposed to this, I just don't think the collision problem is a big deal since it's easily composed around. And, correct me if I'm wrong, that's the only problem. So I guess I'd need more convincing that these props names would really lead to confusing situations.

I think of these route components (whether `<Router component/>` or `withRouter` as exactly that, "a route component" that has a bag of props about routing. I like documenting and using components more than objects, cause you get all the normal expectations (like simpler propTypes, lifecycles and prev/next prop comparison, etc.)

**Comment by ryanflorence** [comment]
Thinking about this more, I can explain the problem more simply.

The props to a route component are both data and imperative API.

`match`, `location`, `length`, `index` are relevant data (length and index are very useful in non-browser envs like native and VR)

All the stuff on history is imperative API

everything else

**Comment by ryanflorence** [comment]
Sorry about that ^ clicked "close and comment" because I intuitively thought it was "cancel" 😆

**Comment by mjackson** [comment]
Great explanation @ryanflorence, thanks. I'm pretty sure the potential naming collision was the only real issue, and, as I already said, that's not really an issue with our code but just more about how people think about using our code. I, for one, like the separate props. It's just less typing and generally easier to deal with.

Thanks for the discussion everyone. I think we'll leave it as-is for now. :)

**Comment by ryanflorence** [comment]
FYI, we didn't circle back to this issue. For those following, the final API is going to be `{ match, location, history }` instead of `{ ...history, match }`.

It gets passed to `withRouter`, `<Route render>`, `<Route children>`, `<Route component>`
