### ISSUE TITLE
react-router@^4.0.0-alpha.5 is not compatible

### ISSUE THREAD

**Issue by cpietsch** [ReactTraining/react-router#4465]
When running `npm install react-router@^4.0.0-alpha.5` you will be forwarded to the latest beta `react-router@4.0.0-beta.4` which is **not** compatible with the 4 alpha.

> npm: ^version "Compatible with version"

This broke quite some projects for me and I had to lock it to `4.0.0-alpha.5` by removing the `^`

**Comment by pshrmn** [comment]
Breaking changes tend to happen with alpha software. I would recommend upgrading your projects to the new version as that will be the API going forward. For the most part, that will just be changing `<Match exactly pattern='/about' />` to `<Route exact path='/about' />` and grouping routes in a `<Switch>` instead of using `<Miss>`.

**Comment by cpietsch** [comment]
The new router also threw some errors regarding createElement.
Thats when I returned to alpha 5.
