### ISSUE TITLE
Shouldn't the Link have the option to keep the query string intact?

### ISSUE THREAD

**Issue by ruifortes** [ReactTraining/react-router#4515]
I know you can pass {pathname, search} but you'll need route props or context to figure existing query string and pass it to the Link.
This could be cumbersome if the app uses query string to store state between navigation.
I could for instance have a query var stating that a messenger box or a product cart is open and it should continue to be regardless of navigation.

I've been passing querystring around but have decided to create a Link wrapper to ease up the task but maybe it should be natively supported in the Link

**Comment by timdorr** [comment]
Is this for 4.0? The search is the raw query string and [gets appended to the URL when it's href'd](https://github.com/ReactTraining/history/blob/master/modules/PathUtils.js#L34-L46). I'm not following what the issue is here, sorry.

**Comment by pshrmn** [comment]
I think that @ruifortes' URL scheme relies on every URL including some state that is handled using the `search` string. The proposed idea is to have a built-in way for _every_ `<Link>` to automatically add the current `search` string to the `location` object that is pushed to `history`.

That is 1) easy enough to do with a custom component and 2) almost certainly feature bloat because I don't imagine many people would have a use for that.

**Comment by ruifortes** [comment]
Imagine that you have a "product cart" always open and can continue navigating.
If you navigate to a product list and every item in that list has a Link to the product page you would have to include the searchstring in every one.
If you close the cart or event change the card state (like going to a different checkout section) you would have to rerender all the product list Links to include the new updates searchString representing the cart state.
