### ISSUE TITLE
[V4] Example for Query Strings needed

### ISSUE THREAD

**Issue by BerndWessels** [ReactTraining/react-router#4527]
Hi

Could you please provide an example how to deal with query strings in V4.

`/list?id=5&sort=true`

how would a `<Route>` look like that matches and how to extract the params `id` and `sort`?

**Comment by pshrmn** [comment]
The search string is not used in matching locations, only the pathname.

```js
<Route path='/list' component={List} />
```

You can parse the current `location.search` string to get the query params as an object. There are a lot of different options for parsing/stringifying query objects. `qs` is a popular one.

```js
import { parse } from 'qs'

const List = ({ location }) => {
  const query = parse(location.search)
  return (
    <ul>
      <li>ID: {query.id}</li>
      <li>Sort: {query.sort}</li>
    </ul>
  )
}
```

**Comment by weishijun14** [comment]
it`s awesome! i need it right now! （我正好需要！不知道怎么用英语说）

**Comment by crazyyi** [comment]
I don't understand why I have to use `history.location` to get the `search` string. Otherwise if I just use `location` I will have to click twice on the link to be able to get the query. I am routing the link so that the component goes back to itself. This is in a paging implementation in a HackerNews client demo I wrote.

**Comment by abdulsoni** [comment]
rfgtfghfg
