### ISSUE TITLE
Relative Routes + Links

### ISSUE THREAD

**Issue by ryanflorence** [ReactTraining/react-router#4571]
Pretty sure this is all we need, we can cut/paste the stuff into core Route/Link, or export `<RelativeRoute>` and `<RelativeLink>`, or keep it external, whatever, but with each route putting itself on context as `router` it got real easy.

```jsx
import React, { Component, PropTypes } from 'react'
import BaseRoute from 'react-router-dom/Route'
import BaseLink from 'react-router-dom/Link'

class Route extends Component {
  static contextTypes = {
    router: PropTypes.object
  }

  getPath() {
    const { path } = this.props
    const isAbsolute = path.startsWith('/')
    const parent = this.context.router
    // todo handle `/blah/ + blah` turning into `/blah//blah`
    return isAbsolute ? path : (
      parent.match ? `${parent.match.url}/${path}` : `/${path}`
    )
  }

  render() {
    return <BaseRoute {...this.props} path={this.getPath()}/>
  }
}


class Link extends Component {
  static contextTypes = {
    router: PropTypes.object
  }

  getTo() {
    const { to } = this.props
    const isAbsolute = to.startsWith('/')
    const { router } = this.context
    return isAbsolute ? to : (
      router.match ? `${router.match.url}/${to}` : `/${to}`
    )
  }

  render() {
    const to = this.getTo()
    return <BaseLink {...this.props} to={to}/>
  }
}

export { Route, Link }
```

I just used it in this app and it works great:

```jsx
import React from 'react'
import { BrowserRouter as Router } from 'react-router-dom'
import { Link, Route } from './Relative'

const PEEPS = [
  { id: 0, name: 'Michelle', friends: [ 1, 2, 3 ] },
  { id: 1, name: 'Sean', friends: [ 0, 3 ] },
  { id: 2, name: 'Kim', friends: [ 0, 1, 3 ], },
  { id: 3, name: 'David', friends: [ 1, 2 ] }
]

const find = (id) => PEEPS.find(p => p.id == id)

const RecursiveExample = () => (
  <Router>
    <Person match={{ params: { id: 0 }, url: '' }}/>
  </Router>
)

const Person = ({ match }) => {
  const person = find(match.params.id)

  return (
    <div>
      <h3>{person.name}’s Friends</h3>
      <ul>
        {person.friends.map(id => (
          <li key={id}>
            {/* relative */}
            <Link to={''+id}>
              {find(id).name}
            </Link>
          </li>
        ))}
      </ul>
      {/* relative */}
      <Route path=":id" component={Person}/>
    </div>
  )
}

export default RecursiveExample
```

#4539 
#4459

@pshrmn @mjackson @wmertens @timdorr See any holes in this?

**Comment by timdorr** [comment]
There's a differing amount of "relativeness" to this approach. It only handles (when the parent is `/foo`) something like `path="bar" -> path="/foo/bar"`. 

I think the intent of the other approaches is more robust relativity (yeah, that's the word!). So you could also do `path="../bar" -> path="/bar"` or `path="../../bar" -> throw Error()`. The point being to support all the relative stuff in hrefs that the DOM supports. In particular, the ability to "navigate up" easily.

**Comment by timdorr** [comment]
And that's not to say the composition approach couldn't be applied. You just need something like [`resolveLocation`](https://github.com/pshrmn/react-router/blob/54626354412b4a9421ddaa653ac044ac9932026b/packages/react-router/modules/resolveLocation.js) to be as robust as possible. But then the question is raised: why have this be a separate component? Why not just bundle it into `<Route>` and `<Link>` directly, since it's really just a function on one prop?

**Comment by ryanflorence** [comment]
I don't think `../` is something I want to support. What does it mean?

```jsx
<Route path="accounts"/>
// then a child in there somehwere
<Route path="foo/bar/baz"/>
```

If I'm at `/accounts/foo/bar/baz` and I link to `../` does that take me to `/accounts/foo/bar` or `/accounts`?

Because the Links and Route's are relative to the entire path of the parent, so does link up go up to the parent or does it work on the `location.pathname`?

I just see confusion. I really don't think it's a common need to link "up". Linking "down" and "laterally" is what people want 99% of the time.

**Comment by ryanflorence** [comment]
> Why not just bundle it into <Route> and <Link> directly

Because there are too many questions right now. When external components are put through the ringer long enough, then we know exactly what the constraints are and won't have to fiddle around with the core API. When it comes in, it comes in solid.

**Comment by pshrmn** [comment]
* `<Link>` needs to support both strings and location objects. That is an easy change, just missing from the example code.
* Relative `<Redirect>`s should work like relative `<Link>`s. I'm not sure how often this would be done, but they both support the same `to` signature, so it is another easy change.
* When `match.url` is falsy, it can be incorrect to assume that the relative path should just have a slash prepended (see #4560 case 1).
* A relative `<Link>` has to listen to `history` in order to always resolve with the correct `match.url`. This is probably the most frustrating part of this because of how many extra listeners it adds. I considered adding a separate `<RelativeLink>` so that only those listen for changes, but `<NavLink>` only works for `<Link>`s, so I had to merge it in.
`(╯°□°）╯︵ ┻ǝʇɐpd∩ʇuǝuodɯoƆplnoɥs┻`
* I'm not sure how this works with dot relative paths. You can test out [this example](https://github.com/pshrmn/react-router/blob/54626354412b4a9421ddaa653ac044ac9932026b/packages/react-router-website/modules/examples/RelativeLinks.js) which was inspired by the recursive example.

@ryanflorence I just saw your comment about not supporting dot relative paths. Will expand on why I think that they are necessary in another comment.

As an aside, are there any examples that the React team has posted showing when using `context` is unreliable? From what I have seen, this only happens when someone is already using subscribers, which re-render a component before the `getChildContext` of their parent gets called, so they end up using the previous `context`.

**Comment by ryanflorence** [comment]
Thanks @pshrmn 

> A relative `<Link>` has to listen to history ... (╯°□°）╯︵ ┻ǝʇɐpd∩ʇuǝuodɯoƆplnoɥs┻

Ah, yes. So frustrating.

Okay, I'd say continue on your work then, you've clearly got your head wrapped around it. We really don't want `Link` to listen to history, that's why NavLink got split out. Maybe we make `RelativeLink` or add relativity to `NavLink` and name it something else, `SlowLink` or `UsesMoreMemoryLink` or a name that is actually good.

Another option that I really don't like as the library author but really love as the consumer: we just have one Link. It detects if it has `activeClassName`, `activeStyles`, or a relative path, and then subscribes/unsubscribes to history.

**Comment by pshrmn** [comment]
First, I missed this in my previous list:
* Resolving a `<Route>` using `match.url` means that the params parsed from earlier routes will not be passed to that `<Route>`. You could use `match.path`, but that will mean that you're creating a more complex matching regular expression in order to capture values that you have already parsed out of the URL.

I personally think that dot relative paths are the most useful feature of adding relative links. It allows you to write reusable components that don't have to have a knowledge of their actual location.

```js
<Route path='albums' render={() => (
  // match = { url: '/albums' }
  <Switch>
    <Route path='' render={() => (
      // match = { url: '/albums' }
      <div>
        // here, simple concatenation can be used to resolve paths
        {
          albumAPI.loadAlbums()
            .map(a => <Link key={a.id} to={a.id}>{a.name}</Link>
        }
      </div>
    )} />
    <Route path=':albumID' render={() => (
      // match = { url: '/albums/<albumID>', params: { albumID: <albumID> }}
      <Switch>
        <Route path='' render={() => (
          // match = { url: '/albums/<albumID>', params: { albumID: <albumID> }}
          // generate links to images similar to album links, nothing interesting
          {
            albumAPI.getPhotos(match.params.albumID)
              .map(p => <Link key={p.id} to={p.id}><img src={p.src} /></Link>
          }
          // going back to the /albums page can be done with dot relative paths
          // this isn't particularly interesting, but means that this component could be
          // reused in someone's /galleries page or /user/profile/<id>/albums/ page
          // and still work.
          <Link to='..'>Back</Link>
        )} />
        <Route path=':photoID' render={() => (
          // assuming parent params are merged:
          // match = {
          //   url: '/albums/<albumID>/<photoID>',
          //   params: { albumID: <albumID>, photoID: <photoID> }
          // }
          // here, a photo might have links back to its album and to sibling photos. Without
          // dot relative paths, you would have to build the URLs using params
          <Link to={`/albums/${match.params.albumID}`}>Back to Album</Link>
          //  or split match.url in order to figure out its parent URL.
          <Link to={`${match.url.split('/').slice(0, -1).join('/')}/${siblingID}`}>Next</Link>
          // with dot relative paths these become
          <Link to='..'>Back to Album</Link>
          <Link to={`../${siblingID}`}>Next</Link>
        )} />
      </Switch>
    )} />
  </Switch>
)} />
```

**Comment by ryanflorence** [comment]
@pshrmn what about: https://github.com/ReactTraining/react-router/issues/4571#issuecomment-281405901 ?

**Comment by ryanflorence** [comment]
sorry, I split this conversation into a new thread, closing in favor of the pull requests #4539 #4459

**Comment by pshrmn** [comment]
Just to answer the question here, it would be relative to `match.url`. If `match.url = '/accounts/foo/bar/baz'`, the path `..` resolves to `/accounts/foo/bar`. This would render the `accounts` route's component, which ideally either has a `<Route>` that matches that path or has a "no match" component to handle the miss.

```js
<Route path='accounts' render={() => (
  <Switch>
    <Route exact path='' render={() => (
      <Link to='foo/bar/baz'>Deep Link</Link>
    )}/>
    <Route path='foo/bar/baz' render={() => (
      <Link to='..'>Up</Link>
    )}/>
    <Route render={() => <div>Failed to match pathname</div>}/>
  </Switch>
)}/>
```

This definitely can cause confusion when a route's path is deeply nested, but I think that clear documentation should help here (at least for people who read the documentation, for everyone else :man_shrugging:) Something along the lines of this (maybe with an example?).

>A `<Link>` can use double dot notation (`..`) to resolve a location relative to its parent `match.url`.

**Comment by JimmyVV** [comment]
if we want to use relative Link,  should keep in mind that the `href` must be trailed with a '/'. so the Link `to='./sam'` could work.

and Why we couldn't use relative Route? I can't find some detail referring to [training](https://reacttraining.com/react-route)

**Comment by pshrmn** [comment]
@JimmyVV That approach to resolving relative URLs is more of a quirk than a real solution. The approach that we are working towards is one that will always work without having to mess with the parent route's path. Also, instead of using dot relative paths, you would just not include a leading slash for relative paths.

There are a couple of PRs with this pretty much implemented, it is just a matter of verifying that everything works as expected.
