### ISSUE TITLE
Animating a Switch which has children containing Switches and Redirects causes major issues

### ISSUE THREAD

**Issue by firasdib** [ReactTraining/react-router#4579]
## Version
4.0.0-master

## Test Case
Assume you have a top level component that has the basic routing table which animates them as they mount/unmount:
```js
<CSSTransitionGroup>
<Switch key={location.key} location={location}>
  <Route path="/foo" component={Foo} />
  <Route path="/bar" component={Bar} />
  <Route path="/" component={Default} />
<Switch>
</CSSTransitionGroup>
```

Default.js has the following routes:
```js
<CSSTransitionGroup>
<Switch key={location.key} location={location}>
  <Route path="x" component={x} />
  <Route path="y" component={y} />
  <Redirect to="/x" />
<Switch>
</CSSTransitionGroup>
```

## Steps to reproduce
If you are on `/` and `Default` is rendered, and then navigate to `/foo`, you will see some flickering on the screen and eventually you're thrown back to `/`.

## Expected Behavior
No flickering and router should continue to function normally.

## Actual Behavior
Flickering animations and thrown back to `/`

**Comment by ryanflorence** [comment]
`<Route path="/" component={Default} />`

that should be:

`<Route exact path="/" component={Default} />`

Otherwise everything matches `/`, might or might not be causing problems here.

More importantly, `Redirect` in a `Switch` needs to have a `from` and `to` prop, not just `to`.

Additionally, you've got some relative paths in there (`path="x"`) which aren't supported.

So, clean all that up and see what happens. I'll reopen if there's still a problem.

**Comment by firasdib** [comment]
Sorry, I was a bit in a hurry when I wrote this.

So the reason I don't want to use `exact` for `path="/"` is that I want to be able to define which routes should match in the `Default` component and redirect there if necessary. Otherwise I would end up with one big routing table a la v2/3 again.

Why does a `Redirect` need a `from`? How do I achieve the 'catch-all' behavior then? I would imagine omitting `from` would be the same as `<Route render={() => <Redirect to="..." />} />`, but maybe im wrong?

Here is the exact tables:

Root.js:
```
            <Switch key={location.key} location={location}>
              <Route
                path="/library"
                component={RegexLibrary}
              />

              <Route
                path="/settings"
                component={SettingsPage}
                exact
              />

              <Route
                path="/account"
                component={AccountPage}
              />

              <Route
                path="/r/:permalinkFragment(\w+)/:version(\d+)"
                component={RegexEditor}
              />

              <Route
                path="/"
                component={RegexEditor}
              />
            </Switch>
```

RegexEditor.js:
```js
              <Switch key={location.key} location={location}>
                <Route
                  path={`${match.path}/tests/:tools(codegen|debugger)?`}
                  component={UnitTestArea}
                  exact
                />

                <Route
                  path={`${match.path}/:tools(codegen|debugger)?`}
                  component={TestStringArea}
                  exact
                />

                <Redirect to="/" />
              </Switch>
```

Here's a table showing what I want

| User visits     | Rendered Component |
| ------------- | ------------- |
| / | RegexEditor + TestStringArea  |
| /r/foo/1  | RegexEditor + TestStringArea  |
| /r/foo/1/bar  | Redirected to / |
| /bar  | Redirected to / |
| /tests  | RegexEditor + UnitTestArea |
| /tests/codegen  | RegexEditor + UnitTestArea |

How could I achieve something similar to that but with animations working?

**Comment by firasdib** [comment]
@ryanflorence Do you have any input on this? Can we chat on Discord or similar?

**Comment by pshrmn** [comment]
@firasdib One of your issues is that you are using `location.key` as the transition key. 

Given the app:
```js
const App = ({ location }) => (
  <CSSTransitionGroup>
    <Switch key={location.key}>
      <Route exact path='/' component={Home}/>
      <Route path='/color' component={Colors}/>
    </Switch>
  </CSSTransitionGroup>
)

const Colors = ({ location, match }) => (
  <CSSTransitionGroup>
    <Switch key={location.key}>
      <Route exact path={`${match.url}`} component={ColorPicker} />
      <Route path={`${match.url}/:color`} component={SpecColor} />
    </Switch>
  </CSSTransitionGroup>
)
```
If the first location is: ` url: '/color/red', key: 'abcdef' }`, it will create the following structure:

```js
<App>
  <CSSTransitionGroup>
    <Switch key='abcdef'> // appear
      <Route match={{ url: '/color' }}>
        <Colors>
          <CSSTransitionGroup>
            <Switch  key='abcdef'> // appear
              <Route match={{ url: '/color/red' }}>
                <SpecColor/>
```
Then, the user might navigate to: `{ url: '/color/blue', key: 'ghijkl' }`. Because this has a different key than the previous URL, this means that there will be a new base `<Switch>` is rendered instead of re-using the existing one.
```js
<App>
  <CSSTransitionGroup>
    <Switch key='abcdef'> // leave
      <Route match={{ url: '/color' }}>
        <Colors>
          <CSSTransitionGroup>
            <Switch  key='abcdef'> // leave
              <Route match={{ url: '/color/red' }}>
                <SpecColor/>
    <Switch key='ghijkl'> // enter
      <Route match={{ url: '/color' }}>
        <Colors>
          <CSSTransitionGroup>
            <Switch  key='ghijkl'> // appear
              <Route match={{ url: '/color/blue' }}>
                <SpecColor/>
```
What I believe you want to render is:
```js
<App>
  <CSSTransitionGroup>
    <Switch key='/color'>
      <Route match={{ url: '/color' }}>
        <Colors>
          <CSSTransitionGroup>
            <Switch  key='/color/red'> // leave
              <Route match={{ url: '/color/red' }}>
                <SpecColor/>
            <Switch  key='/color/blue'> // enter
              <Route match={{ url: '/color/blue' }}>
                <SpecColor/>
```
This exposes an issue with the `<Switch>` component, which is that you do not have a way to pass `match.url` to the `<Switch>` as its key. This is unfortunate, because it would work well as the key here. A `<TransitionSwitch>` that wraps the matched `<Route>` in a `<CSSTransitionGroup>` would probably work. I have done a little experimenting along those lines, but not enough to confirm that that would be the way to go.

**Comment by firasdib** [comment]
I see. Please get back to me if you find out how this can be solved. The match object is available in the switch, so perhaps that can be used somehow?

**Comment by firasdib** [comment]
Also, where can I read about `Redirect` in a `Switch`? Because right now, no matter what I do, I get stuck in this redirect loop.

**Comment by ryanflorence** [comment]
Still working on docs, it's beta, so you can read about it in the source :)

**Comment by firasdib** [comment]
@ryanflorence I can not see any `from` prop? https://github.com/ReactTraining/react-router/blob/v4/packages/react-router/modules/Redirect.js#L16-L22

**Comment by ryanflorence** [comment]
Even the code needs more docs :P it only works in switch, and then eventually handled in matchPath

**Comment by firasdib** [comment]
Oh okay. So the `from` in a `<Redirect>` in a `<Switch>` operates like the `path` in a `<Route>`?

**Comment by firasdib** [comment]
@pshrmn Do you have any news for me :-)?

**Comment by pshrmn** [comment]
@firasdib You can check out this [`wrapSwitch` HOC](https://github.com/pshrmn/rrc/blob/master/docs/wrapSwitch.md) in `rrc`. The component it creates isn't a drop in replacement for `<Switch>` (because I prefer passing a `routes` array over using elements and I don't support redirects as routes), but it is the same idea.

I've tested it out with a simple app and it seemed to work pretty well. Redirects are a bit tricky and you might need to mess around with the `key` a bit, but I think that they can still work.
