### ISSUE TITLE
Wrong version of history library in package.json ?

### ISSUE THREAD

**Issue by kbukum** [ReactTraining/react-router#4586]
Hello , I checked package.json file of the react-router library and as I see you are using  history library in dependencies like that "history": "^3.0.0". But new version of "history" library completely changed path structured. That's way I got error when using history library by installing react-router. Because history library is coming last version because of defined upgrade version flag "^" ("history": "^3.0.0")  .  After I installed history library by strict version like npm install history@3.0.0 --save then problem solved.

**Comment by timdorr** [comment]
history 3.2.1 should be what's installed with that dependency. While 4.5.1 is the latest, we don't support it in react-router 3.x (yet?). The caret version will install any 3.x.y version, not anything on the 4.x side. 

I'm not sure how that would have happened, but it might be an out of date npm version. Not sure, but that's definitely not what happens for me (otherwise our Travis builds would fail)

**Comment by kbukum** [comment]
Hello @timdoor. Actually on mac os I have not seen error about this. But I got this error on windows system. 

Thank you for quick response. I will check it again.
