### ISSUE TITLE
match path with optional params (v4)

### ISSUE THREAD

**Issue by AgentChris** [ReactTraining/react-router#4591]
Hey guys:
Can i match all routes with a path like this:

/work/:workId(/:stepName)(/:goodId/:stepName)

I expect to catch all the routes with the following paths:

/work/work_id_12/step1
/work/work_id_12/good_id_11/step1

**Comment by AgentChris** [comment]
the optional params doesn't seem to work

**Comment by pshrmn** [comment]
v4 uses `path-to-regexp`. You can check its [documentation](https://github.com/pillarjs/path-to-regexp#optional) on how to format params. This is different than in previous versions of React Router.

Personally instead of trying to overload the `path`, I would write this something like:

```js
<Route path='/work/:workId' component={WorkRoutes} />

const WorkRoutes = ({ match }) => (
  <Switch>
    <Route exact path={`${match.url}`} component={Work} />
    <Route path={`${match.url}/:goodId/:stepName`} component={Step} />
    <Route path={`${match.url}/:stepName`} component={Step} />
  </Switch>
)
```

You can test out route configuration using this [route tester](https://pshrmn.github.io/route-tester/#/)

**Comment by AgentChris** [comment]
thanks man this is really usefull :)
