### ISSUE TITLE
[v4] Animated route transitions with previous route

### ISSUE THREAD

**Issue by IljaDaderko** [ReactTraining/react-router#4596]
Hey guys,

v4 is insanely good in react-native 👍 so much nicer than default routing solution. There is use case I can't figure out on my own and wanted to see if you might be able to help out.

I need to animate between routes, to start with something simple fade out previous route and fade in next one. Next routes fade in is pretty straight forward, just animation in componentDidMount with some delay, it is first task that I am having trouble with as as soon as route changes view associated to it is instantly unmounted hence I have no time to perform any sort of animation.

Any ideas?

**Comment by medv** [comment]
https://reacttraining.com/react-router/examples/animated-transitions

relevant

**Comment by taurose** [comment]
From what I understand thus far about v4, you have three basic options to work around the unmounting:

- control your `<Route>`s by passing `location` manually (which can be kept in state). Probably not too helpful in your situation though, since you don't know which of the locations (current or previous) matches
- use `<Route children>` ([docs](https://reacttraining.com/react-router/#route.children)) which is always rendered and gives you the match state so you could keep the component mounted longer when going from match to no match
- don't use `<Route>` directly and roll your own component similar to `<Switch>` by using `matchPath` ([docs](https://reacttraining.com/react-router/#match))

**Comment by timdorr** [comment]
> use `<Route children>` ([docs](https://reacttraining.com/react-router/#route.children)) which is always rendered and gives you the match state so you could keep the component mounted longer when going from match to no match

This is generally the best solution and what [the animation example uses](https://reacttraining.com/react-router/examples/animated-transitions). You basically switch on and off the rendering of the route component with `match` and control the transitions therein with something like React Motion or CSSTransitionGroup. Ryan has some example code here: https://github.com/ReactTraining/react-router/issues/4351#issuecomment-281198187
