### ISSUE TITLE
Add version number property to ReactRouter

### ISSUE THREAD

**Issue by mikecao** [ReactTraining/react-router#4612]
I'm requesting a version number property be added to the global `ReactRouter` object, similar to `React.version` and `ReactDOM.version`. It's useful to be able to quickly validate the current version in the console.

**Comment by timdorr** [comment]
That's another thing to maintain alongside the npm package version. Right now, there isn't good tooling for keeping it in sync with the package.json (where we have `npm version`), so it would be error prone. If you're pulling a UMD version from something like unpkg.com, you should be to see what version is requested either in the HTML or your dev tools' network activity. 

React is special because it's so core to a lot of projects at Facebook and they run multiple versions simultaneously, so knowing the version at runtime actually makes sense for them. I don't know if it makes so much sense for React Router, though.

**Comment by mikecao** [comment]
@timdorr Fair enough. Just a thought though, it looks like you're already using webpack and the DefinePlugin, so you could define a VERSION placeholder and fill it in from package.json during the build. Something like `'VERSION': JSON.stringify(require('./package.json').version)`.
