### ISSUE TITLE
Can't run examples with 4.0.0-beta.6

### ISSUE THREAD

**Issue by h4m3d** [ReactTraining/react-router#4660]
I got 2 error:
1. Warning: Failed context type: The context `router` is marked as required in `Link`, but its value is `undefined`.

2. Uncaught TypeError: Cannot read property 'createHref' of undefined.

**Comment by hihuz** [comment]
Hey, I had the same issue yesterday.

The Link component recieves a 'history' context rather than 'router' but its contextTypes expects 'router'.

It is fixed in 4.0.0-beta.7 I believe, you can force install that version if you want to try out the examples (or just replace all references to 'router' by 'history' in your node_modules Link.js

**Comment by fernandojunior** [comment]
+1

**Comment by jktravis** [comment]
Looks like this change also changed how basename works. I was getting:

`servername/subdir/route`

Now I'm getting

`servername/http://servername/subdir/route`

**Comment by timdorr** [comment]
This is fixed in the latest beta.
