### ISSUE TITLE
`match` function different behavior in server render

### ISSUE THREAD

**Issue by chikara-chan** [ReactTraining/react-router#4677]
## Version
3.0.2

## Steps to reproduce

``` js
async function clientRoute(ctx,next){
    let _renderProps

    match({routes,location:ctx.url}, (error,redirectLocation,renderProps)=>{
        _renderProps = renderProps
        console.log(1)
    })
    console.log(2)
    
    await ctx.render('index',{
        root: renderToString(
            <Provider store={store}>
                <RouterContext {..._renderProps}/>
            </Provider>
        )
    })
}
```

I have such this code in server-side.
In development environment, I use `babel-register` to require React components,  the result is that `match` function is in sync. 
``` js
// Output
1
2
```
In production environment, I use `webpack2.2.1` to bundle server files. But in puzzle, the result is proved that `match` function is in async.
```js
// Output
2
1
```
Why?

**Comment by ryanflorence** [comment]
If you could add a test case to the v3 branch that would make it easier to track down. Our focus is on v4, but we will happily merge fixes into v3 if you can track this down.

**Comment by chikara-chan** [comment]
here is a simple [example](https://github.com/chikara-chan/react-router-bug-reporter) to reproduce the problem

**Comment by taurose** [comment]
I think your problem is the way you polyfilled `require.ensure` : https://github.com/chikara-chan/react-router-bug-reporter/blob/master/client/routes.js#L1-L6

Whether `match` runs sync or async depends on whether there are any async routes (`getComponent` etc) or async hooks. In your case, `require.ensure` provided by webpack (i.e. when building with `run build`) is always async, while your shim (`run dev`) is always sync. And since this is your only async route/hook, it directly affects the behavior of `match`.

You can fix this by making your `require.ensure` async, too:

```js
if(typeof require.ensure !=='function'){
    require.ensure = function(dependencies,callback){
      setTimeout(function() {
         callback(require)
      });        
    }
}
```

**Comment by timdorr** [comment]
@taurose Good find! Yeah, that's definitely the issue. I don't think it's a bug on our end.

**Comment by shenchao591** [comment]
@taurose According to your meaning, the order is still wrong.it does not work
