### ISSUE TITLE
hashHistory missing from this module

### ISSUE THREAD

**Issue by andy14312** [ReactTraining/react-router#4714]
## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by ehartford** [comment]
why is this closed?

**Comment by pshrmn** [comment]
This issue was closed because the body of the issue is the default issue template. It provides no information about the problem aside from the title, which fails to reference the version of React Router that the problem is with.

If the problem is with v4, then it is because `hashHistory` no longer exists in it. Instead you should use a [`<HashRouter>`](https://reacttraining.com/react-router/web/api/HashRouter).
