### ISSUE TITLE
Missing children filtering for <Switch/>

### ISSUE THREAD

**Issue by ThisSentenceIsFalse** [ReactTraining/react-router#4725]
Currently if a `<Switch/>` is anything like
```
<Switch>
  {
    hasPrivileges ? [
      ...routes
    ] : null
  }
  {
    // something else
    ...
  }
</Switch>
```
then no errors will be thrown if `hasPrivileges` evaluates to false. However, declarations such as:
```
<Switch>
  {
    hasPrivileges && [
      ...routes
    ]
  }
  {
    // something else
    ...
  }
</Switch>
```
will throw an ugly error. Same goes for arrays of routes (e.g. imported from another module) which contain falsey values, or for more than one conditional declaration at top-level which evaluates to a falsey value. 

Circumventing this sort of expression leads to tedious rewriting of these conditionals, or forces me to use some external utility (akin to `classnames`), or to write some wrapper, just in keeping with the simplicity of JSX . 

I think that filtering falsey children would not harm the switch logic and that many may benefit from this enhancement.

**Comment by timdorr** [comment]
You're right, since ["false, null, undefined, and true are valid children"](https://facebook.github.io/react/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored).

What is the error you're getting? I'm guessing it's something about [reading the props property of `false`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L39). It's just a matter of returning from that function when the `element` is not an actual element. I'll whip up a PR for this. Should be simple.
