### ISSUE TITLE
Please add a Link component to react-router-redux

### ISSUE THREAD

**Issue by fruchtose** [ReactTraining/react-router#4774]
Currently react-react-redux 5.0.0-alpha.3 works great, but there is one unfortunate issue with it. Since `Link` components from `react-router-dom` are not connected to the store, they issue commands directly to router history without first dispatching a `CALL_HISTORY_METHOD` action. Having a dispatching `Link` component would allow me to intercept actions with middleware and interact with the location payload.

This functionality is currently possible by writing a custom component which differs from `Link` by only a few lines, so it would be nice to have library-level support for this use case. Ideally, one would be able to import it like so:

```javascript
import { Link } from 'react-router-redux';
```

...and be able to use it like a `Link` from `react-router-dom`.

**Comment by timdorr** [comment]
I would normally say this is a good idea, but it won't cover you 100%. If someone hits a back button or you use a component that relies on react-router's Link itself, then you're going to end up missing something if you're relying on the middleware to catch things. 

Instead of intercepting those actions, you should `listen` to the history yourself. That will cover any history action, including those we don't have access to.

**Comment by fruchtose** [comment]
That's a good point. I think the issue I reported is really a proxy for my usage of browser history. It would be nice to intercept locations before are inserted into browser history, rather than receive a notification about a new location after it's already been put into history.
