### ISSUE TITLE
basename not working as expected

### ISSUE THREAD

**Issue by selbekk** [ReactTraining/react-router#4797]
## Version
4.0.0

## Test Case
https://github.com/selbekk/react-router-4-test

## Steps to reproduce
Start app. Notice that the `HomePage` component is rendered.

## Expected Behavior
It should not be rendered, since `basename` is specified on the `BrowserRouter`, and all routes have `exact={true}` specified.

## Actual Behavior
The `/` path is rendered for both `/` and `/base/`.

**Comment by selbekk** [comment]
Please let me know if I'm doing something in a way you shouldn't. The `basename` prop isn't very well documented yet.

**Comment by pshrmn** [comment]
Alright, so there is potentially a problem with the history package, but your issue specifically only exists because you are using a catch-all server.

```js
app.get('*', (req, res) => {
  // return index.html
})
```

A catch-all server is just responding with the same `index.html` file for every request. When using the basename, your server should only be serving the code the basename-specific code to requests that begin with the basename.

```js
app.get('/base/*', (req, res) => {
  // return /base specific index.html
})
```

When `history` is creating a location from the URL, it [strips the basename](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L62-L63) off of the pathname. Perhaps there should be a warning when the pathname does not begin with the basename. I'll open an issue over there where this can be discussed since that is where the issue really is.

**Comment by pshrmn** [comment]
Closing in favor or ReactTraining/history#452.

**Comment by selbekk** [comment]
Thanks a ton for answering my bug report so promptly. It's people like you who makes me want to contribute to the open source community. ❤️ 

Thanks for explaining it to me - that'll make it easier for me to fix the actual issue that triggered this repro. :)
