### ISSUE TITLE
How I add class active for path '/' ? (react-router-dom)

### ISSUE THREAD

**Issue by adrianoresende** [ReactTraining/react-router#4805]
Hello there,
I'm new react programmer, trying to learn with router.

I'm not sure how I use `IndexRoute` (react-router) with `react-router-dom` to use `active` for main page.
I do not know if it is correct to install `react-route` together with `react-route-dom`

Can someone explain what the solution is?

Code:
```
// BAD: Link Home is always active, in all pages.
<NavLink className='title' activeClassName='active' to='/'>Home</NavLink>
<NavLink className='title' activeClassName='active' to='/portfolio'>Portfolio</NavLink>
```

**Comment by pshrmn** [comment]
`<IndexRoute>` was a React Router v2/3 component. If you are using `react-router-dom`, you should only be importing from `react-router-dom` (not a strict requirement, but it keeps the imports simpler).

Your link to `/` is always active because every location begins with `/`. If you only want that link to be active when the pathname is `/`, then you should use [the `exact` property](https://reacttraining.com/react-router/web/api/NavLink/exact-bool).

```js
// If you don't set an activeClassName, it defaults to "active"
<NavLink exact to='/' className='title'>Home</NavLink>
```

**Comment by adrianoresende** [comment]
Thanks a lot for help.

**Comment by toddnagel** [comment]
yes, thanks man!

**Comment by antondachauer** [comment]
I have a nav created with <NavLink> component. The active class will be set, but the default menu item for the location `/` have all the time the `active` class. How can I fix this?
