### ISSUE TITLE
react-router-native is really slow on android

### ISSUE THREAD

**Issue by nouh** [ReactTraining/react-router#4806]
## Version
4.0.0

**Comment by timdorr** [comment]
Not enough info to go on here.

**Comment by txs** [comment]
still slow

**Comment by timdorr** [comment]
Still not enough info to go on.

**Comment by txs** [comment]
switching routes between pages in react navigation is faster. Or since it renders the animation first then change the url route later which creates a smooth experience. Currently trying out react router native stack for animation. But the rendering is a little bit delayed.
I also tested that when without animation. There's still a tiny delay for switch. Hopefully, helping out! Thanks
