### ISSUE TITLE
Transition routes and sub-routes

### ISSUE THREAD

**Issue by rodrigojcmello** [ReactTraining/react-router#4814]
I tried it in many ways, and I gave up on trying alone. Is it possible to make a transition animation between routes and then make a transition to animation sub-routes? For example, you are on a login screen, a full screen, then go to another screen, screen on which there are "tabs" (a fixed bar up or down) then you click on the tabs and will enlivening the sub-routes. Because react-router 4 is new there are no advanced examples of transitions with sub-routes.

**Comment by timdorr** [comment]
"sub-routes" are a bit of a misnomer. Route behaves the same no matter how far down you nest it. 

Take a look at [the animated transitions example](https://reacttraining.com/react-router/web/example/animated-transitions). The key bit is passing your own location to the Route so that whatever animation library you use (ReactCSSTransitionGroup, react-motion, etc) can maintain the previous instance during the transition.

**Comment by pshrmn** [comment]
There was another issue about this somewhere. Basically the issue boils down to _what_ you use as the key for the children of your `<CSSTransitionGroup>` (I think that it is similar with `react-motion`'s `<TransitionMotion>`, but I'd rather not give myself a headache reading its source).

I got into this more in my [`wrapSwitch` docs](https://github.com/pshrmn/rrc/blob/master/docs/wrapSwitch.md#why), but essentially, what you need is a way to animate `<Route>`s, not `<Switch>`es. That allows nested routes to just transition between the nested parts. It isn't a drop-in replacement for `<Switch>`, but it works well:

http://codepen.io/pshrmn/pen/aJGZLq

**Comment by rodrigojcmello** [comment]
@pshrmn I've been trying to do this for 3 weeks, you have no idea how grateful I am, thank you very much. You are amazing!
