### ISSUE TITLE
Broken react-prop link in documentation

### ISSUE THREAD

**Issue by Ethan-Arrowood** [ReactTraining/react-router#4879]
I was reviewing the documentation found [here](https://reacttraining.com/react-router/web/api/Route/render-func) and when I went to click on the route-props link it was nonexistent. 

Link: https://reacttraining.com/web/api/Route/route-props

**Note** I just realized that this is only an issue when opening the link in a new tab. By just clicking the link it seems to scroll back up to the top of the Route documentation.

**Comment by pshrmn** [comment]
There seem to be issues with the [`markdown-loader`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-website/webpack/markdown-loader.js) that it used to compile the website. When I compile the site locally, I get a bunch of URIs with undefined segments.

**Comment by mjackson** [comment]
I am unable to reproduce this locally. Can you please confirm this is still an issue for you on the latest master?

**Comment by pshrmn** [comment]
Just tested it locally as well and it works for me. This commit https://github.com/ReactTraining/react-router/commit/0ccb8fd14fab85e7456d766f4c2f407e32111890 _might_ be where it got fixed. It has been a while, so I don't actually recall exactly what the issue was (and I obviously didn't do a very good job documenting it with my above comment :man_facepalming:).

The bug still exists on the production site, but I'm not sure when that was last updated. There have been a few fixes, so it wouldn't hurt to push a new build.
