### ISSUE TITLE
NavLink has no location property

### ISSUE THREAD

**Issue by fb55** [ReactTraining/react-router#4910]
## Version
4.0.0

## Expected Behavior

All other components (except `Link`, which couldn't do anything with it) have a `location` property that is incredibly useful when using `react-router` in combination with Mobx. `NavLink` is the exception here. Is there a reason it wasn't implemented?

**Comment by pshrmn** [comment]
I'm not sure what a `<NavLink location>` would be used for. Can you give an example? A `<NavLink>` naturally uses the `location` from its nearest parent `<Route>` to determine if it is "active".

**Comment by fb55** [comment]
The `location` would be passed on to the child `Route`, to push an update inside a pure component.

We're wrapping all `react-router` components to listen to a mobx location store that triggers updates as soon as the location changes. Otherwise only router components that are direct children of the `Router` would receive updates.

**Comment by pshrmn** [comment]
Right. So you're running into the blocked updates issue, which [this guide](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md) aims to help with. You should only have to worry about passing the location to your `observer`'d components, because those are the ones that are blocking location change triggered updates.

**Comment by fb55** [comment]
Nice guide :)

Still, it is way too easy to miss one spot where state needs to be updated, especially several layers down. Having the navigation components listen for updates works remarkably well and means that the rest of the application does not need to be concerned with navigation.

I've opened #4918 that implements the necessary change.
