### ISSUE TITLE
Prop-types not found error in build

### ISSUE THREAD

**Issue by rumkin** [ReactTraining/react-router#4960]
## Version
4.1.0

## Test Case
https://codepen.io/anon/pen/qmBRgZ (look at console)

## Steps to reproduce
Append react-router-dom v4.1.0 script from unpkg:
```html
<script src="https://unpkg.com/react-router-dom@4.1.0/umd/react-router-dom.min.js"></script>
```

## Expected Behavior
No errors.

## Actual Behavior
Error thrown `Cannot find module "prop-types"`.

**Comment by YasserKaddour** [comment]
This is a little bit my fault, [react 15.6](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) deprecated `React.PropTypes` and I didn't add `prop-types` as a peer dependency in #4933, because I wrongly assumed that the production build would remove proptypes with `babel-plugin-transform-react-remove-prop-types`.

I tried to add the plugin now but I found out that it does't support `contextTypes` [yet](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/77).

I don't know what to do about it now as adding `prop-types` as peer dependency is not a solution. For now, I would suggest to stick with v.4.0 if you don't use react 15.6 or add `prop-types` as a dependency.

**Comment by Geczy** [comment]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by timdorr** [comment]
Looks like we'll need to mark `prop-types` as an external and expect people to bundle it in with the UMD build.

Maybe React should keep them in the UMD bundle?

**Comment by timdorr** [comment]
Actually, this looks like a build problem. Those errors are hard-coded. We need to push a patch to fix this stuff. Let me look into that...

**Comment by timdorr** [comment]
OK, pushed out a 4.1.1 that fixes the various PropTypes related issues.
