### ISSUE TITLE
Should the "history" dependency be changed to a peerDependency?

### ISSUE THREAD

**Issue by jahed** [ReactTraining/react-router#4964]
This is more a suggestion than a bug, though it can be considered a bug. I'm referring to an older version for `react-router` for my situation but the problem is likely to reoccur for any versions.

Recently, I've been updating my dependencies, the ones in this case being `react-router`, `react-router-redux` and `history`.

I started with `history`. Up from v2 to v4. Of course, doing so means `react-router`@2, which wants `history`@2, will use a different `history` package. In turn, this means any of the `react-router` functions/components which expect a `history`@2 but take the user-provided `history@4` instance will use it wrongly since the APIs between v2 and v4 might be different. 

AFAIK, this issue can be avoided if `history` is set up as a peerDependency such that `react-router`'s packages use the same `history` version as the user and fail otherwise to prevent conflicting versions. i.e. `react-router` should **require** the user to be using the same `history` version as itself.

Another option might be to export the `history` used by `react-router` so the user doesn't need to install their own. Though, this would just bloat the package's exports.

Any thoughts?

**Comment by jahed** [comment]
Looking further, I'm seeing a similar issue with `react-router-redux`'s reliance on the user providing `react-router` for components like `Route`. Unlike `react-router-dom` ([example](https://github.com/ReactTraining/react-router/blob/f9369d8efc50bef29c96ab7abf81068d94b5fd65/packages/react-router-dom/modules/Route.js)), it doesn't export `react-router`'s modules, which may cause silent version conflicts.

[Like `react`](https://github.com/facebook/react/blob/master/packages/react-dom/package.json), I think it makes sense to make the `core` a peerDependency too for the `dom`, `native` and `redux` packages instead of regular dependencies.

**Comment by timdorr** [comment]
Peer deps only make sense if it's expected that you will be importing them in your apps. Since 2.0, we've provided preconfigured instances of history for you to use. In order to make that work, we have to use a regular dependency. Most users don't need to interact with history ever, so making it a peer dep requires that users know about it.

Similar to our reexporting of modules from react-router in react-router-dom, we want to keep your import requirements to a minimum (you don't need both react-router and react-router-dom, for instance). So adding another required package doesn't​ achieve this goal.
