### ISSUE TITLE
Server Side Redering | RouterContext and match alternatives in react-router-dom

### ISSUE THREAD

**Issue by sadeghipour** [ReactTraining/react-router#5004]
Hi,

Any alternative for RouterContext and match in react-router-dom?

I need to do something like below in express:

app.get('*', (req, res) => {

    match(

        { routes:RoutesComponent, location: req.url },

        (err, redirectLocation, renderProps) => {

            let html;

            if (renderProps) {

                html= renderToString(<RouterContext {...renderProps}/>);

            }

            return res.render('index', { html});

        }

    );

});

**Comment by timdorr** [comment]
Please read the docs before filing an issue: https://reacttraining.com/react-router/web/guides/server-rendering

**Comment by KevinGruber** [comment]
Sry to open that issue again,

But I can't find anything describing that in the docs.
I can not access the props from the matched component.
I can only match a route which is not helping me.

It would be good if you could give an example on how to upgrade from router 2.x or 3.x to 4.x
because I can find a lot of references on the internet that people are not finding solutions for that.

The use case is loading Data into the Redux State on SSR.
and the method for that is in the component which will be called on rendering and then written into store.

BR,
Kevin Gruber

**Comment by felguerez** [comment]
I read the documentation but I still have the same question posed by @sadeghipour. Can you point me to the documentation that explains migrating from react-router 3 `match` and `RouterContext` to version 4's analog?
