### ISSUE TITLE
[website feat request] Add version somewhere noticeable

### ISSUE THREAD

**Issue by corysimmons** [ReactTraining/react-router#5025]
I'm following along with ReactForBeginners and it uses `Match` and `Miss`.

Looking at your docs at https://reacttraining.com/react-router/web/guides/quick-start it says to use `Link` instead.

I'm not sure if your docs are updated to v4 yet, but adding it to the logo area would clear it up.

![image](https://cloud.githubusercontent.com/assets/224636/25340741/a629e474-28d4-11e7-87e1-5ee027a129a6.png)

**Comment by timdorr** [comment]
Match and Miss are old APIs from the alphas. Please go off the documentation because that guide appears to be out of date. There is a free course on reacttraining.com

**Comment by corysimmons** [comment]
I understand that now. I still think adding a little version tag to the docs would be helpful for people who are confused.

Heck, flash messages, blog posts, changelog where I can cmd+f `Match` and see a message like `Match is now Route`, would be really helpful for avoiding confusion in an ecosystem where everything is constantly in flux—something it seems RR, in particular, could really benefit from.

**Comment by timdorr** [comment]
The problem is those APIs were in the alpha phase and changed in a number of ways over time, so even if they update to `Route`, it may not be the same `Route` that exists in 4.0.0. The alphas were published with the explicit message that "things are in flux and will change before the final release", so it's not on the docs to handle a short-lived API change.
