### ISSUE TITLE
withRouter example has incorrect import statement

### ISSUE THREAD

**Issue by silverHub** [ReactTraining/react-router#5034]
https://reacttraining.com/react-router/web/api/withRouter

Example looks like:
import React from 'react'
import PropTypes from 'prop-types'
**import { withRouter } from 'react-router'**

I think here we should import from **react-router-dom**, cause that's the only package appears in package.json.

**Comment by pshrmn** [comment]
The import is from `react-router` because the `withRouter.md` file used to generate that is from the `react-router` package. `withRouter` is exported by `react-router` and re-exported by both `react-router-dom` and `react-router-native`. If you look at the core API you will see the same documentation https://reacttraining.com/react-router/core/api/withRouter

**Comment by dgrcode** [comment]
In my opinion, this is still an issue. The fact that the example is copied from the 'react-router' module doesn't solve the issue.

I was reading the 'react-router-native' module API, and I found the same thing [there](https://reacttraining.com/react-router/native/api/withRouter).

This makes me think I need to add 'react-router' as a dependency in addition to 'react-router-native'. Nothing makes me think that `withRouter` is accessible from 'react-router-native'.

Three possible solutions I imagine would be (from simplest to most complex):
 1. Add in the text –not the example– a statement clarifying that `withRouter` can be imported from all core, web and native modules
 2. Avoid copying from the core module, and writing an example for each module.
 3. Instead of importing from a *.md* file, we could import from a *.js* file. That file should export a function which receives one argument, that is the module we want to build the documentation for. The function should return the same text you would get from the original *.md* file, but having the import statement modified according to the argument received.

Even the 3rd solution seems doable without a lot of trouble, and it could be easily modified to make the same type of changes in other *.md* files. That is, having two arguments, one is the module –like before–, and the other the *.md* file. Parsing the .md file looking for something like `${importStatement}` should do the trick.

**Comment by pshrmn** [comment]
PRs with improvements to the docs are welcome. :smile:

**Comment by dgrcode** [comment]
I implemented the second option. The third one was probably easier to implement by modifying the markdown-loader, but I have no experience writing webpack loaders and I was afraid of breaking more than fixing.
