### ISSUE TITLE
Don't add new location to history when navigating to the current URL

### ISSUE THREAD

**Issue by rhernandog** [ReactTraining/react-router#5039]
## Version
4.1.1

## Test Case
https://reacttraining.com/react-router/web/example/basic

## Steps to reproduce
Click on the "About" link several times, the the previous button

## Expected Behavior
If the Link's **to** param is the current history location pathname, don't push it to the history, so if the user clicks the back button, it actually goes back to the previous component, not the current one again.

## Actual Behavior
The history object keeps pushing the same url over and over, so if you click the previous button the same component is rendered again. I understand that there could be some other params on the url, so the question also would be, is there too much code and performance overhead on adding a regex check in order to see if the url location is the same and use the rest of the params for the intend purposes?

**Comment by pshrmn** [comment]
The current behavior is definitely intentional because there is a test case that verifies that a new location is created when navigating to the same path. However, I'm not sure exactly what the rationale behind that is.

I'm going to close this in favor of moving this issue to the [history](https://github.com/ReactTraining/history) repo. It would be more appropriate there because that is what actually handles location changes.
