### ISSUE TITLE
When I refresh the browser Cannot GET thiscurrent router

### ISSUE THREAD

**Issue by naihe138** [ReactTraining/react-router#5065]
router config

```
const routes = [
  { 
    path: '/',
    exact: true,
    component: Main
  },
  { 
    path: '/plan',
    component: PranList
  },
  { 
    path: '/study',
    component: StudyList,
    routes: [
      {
        path: '/study/',
        component: BCMain
      },
      {
        path: '/study/bus',
        component: Bus
      },
      {
        path: '/study/cart',
        component: Cart
      }
    ]
  },
  {
    component: NoMatch
  }
]
```
from '/' to '/plan' is normal
![image](https://cloud.githubusercontent.com/assets/12893716/25651636/c4197d5c-3016-11e7-8053-f328dd548d7e.png)

When I refresh the browser Cannot GET thiscurrent router

![image](https://cloud.githubusercontent.com/assets/12893716/25651623/b4981528-3016-11e7-98e9-8ea11181eace.png)

**Comment by mhazy** [comment]
This isn't an issue with React Router, this occurs with any client-side routing for single page applications.

The reason this occurs is because whatever is serving your application doesn't know what to do with `/plan`, it only exists on the client, so it gives you a 404.

The configuration depends on what you're serving your application with, but, the gist of it is you'll need to send all paths that aren't static files to load `index.html`.

Apache -> mod_rewrite
Nginx -> rewrite
Webpack Dev Server -> historyApiFallback
Express/Koa/Hapi/etc. -> a wildcard route to your `index.html`

**Comment by prettyGIT** [comment]
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#serving-apps-with-client-side-routing
This may help you

**Comment by pshrmn** [comment]
As @mhazy said, you need a server in order to support "pretty" URIs. This is also covered in React Router's FAQs https://github.com/ReactTraining/react-router/blob/v4.1.1/FAQ.md#why-doesnt-my-application-render-after-refreshing

**Comment by ashah023** [comment]
In my case, I was using hash routing, so the routes were broken. Fixed it with:

```javascript
import { createHashHistory } from 'history'

// create history
const history = createHashHistory({
  basname: '',
  hashType: 'slash'
}

// pass to middleware
const store = createStore(
  combineReducers(merge(reducers, { router: routerReducer })),
  applyMiddleware(thunkMiddleware, routerMiddleware(history))
)

```

**Comment by sharma02gaurav** [comment]
@prettyGIT The only solution that worked for me and the legit one. Thanks.

**Comment by ErEllison** [comment]
for any one using webpack dev server : <br>
you guys just need to add this to your config file 
```
devServer: {
    contentBase: './src',
    stats: "errors-only",
    port: 9000,
    open:true,
    historyApiFallback: true
  }
```


`historyApiFallback` will handle that ....
