### ISSUE TITLE
A general question : what'r the main advantages in v4 ?

### ISSUE THREAD

**Issue by be-next-hotdog** [ReactTraining/react-router#5105]
Hello, guys,

As title ... After several comparisons we'r still not clear enough for the main advantages in V4 comparing to v3 ? 

Thx a lot,

**Comment by timdorr** [comment]
I'd suggest watching the main video: https://reacttraining.com/react-router or taking the free course: https://reacttraining.com/online/react-router

It's not really a question anyone can answer conclusively, because it depends highly on your use case, but it's now a smaller, more React-idiomatic library. That means less coding specifically for the router, instead fighting the API differences with React. It no longer overwrites or changes React behaviors and the stuff to learn is drastically smaller and simpler, because it's just a set of components.
