### ISSUE TITLE
Documented `import {BrowserRouter as Router}` + `<Router history=...>` is a leg shooter

### ISSUE THREAD

**Issue by Aprillion** [ReactTraining/react-router#5114]
## Version
4.1.1

## Steps to reproduce
I followed the documentation:
* few weeks ago, I followed one of the 15 examples how to `import {BrowserRouter as Router}` - https://github.com/ReactTraining/react-router/search?utf8=%E2%9C%93&q=%22import+BrowserRouter%22+-%22as+Router%22
* later I found a very nice example how to use custom history object `<Router history=...` - https://reacttraining.com/react-router/web/api/Router
* but not a single warning to make sure to NOT combine the two - https://github.com/ReactTraining/react-router/search?utf8=%E2%9C%93&q=%22%3CRouter+history%3D%7B%22+NOT+context

So I shot myself in the leg, trying to debug why `history.push` is not re-rendering my routed components.

Please take a hint from various other issues:
* https://github.com/ReactTraining/react-router/issues?utf8=%E2%9C%93&q=history%20%22browserrouter%20as%20router%22 
* http://stackoverflow.com/search?q=%5Breact-router-v4%5D+history

and do not dismiss this as "users are doing it wrong." Feel free to do your own survey how many people can spot the bug in following code:

~~~jsx
// hist.js
import createHistory from 'history/createBrowserHistory'
export default createHistory()

// app.js
import hist from './hist'
import {BrowserRouter as Router} from 'react-router-dom'
ReactDOM.render(<Router history={hist}> ... </Router>) 

// async_logic.js
import hist from './hist'
xy.then((data) => hist.push(data.abc))
~~~

The, try to use `history.push()` and debug why it doesn't work...

## Expected Behavior

a) **throw an Error**, ideally of the same kind as other prop-types validation
b) make it work, accepting the `history` prop (maybe with a warning)
c) update docs to stop pretending `BrowserRouter as Router` is a good, safe code style, because it creates a sneaky technical debt to bite maintainers in their bottoms

## Actual Behavior

The `history` prop is silently ignored just as any other extra React prop `¯\_(ツ)_/¯`
Unit tests pass, eslint (3.19.0) and eslint-plugin-react (6.10.2) keep silent.

**Comment by Aprillion** [comment]
As a workaround, I plan to try out https://github.com/airbnb/prop-types `forbidExtraProps`...

**Comment by timdorr** [comment]
A PR to warn when history is passed to one of the pre-built Routers would be best. Should be pretty simple to build and test. Want to submit one?

**Comment by Aprillion** [comment]
the change is simple, but i haven't found the time to explore how to test for warnings with whatever test framwork and version this project is using :) will have a look this week(ish)

so, just history or any prop not listed in proptypes? do you need to keep supporting "extra" props?

**Comment by timdorr** [comment]
`history` seems like the obvious one to check, since it's so fundamental and seems like an easy error to make. I wouldn't worry about the others.

Testing a `warning` call is actually not that bad. You just [stub out `console.error` with a replacement function](https://github.com/BerkeleyTrue/warning/blob/master/test/package/development.js#L20-L32). Just don't forget to set it back after you're done with the test :)

**Comment by pshrmn** [comment]
React Router uses [mjackson/expect](https://github.com/mjackson/expect) for its tests. I think that the simplest approach would be to [spy on](https://github.com/mjackson/expect#spyon) `console.warn` to verify that it is called with the expected warning message.

Tim beat me to it, but basically I would add the following test to the `<BrowserRouter>`, `<HashRouter>`, and `<MemoryRouter>` tests (minus my comments).

```js
it('warns when passed a history prop', () => {
  // we don't need to use an actual history object
  const history = {}
  const node = document.createElement('div')
  expect.spyOn(console, 'error')
  ReactDOM.render((
    <BrowserRouter history={history} />
  ), node)
  expect(console.error.calls.length).toBe(1)
  // You can also test what the argument passed to console.error
  // was so that you verify that the console.error was called for the
  // expected reason
  expect.restoreSpies()
})
```

**Comment by stuartsimpson** [comment]
I don't know if this is the right place to voice this but I have been fighting getting the history.push to work with react, react-router, and history for two weeks now.  I have seen or read each of the posts listed by @Aprillion  but have not been able to piece together a working solution.  I have tried to use the context but get that the router is undefined when using the prop-types package and referencing this.context.router.history.push().  I looked into react-router-redux but in a post I found @timdorr  indicated that it was not ready for use, so I have simplified my example to: 

``` javascript
import React from 'react';
import {render} from 'react-dom';
import {
  BrowerRouter as Router,
  Link,
  Route} from 'react-router-dom';
import {createBrowserHistory as createHistory} from 'history';

class Page1Component extends React.Component {
  constructor() {
    super();
    this.state = {};
  }
  render() {
    <div><h1>Page1</h1></div>
  }
}

class Page2Component extends React.Component {
  constructor() {
    super();
    this.state = {};
  }
  render() {
    <div><h1>Page2</h1></div>
  }
}

class NavigationApp extends React.Component {
  constructor() {
    super();
    this.state = {};
  }

  clickToNav(){
    this.context.router.history.push('/Page2')
  }

  render(){
    return (
      <div>
        <Router history={history}>
          <div>
            <Link to='/'>Page1</Link>
            <Link to='/Page2'>Page2</Link>
            <div onClick={this.clickToNav.bind(this)}>history.push('/Page2') Navigation</div>

            <Route exact path='/' component={Page1Component}/>
            <Route exact path='/Page2' component={Page2Component}/>
          </div>
        </Router>
      </div>
    )
  }

  NavigationApp.contextTypes = {
    router: PropTypes.object
  }
}

```

**Comment by timdorr** [comment]
@stuartsimpson this isn't the appropriate venue for that kind of question. This is an unrelated issue and we don't do support on this bug tracker. Please use Stack Overflow instead.

**Comment by Aprillion** [comment]
@timdorr https://github.com/Aprillion/react-router/blob/master/CONTRIBUTING.md#development section says that `npm test` should watch for changes, but for me on Win 10 (using Git Shell), it only ran the tests once, not in watch mode... also while everything is green before I made any changes, there are some warning - should I be concerned that my set up is wrong?

```
ERROR: 'Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.'

ERROR: 'Warning: You should not use <Route render> and <Route children> in the same route; <Route children> will be ignored'

> echo 'Error: no test specified'
```

**Comment by pshrmn** [comment]
@Aprillion That message can probably be updated, but in order to watch for changes you will need to use Karma's `--no-single-run` option. I think that that change has something to do with `lerna`, but I am not certain.

```sh
npm test -- --no-single-run
```

All of the logged warnings that show up are annoying, but I don't think that they're actually errors.

The `no test specified` errors are just lerna letting us know that those packages do not contain a test command.

The one about `<Route render>` and `<Route children>` shows up in a fix for Preact because Preact automatically passes the `children` prop as an empty array if none is provided. That was apparently causing issues, so that test is simulating an empty `children` array prop. Yes, the `warning` could be smarter, but it is such a small thing that I personally am not worried about it.

The `setState` errors appear to happen the `history` object created by a `<HashRouter>` because we are testing in a browser but have not manually changed the location (by setting `window.location.hash` to reflect what the value should be). Again, this is more of an annoyance and not an actual reflection of something being wrong with the actual code.

**Comment by Aprillion** [comment]
@timdorr @pshrmn do I need to ask for the PR code review somehow of someone is checking new PRs once in a while please?

**Comment by pshrmn** [comment]
All PRs will be handled eventually, but it can take some time. I'll add some comments, but I don't touch the actual merging.

**Comment by timdorr** [comment]
We generally have a policy of needing at least two collaborators to agree to a change for it to be merged in. Michael and Ryan can veto, of course. I'm not sure of their current status, as both have been inactive on GitHub lately. But I know they don't like to lose track of things going on here, so I tend to defer the API behavior changes (breaking or otherwise) to them, even if we have multiple +1's on a PR.
