### ISSUE TITLE
Potentially misleading documentation for HashRouter

### ISSUE THREAD

**Issue by mymainmanbrown** [ReactTraining/react-router#5117]
I am developing a web application whose only interactions between client and server are via the server's api - nginx serves the client files, and all requests other than '/' are made to an api that is a completely independent process, used to serve only json - no views or html files (kind of like a microservice, but more like a macroservice).

I initially avoided the HashRouter because it said "legacy" in it, however I see no way to have the server be completely ignorant of client urls and not use the HashRouter.  I do not consider this to be a "legacy" development practice, so I think the documentation should be update to re-word the HashRouter verbage, or at least put a note or something in the "Examples" documentation, perhaps in the "No Match (404)" section, so that the next person who decides to have his client and server code split up into separate repositories has some guidance when encountering this problem.

**Comment by timdorr** [comment]
You should be looking into using pushState (aka Browser) history. It's not a difficult configuration to support on your server. The hash history is legacy because it was developed before we had the history APIs we have today. It has a number of compromises under the hood, so we intentionally discourage it's use.
