### ISSUE TITLE
Ability to use <Redirect /> to perform history.go()

### ISSUE THREAD

**Issue by techniq** [ReactTraining/react-router#5140]
It would be really nice to be able to use `<Redirect />` to go back in the history stack (instead of just pushing another location onto the stack). 

A few use cases:
- Navigating back to the page you are at after saving on an edit route.  For example, the edit page could have been routed to from the list of items page, a details page, other even somewhere else (shown as referential data with an edit link).
- Returning the user to the page they were attempting to access before being redirected to a login page.

Currently (for the login case) I pass the current location as a route state param then use it to redirect the user back after logging in:

```js
<Redirect to={location.state && location.state.from || '/'} />
```

The login case isn't bad to use state since I encapsulate this within a `<PrivateRoute />` component, but having to pass the `from` route state for a good majority of my `<Link />`s is rather inconvenient, and I figure it's best to not always push new history if it's not needed.

What I propose is the ability to do something like:
```js
<Redirect go={-1} /> // history.go(-1)
```
and possibly even
```js
<Redirect back />    // history.goBack()
<Redirect forward /> // history.goForward()
```

**Comment by pshrmn** [comment]
For logging in, I don't think that you would want to use `history.go` because it preserves the entries. For me, the login flow would be:

1. The user visits a page that requires authentication.
2. App redirects (using replace) to the `/login` page, storing the current location either in `location.state` or encoded in `location.search` (e.g. `/login?next=/auth-page`).
3. The user successfully logs in.
4. The application replaces the `/login` location with the original location (or pushes the original location, but replace is probably preferable so that the `/login` location is wiped from the entries).

If you are using `history.go`, `/login` would still exist in the entries array and the user could click the browser's <kbd>forward</kbd> button and be back at the `/login` page. I don't think that this would be desirable behavior.

---

For redirecting after a form is saved (or cancelled), I think that it would be preferable to do this within the event handler.

```js
class Form extends React.Component {
  cancelHandler = (event) {
    this.props.history.go(-1)
  }

  savehandler = (event) {
    // save the form, then...
    this.props.history.go(-1)
  }

  render() {
    return (
      <form>
        {/* ... */}
        <button type='submit' onClick={this.saveHandler}>Save</button>
        <button type='button' onClick={this.cancelHandler}>Cancel</button>
      </form>
    );
  }
}
```

I could see there being more of an argument for `<Redirect go>` in this situation, but to me it feels like you have to do more work to setup declarative routing then it would be to just do it imperatively.

```js
class Form extends React.Component {
  state = { finished: false }

  cancelHandler = (event) {
    this.setState({ finished: true })
  }

  savehandler = (event) {
    // save the form, then...
    this.setState({ finished: true })
  }

  render() {
    return this.state.finished
      ? <Redirect go={-1} />
      : <form>
          {/* ... */}
          <button type='submit' onClick={this.saveHandler}>Save</button>
          <button type='button' onClick={this.cancelHandler}>Cancel</button>
        </form>
    );
  }
}
```

**Comment by mjackson** [comment]
FWIW I had a `<Pop>` component that I was [experimenting with in `react-history`](https://github.com/mjackson/react-history#navigation) that people didn't seem to like very much for some reason.

I agree that `<Redirect>` *feels* like it should be able to `go`. It's our only component that we can use for navigation, but it's not quite complete because it can only `push` or `replace`.

**Comment by techniq** [comment]
@pshrmn For my data access, I'm using [react-odata](https://github.com/techniq/react-odata) (which uses [react-fetch-component](https://github.com/techniq/react-fetch-component)) which allows me to declaratively request data and handle the request's lifecycle (disable submit button while inflight and change text of button, and if the response is successful, I was hoping to render the `<Redirect />`)

Here is some example code from an edit form.
 
```js

render() {
  const { match: { params }, history } = this.props;
  
  // form omitted here...

  <FooData
    query={{ key: params.id }}
    options={() => ({
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(this.state.foo)
    })}
    manual
  >
    {({ loading, data, error, fetch }) => {
      if (data) {
        // TODO: Redirect to last page (history.goBack?)
        return <Redirect to={`/foo/${params.id}`} />
      } else {
        return (
          <div>
            <CardActions>
              <RaisedButton
                label={loading ? 'Saving...' : 'Save'}
                primary={true}
                onTouchTap={() => fetch()}
                disabled={loading}
              />
              <RaisedButton
                label="Cancel"
                onTouchTap={() => history.goBack()}
              />
            </CardActions>
            {error && <Error error={error} />}
          </div>
        );
      }
    }}
  </FooData>
}
```

Regarding the login use case, that is very good to know and something I should be handling better.
