### ISSUE TITLE
404 page error? help :P

### ISSUE THREAD

**Issue by luandr** [ReactTraining/react-router#5156]
I'm a newbie. Hey, i have a situation. My 404 page doesn't work. My url is: `http://localhost:3000/` => show {App} my url is `http://localhost:3000/lul` => show `Cannot GET /lul`
My code
```
import React from 'react'
import { render } from 'react-dom'
import './stylesheets/ui.scss'
import { App } from './components/App'
import { Whoops404 } from './components/Whoops404.'
import { BrowserRouter as Router, Route, hashHistory, Switch } from 'react-router-dom'

window.React = React

render((
	<Router history={hashHistory}>
    <Switch>
        <Route path="/" component={App} />
        <Route path="*" component={Whoops404}/ >
    </Switch>
    </Router>),
document.getElementById('react-container')
)
```
My english is out of practice xD
Thanks.

**Comment by pshrmn** [comment]
The issues section is for bugs, not asking questions. For questions, you should use StackOverflow or Reactiflux. That said, there are a number of things that I can quickly point out with the above code:

1. `react-router-dom` does not export a `hashHistory`.
2. If you are using `<BrowserRouter>`, a history will be created for you, you do not (and cannot) provide your own.
3. The first component in your `<Switch>` has the path `/`, which will match **all** pathnames unless you use the `exact` prop (`<Route exact path='/' component={App} />`).
4. The error that you are getting is not from React Router. It is because you are requesting a resource from the server that does not exist. You need to make sure that you have a server running that can respond to dynamic requests and return the appropriate response.

**Comment by luandr** [comment]
@pshrmn i tried `<Route component={NotFound} />`, remove switch, ect... I tried everything =\, can you redirect me to make it right? Thanks! <3
