### ISSUE TITLE
react-router-* should provide as is absolutely all not changed inherited functions

### ISSUE THREAD

**Issue by a-x-** [ReactTraining/react-router#5164]
// Excuse my beginner's English

e.g. `react-router-dom` does not re-exports `browserHistory` now.

also, instead of creating wrappers for every `react-router` function it'll be the better keep only index.js with re-exports (better for changed method readability. e.g. I want to look sources of `react-router-dom` for added/changed methods, I have to open all the modules in the [react-router-dom/modules/index.js](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom/modules)
 now ).

e.g. wrapper to delete:
[MemoryRouter.js](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/MemoryRouter.js)
```js
export { MemoryRouter as default } from 'react-router'
```

e.g. how to rewrite re-exports:
[react-router-dom/modules/index.js](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/index.js)
```js
// ...
export MemoryRouter from '../react-router/MemoryRouter'
// ...
```

thank you

**Comment by pshrmn** [comment]
1. `browserHistory` is not exported because it no longer exists. The `<BrowserRouter>` component creates a `history` object for you. If you need a custom `history` object, you have to create it yourself and pass it to a `<Router>`.

2. The separate files have something to do with enabling tree shaking (see #4432 and the issue it links to). I'm not familiar enough with tree shaking to add any more information on why it was necessary.
