### ISSUE TITLE
How efficient monitoring global routing change with Router4?

### ISSUE THREAD

**Issue by minooo** [ReactTraining/react-router#5178]
In Router3，we can monitor routing change by add a middleware，such as:
```javascript
export default store => next => action =>{
    if(action.type=='@@router/LOCATION_CHANGE'){
        // do something
    }
    return next(action)
}
```
But how do this in router4 ??

## Version
4.0.0

**Comment by timdorr** [comment]
I think you're confusing this with react-router-redux. React Route 3.x doesn't have any sort of middleware built-in.

However, just provide your own history instance and `listen` to it for changes. Works great without getting Redux involved.

**Comment by xusai2014** [comment]
@timdorr Hi timdorr, I use the history to listen the router changes. but it only works when I click the go back  on the browser. 

my code is as below(the listener doesn't work)
```
this.props.history.push(`/lender/allloan/`)
```

**Comment by CristianoYL** [comment]
Hi there,
I recently started using **react-router-dom** and ran into a similar question. I was hoping to add a global listener for my router (a BrowserRouter):

```
<BrowserRouter>
      <Switch>
        <Route path="/search/:query" component={Result} />
        <Route path="/about" component={About} />
        <Route exact path="/" component={Home} />
      </Switch>
</BrowserRouter>
```

I tried to add the listener from within my Home component like so:

```
componentDidMount() {
    const { history } = this.props;
    history.listen((location) => {
       # do something
    });
}
```

This approach works but not quite well. Since whenever the user navigates to the home page (route `/`), it adds another duplicate listener to history. I'm wondering if there's any way to check if there's an existing listener?

I understand that I might be looking in the wrong direction. My first attempt was to create a history instance with a listener and provide it to the router. But **BrowserRouter** ignores the history prop, and suggests that I shall use **Router** instead. But in the **ReactTraining** tutorial, it suggests that I shall usually use one of the high-level routers (such as **BrowserRouter**) as opposed to the **Router**. 

Any suggestions would be appreciated. Thanks!
