### ISSUE TITLE
Prevent passing of children as props (react/no-children-prop)

### ISSUE THREAD

**Issue by smalike** [ReactTraining/react-router#5188]
https://reacttraining.com/react-router/web/example/custom-link
```
const OldSchoolMenuLink = ({ label, to, activeOnlyWhenExact }) => (
  <Route path={to} exact={activeOnlyWhenExact} children={({ match }) => (
    <div className={match ? 'active' : ''}>
      {match ? '> ' : ''}<Link to={to}>{label}</Link>
    </div>
  )}/>
)
```
Children should always be actual children, not passed in as a prop.

**Comment by pshrmn** [comment]
You can see how `React.createElement` sets up the `children` prop [here](https://github.com/facebook/react/blob/15-stable/src/isomorphic/classic/element/ReactElement.js#L213-L229). The only real risk from passing `children` as a prop is if you pass children both as a prop and nested. In that case, the `children` prop would be overwritten by the nested `children`.

```js
// don't do these
<Route children={fn1}>{fn2}</Route>
React.createElement(Route, { children: fn1 }, fn2);
```
I personally prefer to use nested `children` in JSX because I think that it looks nicer, but if you know what you're doing, it shouldn't matter.

**Comment by timdorr** [comment]
Also, this is really up to the user. If you want to enforce that in your eslint config, go right ahead.
