### ISSUE TITLE
How to use react-router with Transfer-Encoding: chunked?

### ISSUE THREAD

**Issue by loheswaran** [ReactTraining/react-router#5212]
Could you please help me to implement react-router with **Transfer-Encoding: chunked**?  Or please share any document to refer.

## Version
4.0.0

## Test Case
https://codepen.io/ReactJSTraining/pen/jyYjeW

**Comment by timdorr** [comment]
This isn't something that the router has anything to do with.

**Comment by loheswaran** [comment]
@timdorr  : As per the document, app should be wrapped inside the static route at server side and BrowserRoute should be used at the client side.  But in my case, I am not rendering the entire app at a time instead I will render the app components one by one and stream the content to the browser.  Could you please let me know how to use the static route in this case?

**Comment by timdorr** [comment]
No, because that doesn't have anything to do with the router. You need some sort of streaming support in React's rendering. 

Honestly, it sounds like you're prematurely optimizing your application. Try to make it work with just normal requests. If you need anything to stream, just hook up a WebSocket in the client.

**Comment by loheswaran** [comment]
I think you didn't get my question.  I am not asking about how to do streaming in react(I do have a react application with SSR and streaming using express js).  My question is all about how to use react-router when I do SSR and streaming of react components.
