### ISSUE TITLE
doc: add a note about not preserving component state

### ISSUE THREAD

**Issue by nahuel** [ReactTraining/react-router#5222]
When you switch between routes, React Router doesn't preserve the component state. This is an unexpected behaviour from the one you are accustomed to in the React reconciliation process. It will be nice if a note was added in the documentation warning the usage of componentes that depends on preserving his state.

**Comment by Johnius** [comment]
Am I right that `App`s state will be reset when hit any of child routes?

**Comment by timdorr** [comment]
@Johnius No, if the component is still in the tree after a navigation, it will re-use the same instance. 

However, as to the original question, I'm not sure I see a need for noting this. If you unmount a component by navigating away from it, of course React is going to destroy its local state. This is entirely expected behavior and would be the same if you did something like `page == 'Home' ? <Home> : <Page>` or something to that effect. When the components in the tree disappear, so does their state.
