### ISSUE TITLE
Animated Transitions can't use HashRouter

### ISSUE THREAD

**Issue by gy190** [ReactTraining/react-router#5249]
When I use HashRouter instead of BrowserRouter in official case.The animation transition didn't work.
[official case](https://reacttraining.cn/web/example/animated-transitions)

**Comment by pshrmn** [comment]
The issue is that `<HashRouter>`does not add the `key` property to locations*. That means that when you try to run the example as given (using `location.key`), the `key` is always `undefined`, which means that the `<CSSTransitionGroup>` cannot tell what components are entering/leaving. If you switched this:
```js
key={location.key}
```
to this
```js
key={location.pathname}
```
it should work. 

* The reason for this is that hash history doesn't use `history.(push|replace)State` to switch the location (it just uses `window.location.replace`), so there is no way to store a `key` for a location.
