### ISSUE TITLE
RN - <Link> doesn't update location.pathname

### ISSUE THREAD

**Issue by joachimroeleveld** [ReactTraining/react-router#5251]
## Version
react-router-native 4.1.1
React 15.4.1
React Native 0.42.3
Redux 3.5.2
React Redux 5.0.4

## Test Case
```javascript
class Content extends React.Component {
  componentDidMount() {
    this.props.history.listen((location, action) => {
      console.log(location, action);
      console.log(this.props.location); 
    });

    this.props.history.push('/foo');
  }

  render() {
    let Foo = <Text>{'Foo'}</Text>;
    let Bar = <Text>{'Bar'}</Text>;

    return (
      <NativeRouter>
        <View>
          <Link to="/foo"><Text>{'Foo'}</Text></Link>
          <Link to="/bar"><Text>{'Bar'}</Text></Link>

          <Switch>
            <Route path="/foo" component={Foo} />
            <Route path="/bar" component={Bar} />
          </Switch>
        </View>
      </NativeRouter>
    );
  }
}

export default withRouter(connect()(Content))


// ------------------------------------------------------

class App extends React.Component {
  // ... init store

  render() {
      <Provider store={this.store}>
        <Content/>
      </Provider>
  }
}
```

## Steps to reproduce
Click a link or call `this.props.history.push('/foo')`

## Expected Behavior
Replacement of `this.props.location.pathname` and an updated component

## Actual Behavior
`this.props.location.pathname` is not updated, and the component is not rerendered either. `this.props.history` is updated as can be seen in `this.props.history.listen`. Setting `this.props.location.pathname` manually does result in the expected behavior.

**Comment by pshrmn** [comment]
Wrapping your `<Content>` component is `withRouter` doesn't make any sense because it is not inside of a `<Router>`. You're also attempting to add a listener to `this.props.history` in your `<Content>`, but once again, because it is not inside of a `<Router>`, it does not have access to these values. What you probably want to do is to move your `<NativeRouter>` outside of the `<Content>`.

```js
<Provider store={this.store}>
  <NativeRouter>
    <Content />
  </NativeRouter>
</Provider>
```

**Comment by joachimroeleveld** [comment]
That is indeed a problem with the previous code, but my actual code doesn't have that problem. I updated the code in the example but the problem still exist: `props.location` is not updated and props are not rerendered. Please also note that events _do come in_ in the `this.props.history.listen` callback.

**Comment by joachimroeleveld** [comment]
I failed to get it working after hours of looking into my code, documentation and examples. Not expecting to get it to work I now work around this issue by doing this in `Content`'s `componentWillMount()`:

```javascript
this.props.history.listen(location => {
  if (location.pathname !== this.props.location.pathname) {
    this.props.location.pathname = location.pathname;
    this.forceUpdate();
  }
});
```

**Comment by pshrmn** [comment]
@joachimroeleveld Have you tried adding a `componentWillReceiveProps` lifecycle method to your `<Content>` component? There shouldn't be any navigation blocks happening.

**Comment by joachimroeleveld** [comment]
@pshrmn, yes, but it is not triggered through route changes. It is however triggered when a Redux prop (mapStateToProps) changes.

**Comment by JounQin** [comment]
+1 for `componentWillReceiveProps` not fired on change location, unlike `forceUpdate`, I use `setTimeout` in `history listen` callback for now, is there a better way?

**Comment by FredyC** [comment]
Well, isn't that like a core functionality of the router to change routes? 😆  I just encountered the same problem. I tried debugging and it seems that `NativeRouter` is not even listening to any changes. There is a single listener in `Router` and strangely enough, its `computeMatch` method always sets `pathname` to `/`

https://github.com/ReactTraining/react-router/blob/c7993ce58ee1e4c1176b576a46bcc5561ac751ad/packages/react-router/modules/Router.js#L60

I am failing to understand how is this supposed to work since `NativeRouter` is just a `MemoryRouter` and there are no listeners whatsoever. 

@timdorr  Since you have closed this issue, do you have some idea what might be wrong here?

**Comment by ohpyupi** [comment]
Do we still need to update location manually? Also, I see that match is not updated.
