### ISSUE TITLE
Preventing transitions inflexible in 4.x

### ISSUE THREAD

**Issue by bwhitty** [ReactTraining/react-router#5254]
This is a continuation of https://github.com/ReactTraining/react-router/issues/4635 but in a new issue as that particular issue appears to be at a dead end.

Transition prevention seems to have a regression of functionality from version 2/3. The solutions put forward in the linked ticket work for simple use cases, but as has been said already, they are not sufficient for advanced cases such saving dynamic data prior to allow transition to continue.

For example, you can have access to a redux store with
```js
export function makeHistoryUserConfirmation(store) {
  return function getUserConfirmation(message, callback) {
    // render some custom component into a completely different dom tree; not great.
    // When I'm at /user/profile/edit
    // I want to save/discard changes to that data prior to callback()

    // When I'm at /asset/edit
    // I want to save/discard changes to that data prior to callback()

    // Since this global function has no React application for rendering context,
    // all of the logic must be implemented imperatively inside of here

    if (store.isEditingProfileData) // ?? imperative

    if (store.iseEditingAssetData) // ?? imperative 
  }
}

render(
  <ReduxProvider store={store}>
      <Router 
        basename={i18n.basename} 
        getUserConfirmation={makeHistoryUserConfirmation(store)}
      >
        <App />
      </Router>
  </ReduxProvider>,
  document.getElementById('app')
);
```
but since you're now out of the context of your `<App />` component, you cannot declaratively render different components which are hooked into the store (which in this theory would handle saving of different data based on where the user is in the app). You would have to move all of the logic into the the one component you're rendering from within `getUserConfirmation` and do all of the logic *imperatively*. The rest of react-router 4's API is very declarative, but this is glaringly not so.

I don't actually have an API in mind right now (though I'm trying to come up with one), but I'd like to have this issue open to track ideas.

**Comment by timdorr** [comment]
I don't mean this to be dismissive of the issue, but this really needs to live in `history` instead of here. This is because there is no longer a central route configuration ("static routing" as Ryan has coined it) and therefore no single transition to block. The singular action really lies not in the *route* transition, but the *location* transition. That's what you're attempting to block: sending your browser to another location. And history is now the sole arbiter of all location-related activities, so it's the best place to implement this kind of functionality. 

`history` currently [does implement such an API](https://github.com/ReactTraining/history#blocking-transitions) and [we use it via `<Prompt>`](https://reacttraining.com/react-router/core/api/Prompt). So if that API/implementation isn't sufficient (it certainly leaves a lot to be desired), we should open up issues over there to improve it.

Also, I understand this relies on imperative escape hatches. But it's unlikely we'll land on a declarative approach to this, since we are no longer hooking into the creation of React Elements and other weirdness. It's harder for us to build some APIs this way, but we think the overall API surface is better for it.

**Comment by bwhitty** [comment]
I actually think https://github.com/ReactTraining/history/pull/484 will allow this to be entirely solved in user-land. Appreciate the response and I'll reopen if that's not the case or if it turns out some decent API could actually land in the router. Thanks.
