### ISSUE TITLE
Update <Redirect /> docs to reflect use of `exact` and `strict` in a <Switch /> 

### ISSUE THREAD

**Issue by JamesQuigley93** [ReactTraining/react-router#5258]
According to the discussion on   #4791 , which was later merged into #4826 , it is possible to use the `exact` and `strict` props on a <Redirect /> as long as it is rendered inside of a <Switch />.
Hence:
`
<Switch>
     <Redirect from='/' to ='/app' strict />
</Swtich>
`
will work while:
`
<Redirect from='/' to ='/app' strict />
`
Will not.
This behavior is (in my opinion) not intuitive, and also not documented in either the <Switch /> or the <Redirect /> sections of the docs. I think because its behavior on the <Redirect /> component it should be described in its docs.

If people agree I'll make a pull request with proposed markdown (this is my first github issue still not exactly sure how the process works)

**Comment by pshrmn** [comment]
This functionality is documented under the `<Switch>` https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Switch.md#children-node. A `<Switch>` essentially treats all of its child elements as `<Route>`s, which is why you can use `exact`/`strict` on the `<Redirect>`.

The reason that it is not in the `<Redirect>` documentation is that they aren't actually props of the `<Redirect>`. I actually think that it would make sense to remove the `from` prop from the `<Redirect>` documentation and add a link to the `<Switch>` `children` props section.

**Comment by JamesQuigley93** [comment]
I see. So my first comment that its not in either section of the docs is incorrect. My understanding of the situation now is that a `<Switch>` must convert all of its children into `<Route>` components which is what allows the `<Redirect>` component to use props that are normally only on `<Route>` such as `exact` and `strict`.  

My problem with this is that it goes against my understanding of a component. The `<Redirect>` component itself can take different props depending on where its rendered and what parent component it has. This is a behavior that is unique to  the `<Redirect>` component itself. Which is why I think there should be some form of mention of it in the `<Redirect>` section.  

Overall I think that any component's props should be the same no matter where it gets rendered. In a perfect world that would mean that the vanilla `<Redirect>` component would get access to `strict` and `exact` without needing to be in a `Switch` but I also understand that this is probably more work than its worth.

**Comment by pshrmn** [comment]
I agree that the setup of `<Switch>` isn't particularly satisfying. It is similar to how older versions of React Router worked where `<Route>` components were just glorified objects and not actual components.

I have a package of React Router compatible components that I created called `rrc`; one of these components is the [`<ConfigSwitch>`](https://github.com/pshrmn/rrc/blob/master/docs/ConfigSwitch.md), which I feel better expresses how the switch works.
```js
<Switch>
  <Route exact path='/' component={Home} />
  <Route exact path='/about' component={About} />
</Switch>
// vs
<ConfigSwitch
  routes={[
    { path: '/', exact: true, component: Home },
    { path: '/about', exact: true, component: About }
  ]}
/>
```
It won't work as a fix for this because it only supports actual routes, but I think that it makes more sense.

**Comment by JamesQuigley93** [comment]
The question now is, do you think its worth documenting the use of `exact` and `strict` under both `Switch` and `Redirect`? It would make the docs somewhat redundant but it would also make them easier to read and to follow for people new to the library.
