### ISSUE TITLE
LocationChange without rendering Component

### ISSUE THREAD

**Issue by viennv1709** [ReactTraining/react-router#5281]
I did the instructions from `react-router` page. But I can't figure out why when the location change. My app doesn't render `Component`
```javascript
export default withRouter(connect(mapStateToProps, mapDispatchToProps)(CategoryPage));
```

```javascript
const Root = ({store, history}) => (
    <Provider store={store}>
        <div>
            <Router history={history}>
                <App>
                    <Route exact path="/" render={() => (
                        <Redirect to="/categories"/>
                    )}/>
                    <Route path="/categories" component={CategoryPage}/>
                </App>
            </Router>
            <DevTools />
        </div>
    </Provider>
);
```

**Comment by hannadrehman** [comment]
i am also facing the same issue

**Comment by timdorr** [comment]
Is App connected as well? Any connected component will block updates of all components underneath it. withRouter() is the fix here.

**Comment by viennv1709** [comment]
App is also connected with withRouter as well.

**Comment by LKay** [comment]
Would there be any more elegant way to handle this bug than unnecessarily decorating connected components?

**Comment by pshrmn** [comment]
@LKay This guide covers that. https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md#the-solution `withRouter` is the easy way to prevent blocked updates, so that usually gets recommended, but I prefer just passing the `location` prop to any components that block updates. It could even just be part of the `location`, just something that changes whenever you render a new location.
