### ISSUE TITLE
Feature request -- Working together with React Transition Group (low level API)

### ISSUE THREAD

**Issue by Bram-Zijp** [ReactTraining/react-router#5293]
At it's current state, React Router v4 will not work together with React Transition Group low level API for animated transitions on page navigation. I fiddled around, asked the question on multiple places without any answers. The only workaround I found was writing a custom switch which requires allot more boilerplate. Therefor I would like to request implemented functionality and documentation so that other people their JS fatigue remains leveled avoiding lots of fiddling.

[Codepen](https://codepen.io/anon/pen/owXzgo)
[Stackoverflow URL](https://stackoverflow.com/questions/44388542/react-router-v4-react-transition-group-js-animations-flavor-not-firing-class)

timdorr: Just follow these guidelines: [#4351 (comment)](https://github.com/ReactTraining/react-router/issues/4351#issuecomment-281198187)

@timdorr 
[Doesn't seem to work](https://codepen.io/anon/pen/GEEpGO) following those guidelines? 
This also [doesn't seem to work](https://codepen.io/anon/pen/eRRJON)

Everytime I report this missing feature/bug it gets closed by timdorr while he points at a solution that does not work (only for the CSS transition high level api) I provided multiple pens that show these features do not work however no one responds after the issue is closed.

Please provide a working example, prefferably on your nice looking [documentation website ](https://reacttraining.com/react-router/)aswell. This would benefit JS animators greatly.

**Comment by timdorr** [comment]
Well, thanks for throwing me under the bus. Really appreciate it... >_>

The issue here is that the lifecycle hooks live on the component, but the `Switch` is what is transitioning in and out of the DOM. `TransitionGroup` expects to act on that component, not the eventual route component. There is no way around this, as it's just how React and `TransitionGroup` work. 

What you can do is wrap `Switch` with a component that does have transition hook functions on it. You could then proxy those through to the component returned by `Switch`. Probably your best bet is just keeping it at the level of that top wrapping component, though.

**Comment by Bram-Zijp** [comment]
@timdorr sorry for throwing you under the bus and thanks for explaining. Thats allot of overhead for animating with react router. One would be better off sticking to the version 3 for code clarity with js animation in mind.
