### ISSUE TITLE
Feature request: Make withRouter easier to use

### ISSUE THREAD

**Issue by danielbastos11** [ReactTraining/react-router#5369]
Hey!
While `withRouter` is a great solution for the issue it solves, I think it's quite a hassle to import it everytime I want to use a Redux-connected component in my `Route`s. 

So, I was thinking: would it be possible to automatically use `withRouter` inside the `Route` component, instead of forcing people to do it manually? Maybe this behavior could be triggered by a prop.

So, if you have a code that looks like this:

```js
  import { withRouter } from 'react-router-dom'
  ...

  export default withRouter(connect(Foo))
```

You could drop `withRouter` and use this `Route` instead:

```js
  <Route path="/foo" component={Foo} withRouter />
```

I think this would be more readable, more reusable, more elegant etc.
I even think I could send a PR to do that, but I'd like to hear from you guys first.

Thanks in advance

EDIT: Text was a little bit confusing, I think. Sorry.

**Comment by pshrmn** [comment]
In your above example, you do not need the `withRouter`. The reason to use `withRouter` is to pass context variables to the component as props. This is useful with Redux's `connect` because when the props change (which happens when the location changes), then the `shouldComponentUpdate` of the component returned by `connect` will return `true`, allowing it and its children to re-render (solving the blocked updates issue).

If you look at the [`withRouter` source code](https://github.com/ReactTraining/react-router/blob/v4.1.1/packages/react-router/modules/withRouter.js), you will see that `withRouter(Foo)` is literally the same as `<Route component={Foo} />`. That means that if you pass a `withRouter` wrapped component as the `component` prop of a `<Route>`, you are effectively rendering a `<Route>` inside of a `<Route>`

```js
// the component tree when passing a withRouter wrapped
// component to a <Route>
<Route path='/foo'>
  <Route>
    <connect>
      <Foo />
    </connect>
  </Route>
</Route>
```

**Comment by danielbastos11** [comment]
Yeah, I was making a silly mistake on my app.
Sorry about that!
