### ISSUE TITLE
Link not working with mdc-web

### ISSUE THREAD

**Issue by smandava** [ReactTraining/react-router#5370]
The single page app behavior is not working while using the google's mdc-web persistent drawer with the BrowserRouter.

demo of persistent drawer: 

http://material-components-web.appspot.com/drawer/persistent-drawer.html

code: 

https://raw.githubusercontent.com/material-components/material-components-web/master/demos/drawer/persistent-drawer.html

 

## Version
4.1.1

## Test Case
https://codesandbox.io/s/Wn02Dn6Vx

## Steps to reproduce

Click on any of the navigation links  ( Home, Products or About )

## Expected Behavior
Single Page Application behavior - Home, Products or About component should be rendered with out any network calls to the server.

## Actual Behavior
Whole page is loaded every time Home, products or About clicked.

## Additional notes

Hash Rouer:
https://codesandbox.io/s/5ywlAY6NA

or a mdc-permanent drawer

https://codesandbox.io/s/73wxMZgx1 

have expected behavior.

**Comment by pshrmn** [comment]
Not a React Router issue. If you added a `debugger;` line to the `<Link>`'s cilck handler, you would see that it never gets called. It appears that MDC is attaching click handlers to your links and those are causing that navigation to happen.

The hash router only appears to work. If you look at the `history`, you will see that the `history.action` after clicking a link is `POP`, when it should be `PUSH`. The hash history attaches an `onhashchange` event to the window, which is why it can react to the location changes, but not correctly.

You'll have to see if you can disabled MDC's click handler because React Router links won't work if they can't use their own click handler.
