### ISSUE TITLE
Dynamic basename does not update links when it is changed

### ISSUE THREAD

**Issue by hashwin** [ReactTraining/react-router#5465]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/r0ypl1l29o

## Steps to reproduce
In the codesandbox link you can try clicking on some links and see that the url has '/1' properly prepended. But, if you click on the button that changes the state containing the '1', the basename for those links remains the same despite a new basename being supplied to the Router.

## Expected Behavior
Links should change to reflect the new basename.

## Actual Behavior
Basename that is changed from the state (or redux) does not propagate to links.

**Comment by pshrmn** [comment]
Dynamic basenames aren't a thing. The [`<BrowserRouter>`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js) creates a history object when it is initially rendered and then always re-uses that object.

If you want to change basenames (and I don't actually know why you would want to), you would need to use the plain `<Router>` and create a new `history` object yourself. In theory, that should work, but I haven't actually tested it and I'm not sure of the performance implications it brings.

**Comment by hashwin** [comment]
My use case deals with contexts within the app. Let's say you have 2 different contexts, with IDs '1' and '2'. The entire app should function based on the current context and switch if need be. A url can be as follows:
```www.example.com/<context-id>/settings```
So with context 1 it would be
```www.example.com/1/settings``` or ```www.example.com/1/posts```
So you should be able to switch between 1 and 2 there.
Now since the entire app requires a context, I thought putting it in as a basename would save me from having to put in the current context manually in every URL. Is there another way of achieving something like this?

**Comment by pshrmn** [comment]
I know that you already have the value in state, but I think that you would want that value captured as a `param`.

Basically, you would start with a base route: `<Route path='/:contextID' component={App} />`. Then, all child routes would look something like: ``<Route path={`${match.path}/rest/of/the/path`} ... />``. It might not be the prettiest, but that probably _is_ the best approach. Another advantage of this is that instead of having to pass state down through components, your routes would have the context id available to them through `match.params`.

Eventually (hopefully soon! #4539) there should be support for partial routes, and then you won't have to include the `match.path` in your paths.

**Comment by rdgomt** [comment]
Hello. I am wondering what is the best approach to store map coordinates in the url. Like this app: app.onesoil.ai. I found that changing history basename gives a warning in console.
