### ISSUE TITLE
ConnectedStaticRoute feature?

### ISSUE THREAD

**Issue by adam-26** [ReactTraining/react-router#5475]
Hello,

This applies to the react-router-redux package.

Supporting redux usage on both client and server is currently possible, but the `router` state is not included in the redux router store from the server -> client.

I believe adding a `<ConnectedStaticRouter />` to the react-router-redux package should make this possible, it's only real task is to assign the request url to the redux store in the correct format.

Using the `<ConnectedRouter />` on the server does not provide access to the same context that the `<StaticRouter />` provides, which is required for rendering on the server.

I initially identified this need in adam-26/react-router-dispatcher#12:
 * The `<ConnectedStaticRouter />` only needs to assign the request url to the redux store
 * Make the methods in `<StaticRouter />` for parsing the string url accessible
 * The `<ConectedRouter />` need to be modified **not** to dispatch a __LOCATION_CHANGED__ action on the client when it was rendered on the server.

This is related to #4717, it would be great if the same functionality was supported for server-side rendering.

**Comment by timdorr** [comment]
The only reason we provide `staticContext` back to the caller is so that we have a means to emit changes and the server can react to them. But if you have a Redux store, you already have this functionality. Just dispatch an action and respond to it on your server after rendering. 

It's really that simple. We don't need to confuse things by offering two APIs that do the same thing.
