### ISSUE TITLE
StaticRouter includes leading slash

### ISSUE THREAD

**Issue by mxstbr** [ReactTraining/react-router#5488]
## Version
`react-router` v4.2.0
`react-router-dom` v4.2.2

## Steps to reproduce

Server-side render a `react-router` app with a `<Link to="?some=query" />`.

## Expected Behavior

It should generate the same anchor tag HTML on the server as on the client.

## Actual Behavior

![screen shot 2017-09-01 at 4 07 55 pm](https://user-images.githubusercontent.com/7525670/29973755-ea6f6830-8f30-11e7-80b8-27af23bc5129.png)

Any ideas why this is happening? I'm stumped. Tried including a different/empty `basename` on client and server but it's still there. Maybe related to #5127, but it's not a relative link is it?

**Comment by pshrmn** [comment]
The `<StaticRouter>` is a bit funky since it doesn't use a `history` instance, but it is actually the client side `href` that I am surprised about because `history` is supposed to return absolute paths.

The bug is in our `<Link>` implementation. [`<Link>` assumes](https://github.com/ReactTraining/react-router/blob/v4.2.2/packages/react-router-dom/modules/Link.js#L72) that if you pass it a string `to` prop that that string includes a pathname.

In the short term, if you switch from `<Link to="?some=query" />` to `<Link to={{ search: "?some=query" }} />`, you should get consistent results, although the results might still be incorrect (since the `pathname` should be resolved based on the current location, not just default to root).

**Comment by mxstbr** [comment]
Would the fix here be to introduce a second check `if (to[0] === '?')` and then passing `to` to search or something to that effect?

**Comment by pshrmn** [comment]
I think that we should be using the `createLocation` function exported by `history` to create an actual location object (`parsePath` would be another option, but `createLocation` is necesary for resolving relative paths with the current URL`).

I should have a PR up shortly. I'm taking this opportunity to finally have the `<Link>`s store their `href` in state so that they aren't recalculating that on every single re-render. Not a huge win, but it should be a bit more efficient.

**Comment by pshrmn** [comment]
Opened #5489
