### ISSUE TITLE
default 404 not working

### ISSUE THREAD

**Issue by heinhoang** [ReactTraining/react-router#5514]
"react-router-dom": "^4.2.2"
My routes like this
```
<Switch>
	<Route path="/dashboard" name="Dashboard" component={Dashboard} />
	<Redirect from="/" to='/dashboard' />
	<Route component={NoMatch} />
</Switch>
```
when I navigate to a non-existing url (locallhost/#/aaa), it always returns to /dashboard
I also tried this `<Route exact path="/" render={() => <Redirect to="/dashboard" />} />`
but no use

**Comment by pshrmn** [comment]
The provided code snippets are not enough to give a definitive answer (we provide a CodeSandbox link in the issue template that can be edited to run your code, please use it!). Based on the provided code, the `<Redirect>` should have the `exact` prop in order to only redirect from the root (`/`) location. If that doesn't fix it for you, you'll need to provide a more complete example.

**Comment by heinhoang** [comment]
Thnaks @pshrmn, the `exact` works
