### ISSUE TITLE
conditional dash

### ISSUE THREAD

**Issue by PedroEsperanca** [ReactTraining/react-router#5536]
I'm trying to resolve routes like:
`/product/:name?-:id`

that would allow routes like:
```
/product/wtv-3652672
/product/3652672
```
But this does not seem to work.
What's the recommended way to conditionally include dashes ?

**Comment by pshrmn** [comment]
React Router uses `path-to-regexp` for its route matching. You should check out its configuration options, especially [custom match parameters](https://github.com/pillarjs/path-to-regexp#custom-match-parameters).
```js
<Route path='/product/:name(\w+-)?:id' ... />
```
You'll have to manually strip the dash off of the name, but otherwise it seems to match fine.

For future reference, you can use https://pshrmn.github.io/route-tester to test out combinations of `<Route>` `path`s and its other props.
