### ISSUE TITLE
<Redirect from={ignoredPath}> from is ignored.

### ISSUE THREAD

**Issue by jhicken** [ReactTraining/react-router#5548]
## Version
4.2.0

## Expected Behavior
I would expect <Redirect from="/stuff/cool" to="/stuff/nuggets" /> to only redirect when the from is matched.

## Actual Behavior
I am always redirected.

I am guessing this just never got implemented.

https://reacttraining.com/react-router/web/api/Redirect/from-string

It looks like from is just never used.
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Redirect.js#L14

Am I missing something? Is this on someones backlog?

**Comment by pshrmn** [comment]
I have no idea what your expected/actual behavior is referring to since you didn't provide any example code.

`from` isn't really a prop of `<Redirect>`. Instead, it is an alias for the `path` prop of a `<Route>` and it can **only** be used inside of a `<Switch>`.
```js
<Switch>
  {/* these two redirects are the same */}
  <Redirect from='/somewhere' to='/somewhere-else' />
  <Redirect path='/somewhere' to='/somewhere-else' />
</Switch>

const Thing = () => (
  <div>
    {/* this Redirect will always redirect because it isn't in a Switch */}
    <Redirect from='/somewhere' to='/somewhere-else' />
  </div>
)
```

**Comment by jhicken** [comment]
You obviously did understand what I meant. Please don't be a jerk.

I apologize. I missed that in the docs. Thanks for clarifying that for me.

**Comment by pshrmn** [comment]
I'm sorry if you felt that I was being rude. My intentions were to state "I'm making a guess here because I don't have enough information, here is what you could have done to fix that".

When an issue is opened with no example code, all anyone but the issue creator can do is to speculate. That makes it very difficult to identify exactly what the issue is and provide assistance. Here, I put out a couple of possible solution to what might have been your problem. I'm glad that helped your figure out the problem, but to be honest, I'm still not sure exactly what the original issue was.

**Comment by jhicken** [comment]
Yup I get it. I thought the simple piece of code I pasted was enough. I apologize that it was confusing. I could have put a better example together. 

My problem was that I was missing the `<Switch>` around the `<Redirect>`.
