### ISSUE TITLE
Weird behavior if  route order change 

### ISSUE THREAD

**Issue by eromoe** [ReactTraining/react-router#5549]
Hi, I found this problem today,  I have routes like below
```
      <Switch>
        <Route exact path="/" component={HomePage} />
        <Route path="/annotator" component={AnnotatorPage}/>
        <Route path="/corpus/:corpusId" component={CorpusPage} />
        <Route component={NotFoundPage} />
      </Switch>
```
In `CorpusPage`  , there is a `< Link >`  point to `AnnotatorPage`.
I click Link,  url change, but AnnotatorPage not be loaded. 

After some test,  I I found put `HomePage`  at bottom works.
```
      <Switch>
        <Route path="/annotator" component={AnnotatorPage}/>
        <Route path="/corpus/:corpusId" component={CorpusPage} />
        <Route exact path="/" component={HomePage} />
        <Route component={NotFoundPage} />
      </Switch>
```

This behaviour is weird , a bug ??  Or is there any doc talk about this?

**Comment by pshrmn** [comment]
The described behavior shouldn't be happening based on what you've provided and I have to imagine the cause is something outside of React Router's control.

If you can put together a reproducible example of what you're running into with your app (you can fork this sandbox https://codesandbox.io/s/n55VljYk7), we can take a closer look at it.

**Comment by eromoe** [comment]
Sorry, it is my fault ,  I have some code  in `componentWillReceiveProps` which affect re-render.
