### ISSUE TITLE
location.key in undefined if hash using BrowserHistory

### ISSUE THREAD

**Issue by Danetag** [ReactTraining/react-router#5578]
## Version
4.1.2

Hello all!

The title is pretty much self explanatory: My `location.key` is undefined if my url contains a hash, and doesn't `Match` with the path I gave (it works without the hash)

Any idea why? Is there an option I missed?

Thanks for your hard work!
Arnaud

**Comment by timdorr** [comment]
This is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

**Comment by Danetag** [comment]
Isn't it a bug though..? We'll turn to Stack Overflow then. Thanks!

**Comment by pshrmn** [comment]
It is difficult to say whether it is a bug or an error without a reproducible repo, but there is no reason that what you described should happen.

Location issues should also be posted in the `history` repo, since that is what controls creating objects. https://github.com/ReactTraining/history/blob/master/modules/LocationUtils.js

**Comment by Danetag** [comment]
@pshrmn Thank you!
