### ISSUE TITLE
query string is not match

### ISSUE THREAD

**Issue by rustam-gaifiev** [ReactTraining/react-router#5580]
path-to-regexp  is support template like this:
/:lang?prop1=:prop1

but Route component is not supported this case bacause here it takes only pathname string. It woould be better to take **location.pathname + location.search**

https://github.com/ReactTraining/react-router/blob/9662a48fbc5de97f820608349ab37b4af5dba896/packages/react-router/modules/Route.js#L66

**Comment by timdorr** [comment]
path-to-regexp doesn't support query strings. Doing it this way would mean `/?foo=:foo&bar=:bar` would not match `/?bar=1&foo=2`, even though it is a logical match. Because query string processing is such an opinionated thing (how you handle arrays, boolean handling, etc), we have removed it and leave it up to you to handle.

**Comment by rustam-gaifiev** [comment]
path-to-regexp is working well with query string. You can try it here:
http://forbeslindesay.github.io/express-route-tester/

I'm running server-side rendering like this:
// route = {
//    path: '/:lang/search?query=:query'
// }
const match = matchPath( '/en/search/query=aaaa', route );
// math = {params: {lang: 'en', query: 'aaaa'}}

and it is ok, but when I'm trying to render on client side, it is not matched as I pointed above.

**Comment by timdorr** [comment]
No, it doesn't. If you add a second parameter and switch the order around, it will not match. Query string processing isn't supported.

**Comment by Wildhoney** [comment]
I made a simple implementation for my case, although you could make it more robust by using [`matchPath`](https://reacttraining.com/react-router/web/api/matchPath). Downside is that you need to pass in all of the same props that you use for the `<NavLink />` component, because the `isActive` prop doesn't pass the `NavLink` props as they're not available at the point &ndash; you could create a shared object that's used both to construct the `NavLink` **and** passed in to the `isActive` prop.

```javascript
<NavLink
    to="/shortlist/sales?customer_id=1"
    isActive={this.determine("/shortlist/sales?customer_id=1")}
    >
    Shortlist
</NavLink>
```

Where `this.determine` is created as:

```javascript
import { parse } from 'query-string';
import hash from 'object-hash';

// ...

determine(path) {

    const [pathname, search = ''] = path.split('?');

    return (match, location) => {
        const isPathMatched = location.pathname === pathname;
        const isQueryPatched = hash(parse(location.search)) === hash(parse(`?${search}`));
        return isPathMatched && isQueryPatched;
    };

}
```

Using the `hash` allows the search query params to be in any order. It's not overly robust, as mentioned earlier, but for my case it's adequate, and is a good starting point for anybody who's going to take it further.

To me it seems a fundamental part of URL matching, and I'm highly surprised that React Router doesn't support it. Maybe when we rewrite it from scratch, we'll have that functionality in v5 🎉
