### ISSUE TITLE
Proposal: Remove `children` prop, add prop about when to render

### ISSUE THREAD

**Issue by ryanflorence** [ReactTraining/react-router#5583]
I'd like to change how Route `render` and `children` work.

## What's the difference between them?

```jsx
<Route path="/foo" children={() => (
  <div>Children always renders, match or miss.</div>
)}>

<Route path="/foo" render={() => (
  <div>Render only renders if there's a match, null if miss</div>
)}>
```

## The API isn't instructive

The API is not instructive of behavior at all: "render" doesn't indicate "only renders when there's a match" and children doesn't indicate anything either.

Maybe we can ditch having two render props with a prop that *is* instructive of the behavior.

```jsx
<Route alwaysRender={true} render={({ match }) => (
  <div>Now we only have one render prop, and an instructive API</div>
)}/>
```

I'm pretty convinced this is a good way forward. Route has two types of props:

- How should I match? (`path`, `exact`, `strict`)
- How should I render? (`render`, `children`, `component`)

It’s a bit conflated that the distinction between `render` and `children` is how things match!

## Component prop

Also, with this change the `component` prop can participate in use-cases where you want to render even when there's no match. Today you have to use the `children` prop.

```jsx
<Route children={(props) => <OtherThing {...props} />}/>
// becomes this when the use case for the route changes:
<Route alwaysRender={true} component={OtherThing}/>
```

## Bikeshedding on the name of the prop

```jsx
<Route alwaysRender={false} render={() => ()}/>
<Route renderOnMiss={false} render={() => ()}/>
<Route renderOnMatchOnly={true} render={() => ()}/>
<Route renderOn={"match" || "miss" || "both"} render={() => ()}/>
<Route ignoreMatch={false} render={() => ()}/>
```

Thoughts?

**Comment by hunterc** [comment]
I agree that the difference between `children` prop and `render` is a little annoying.
Two things I like about your suggestion:
1. **remove `children` and just use `render` for render function behavior**
  This can be confusing and I like simplifying it to always be one prop.
2. **add another "behavior prop" to tell Route to always render regardless of match**
  Since the current api uses a prop to denote behavior, (`strict`, `exact`), I like the idea of having a prop that means "render regardless of match". I also like that this means the `component={Component}` pattern can exist for always render scenarios.

As far as naming, I like `alwaysRender` or a single word like `always`.

**Comment by edygar** [comment]
```jsx
<Route type={'miss' | 'match' | 'any'} render={({ match, route }) => } />
```

**Comment by kwelch** [comment]
Dropping children for the confusion makes sense. I like the idea of render and component essentially working the same with the main difference being inline. Lastly I think alwaysRender is the mostly intuitive.

**Comment by edygar** [comment]
Haha, new idea:

```jsx
<Route when={'miss' | 'match' | 'always'} render={({ match, route }) => } />
```

**Comment by klzns** [comment]
Why do you need the `alwaysRender` prop when there's the `match` param in the render function?

**Comment by jimthedev** [comment]
Like @edygar said but reverse the prop order in examples to read like a sentence:

```
<Route render={({ match, route }) => } when={'miss' | 'match' | 'always'} />
```

**Comment by ryanflorence** [comment]
@klzns the first stab at the v4 API started that way but it was just way too inconvenient for every route to be checking "match" before rendering. You rarely need the "always render" behavior.

**Comment by timdorr** [comment]
Why not just merge the props together?
```js
<Route rendeAlwaysr={() => ()}/>
<Route renderMiss={() => ()}/>
<Route renderMatch={() => ()}/>
```

**Comment by insin** [comment]
Benefit of making it something which has to be `true`:

```html
<Route always render={() => ()}/>
```

**Comment by ryanflorence** [comment]
@timdorr 

```jsx
<Route renderAlways={() => ()}/>
<Route   renderMiss={() => ()}/>
<Route  renderMatch={() => ()}/>
<Route componentAlways={Foo}/>
<Route   componentMiss={Foo}/>
<Route  componentMatch={Foo}/>
```

**Comment by approots** [comment]
Would rather not have potential props conflict confusion:

```
<Route renderAlways={() => ()} renderMiss={() => ()}/>`
<Route always miss render={() => ()} />
```

So I'd prefer the @edygar suggestion:

`<Route when={'miss' | 'match' | 'always'} render={({ match, route }) => } />`

And default to `always` and a `match` check could be made as suggested by @klzns

**Comment by JulienPradet** [comment]
I like the core idea ! :)

For these kind of cases I usually go for a prop `should...` to match a bit with the React API. How about `shouldRouteRender` ?

And it would be nice if children was kept but deprecated for a smooth transition.

**Comment by cfenzo** [comment]
I like the idea of a `always` flag/boolean for the cases where you want to always render..
But if you do end up with a prop like `when={'miss' | 'match' | 'always'}`, please don't make `always` the default..

**Comment by HeyHugo** [comment]
Hm can't you already "always render" by just skip having `path` prop?
Like this:
```
<Route component={SomeComponent}>
or 
<Route render={() => (<div>hello</div>)}>
```

The only thing I can think of that might not be easily done is rendering on the negation of path (render on any path except path matching X)

**Comment by ryanflorence** [comment]
@HeyHugo 

NavLinks:

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L27-L31

Custom Links:
https://reacttraining.com/react-router/web/example/custom-link

Animations:
https://reacttraining.com/react-router/web/example/animated-transitions

**Comment by HeyHugo** [comment]
I see, thanks

**Comment by HeyHugo** [comment]
Since it is a boolean I think it would be nice if the API aligns with how other boolean props on `<Route>` are used. In other words it is assumed to be `true` when present and `false` otherwise
```
<Route alwaysRender path="/foo" render={() => ()}/>
```

Idea of alternative name for the prop `forceRender`

**Comment by mjackson** [comment]
Thanks for bringing this up, @ryanflorence. I was thinking about this the other day as well! I like the idea of `<Route alwaysRender>`.

**Comment by jole78** [comment]
Personally I'd go for the renderOn={"match" || "miss" || "both"} or a prop that would allow me to control when a route should render its children. I have a use case like the one below where I only want to render the page footer when I'm on the exact match...I know I can get around it now by using a render prop but it looks and feels a little cumbersome....

```javascript
               <Route path={match.path} exact>
                    <Page.Footer>
                        SOME FOOTER STUFF ONLY TO SHOW ON THE EXACT MATCH
                    </Page.Footer>
                </Route>
```

**Comment by gnoff** [comment]
I probably don't know all the reasons `<Match />` was renamed `<Route />` but perhaps it's time to go back and add `<Match />` `<Miss />` and `<Always />`

I always thought Match was more expressive of what was happening.

Assuming that isn't how thing go however and we stick with a prop...
Its hard to think of a render function that conditionally needs to flip between match and always (or another pair of conditions) so having boolean properties for JSX sugar is unlikely to be used meaningfully and using a when prop taking enumerable valid render conditions is impossible to use inconsistently so I'd favor that.

**Comment by GodsBreath** [comment]
This is slightly off-topic but still relevant. Why not use the **actual** child element of the Route to determine what is rendered instead of a prop? It seems like a hack to pass render functions or component constructors to a component when you can accomplish the same thing with built-in props.children prop? It would be a lot more intuitive for new users. It would also make it easy to pass props to the rendered component, instead of having to pass them via an anonymous function wrapper

```
<Route path="/mycomponent" render={(props) => <MyComponent {props...} myProp="myVal" />} />
```

```
<Route path="/mycomponent"> 
  <MyComponent myProp="myVal" />
</Route>
```

And, of course, this would work perfectly well in conjunction with an `alwaysRender` prop.

**Comment by gnoff** [comment]
@GodsBreath I think the argument against your framing is that there would be implicit prop assignment on MyComponent causing unexpected interactions between the route provided props and the owner provided props. render prop forces the consumer to make an explicit choice on how to layer these things and guarantees you can compatibly compose any component, especially ones you did not write yourself, with a Route component

**Comment by GodsBreath** [comment]
I'm relatively new at this, but that seems to sacrifice an awful lot of readability for the sake of what seems to be a relatively unlikely scenario. The example I provided is simple. It gets even worse when there are several props that need to be passed to MyComponent. If there is a conflict with the implicitly passed props, then at that point the consumer could still make use of the render prop.

I suppose you could improve readability a bit by replacing the anonymous, inline function with a named function that does some partial application, but that has it's own readability problems:

```
MyComponent.makeRenderer = (myProp) => {
  return (props) => <MyComponent {...props} myProp={myProp} />;
};

<Route path='/mycomponent' render={MyComponent.makeRenderer('myVal')} />

```

Either way, it seems like a lot of trouble and violation of the react philosophy just to accommodate a hypothetical naming collision between router props and component props.

**Comment by iamandrewluca** [comment]
@GodsBreath also thought about this, why not use direct children. 
But it seems that, `children`, `render`, `component` should be called at some point and render something.

One way we could use children directly is to use it as a render prop

```javascript
<Route path="/mycomponent"> 
  {({match}) => match && (
    <MyComponent myProp="myVal" />
  )}
</Route>
```

But as we can see it does not look nicer

If we add children directly inside route, it gets executed at that moment when we reach the route code, and errors may throw.
ex: `someAsyncData` is loaded when we are on route `/mycomponent`

```javascript
<Route path="/mycomponent"> 
  <div>{someAsyncData.someInfo}</div>
</Route>
```

`someInfo` is not available at this moment, because `someAsyncData` is not loaded yet and errors may throw.

Better this. `render` is called when we are on `/mycomponent` route and `someAsyncData` is kind of on loading already

```javascript
<Route path="/mycomponent" render={() => (
  <div>{someAsyncData.someInfo}</div>
)} />
```

Kind of this. Correct me someone if I'm wrong.

**Comment by ianstormtaylor** [comment]
FWIW, I like the proposed `when` naming scheme...

```js
<Route when="always">
  {...}
</Route>
```

...because I think it might be nice to have this become a sort of pseudo-standard for render-prop-based APIs. I have often wanted a similar thing for Apollo-like state management libraries...

```js
<Query when="success">
  {({ data }) => (
    ...
  )}
</Query>
```

...instead of having to deal with the matching logic yourself all the time.

And in React Router's case it obviously makes sense to have `when="match"` as the default, whereas in other libraries the default might make sense as something else.

**Comment by GodsBreath** [comment]
I hope I'm not breaking ettiquette by bumping this thread.

**Comment by mjackson** [comment]
Thank you everyone for the discussion here. I think there is probably an easier way forward that I discussed in depth in #6362. Please give that a look and let me know what you think. If it sounds better, we can go ahead and close this.

**Comment by mjackson** [comment]
It's looking like #6362 is going to work, so I'm going to close this in favor of that.
