### ISSUE TITLE
Route parameter value with an encoded '?' as %3F not decoded in params

### ISSUE THREAD

**Issue by kellyrmilligan** [ReactTraining/react-router#5607]
## Version
4.1.1

## Test Case
https://codesandbox.io/s/zqj6wvk7m3

## Steps to reproduce
click on the  Topic Example ?

## Expected Behavior
`topic example %3F` should be displayed as `topic example ?`
## Actual Behavior
the param is displayed as `topic example %3F`

**Comment by timdorr** [comment]
This is ultimately caused by `history`. Here's the issue open to track the bug: ReactTraining/history#505

**Comment by pshrmn** [comment]
As a follow up, `history` uses `decodeURI` to decode pathnames. `decodeURI` cannot decode escape sequences that could not have been created by `encodeURI`. This means that because `encodeURI` cannot encode a question mark, `decodeURI` cannot decode an encoded question mark.
```js
const eU = encodeURI('?') // '?'
const eUC = encodeURIComponent('?') // '%3F'
decodeURI(eU) // '?'
decodeURI(eUC) // '%3F'
```
I would say that if you have characters that need to be encoded using `encodeURIComponent`, you should expect to have to call `decodeURIComponent` to decode them.

**Comment by ottumm** [comment]
> I would say that if you have characters that need to be encoded using encodeURIComponent, you should expect to have to call decodeURIComponent to decode them.

I don't think this workaround is generally safe, due to the fact that `decodeURI` and `decodeURIComponent` have overlapping reserved character sets, so calling `decodeURIComponent` on a string that has already been decoded by `decodeURI` runs the risk of double-decoding. Consider this example:

```
> encodedPathComponent = '%2520%2F'
'%2520%2F'
> correctDecodedValue = '%20/'
'%20/'
> decodeURIComponent(encodedPathComponent) == correctDecodedValue
true
> decodeURI(encodedPathComponent) == correctDecodedValue
false
> decodeURIComponent(decodeURI(encodedPathComponent)) == correctDecodedValue
false
```

I fear the above example might not be the clearest, but the intention is to show that there are validly-encoded URL path components that cannot be correctly decoded once `decodeURI` is called on them. If `react-router` offered a way to opt-out of the automatic decoding that could be an acceptable workaround.
