### ISSUE TITLE
Switch with Route and Redirect doesn't work in production build

### ISSUE THREAD

**Issue by ZakTax** [ReactTraining/react-router#5632]
## Version
4.2.0

## Test Case
https://codesandbox.io/s/pylwwqxrj0 :warning: however it's a production-only issue

## Steps to reproduce
- create a Switch with a catch-all Redirect to the path of another Route:
```
    <Switch>
      <Route path="/settings/profile" exact component={Profile} />
      <Redirect to="/settings/profile" />
    </Switch>
```
- **build production app** + navigate to page with switch (don't match the Route's path)

## Expected Behavior
- url changes to /settings/profile
- newly matched Route now displays
- :+1: expected behavior matches actual behavior in development environment

## Actual Behavior
- url changes to /settings/profile
- react devtools shows that Redirect never unmounts, has null children
- Route doesn't match until user refreshes page

## Comments
Switch documentation states: `Renders the first child <Route> or <Redirect> that matches the location.`

Let me know if I'm mistaken about how this should work. However, fact that it works in development but not in production build makes me think this is a bug.

**Comment by ZakTax** [comment]
Just tried to replicate using a fresh CRA setup and everything worked as expected. It also worked as expected when using a fresh CRA with our dependencies and lockfile pasted in. I think this means it will be impossible to replicate without our exact setup. Let me know if there's anything else I could do to help replicate, otherwise close this issue.

**Comment by yellohfilipe** [comment]
Are you using `react-router-redux`? Because I have the same issue and I think the problem comes from that package.

When I build my CRA, it seems to be packing up two versions of react. That wasn't really a problem until upgrading to React 16 I guess.

When I do `npm ls react` I get:

`npm ERR! invalid: react-router-redux@5.0.0-alpha.6 /Users/.../node_modules/react-router-redux`

And if you check the build file source maps, you can see that the `react-router-redux` has imported React 15.

**Comment by timdorr** [comment]
This is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

**Comment by yellohfilipe** [comment]
Right, this might not be the right place for it, but I think it is an issue. This is actually blocking us to deploy to production at the moment. 

I have forked `react-router-redux`, changed the `peerDependencies` requirements to allow React 16, and published it. I wanted to make sure that this is the problem. If I change the imports to use my forked version the app works with no problems in staging (which uses the CRA prod build).

Should I report this somewhere else, didn't find this issue in the list or this is not an issue because the package isn't supposed to support React 16 anyway? :)

**Comment by ZakTax** [comment]
@yellohfilipe It was also blocking us from production. We found a fix, might work for you:
Instead of `<Redirect ... />` try `<Route render={() => <Redirect ... />} />`

**Comment by inoyakaigor** [comment]
Just for history: I had a similar problem and in my case component with `<Switch/>` have `@observer` decorator which blocked re-render
