### ISSUE TITLE
withRouter not re-rendering wrapped component on route change

### ISSUE THREAD

**Issue by bristoljon** [ReactTraining/react-router#5642]
## Version
4.2.0

## Test Case
https://codesandbox.io/s/2ol8mrj27j

## Steps to reproduce
Nest a `withRouter` wrapped component inside another component that implements `shouldComponentUpdate`

## Expected Behavior
The wrapped component should receive updated props every time the route changes regardless of whether or not parent components implement `shouldComponentUpdate`

## Actual Behavior
The wrapped component does not receive updated `location` prop when route changes and so does not update

To be fair the documentation does state this will be the case after incorrectly stating 

> withRouter will re-render its component every time the route changes with the same props as <Route> render props: { match, location, history }.

Now I understand why this is the case due to the use of context however it doesn't need to be this way if `withRouter` implemented something like [this](https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076). 

Here context is only used to provide a mechanism for wrapped components to subscribe to changes in the provider. This would mean `withRouter` would actually live up to the above statement in the docs and would update it's component on every route change regardless of what it's parents do..

PS. I've used the BUG template for this issue but maybe it is actually a feature request

**Comment by pshrmn** [comment]
The existing behavior is intentional. I won't get into the details because this has been discussed numerous times, but subscriptions are not necessary.

Instead I would ask you to consider why the children of a component that should not update _should_ be updated. This "optimization" might be necessary for packages that are constantly triggering re-renders, but RR isn't re-rendering your entire application just to update the value of an `<input>`. This issue only occurs when the location changes, which I think is an event worthy of actually considering whether a component should update instead of relying on subscriptions to get around the block. That is all RR needs you to do. If a component actually should update, just pass it a prop that changes when the location changes and you'll be good to go.

**Comment by bristoljon** [comment]
Yeah that makes sense, thanks for the quick reply.

For some reason I assumed this was what `withRouter` was doing already as hadn't hit any blocked update problems until just now but turns out that was just because so far I had only used `withRouter` to get the `history` navigation functions which I guess will always work.

Cheers, for the input and thanks to all involved for making such a nice framework.

**Comment by reyraa** [comment]
Assume we have a component which is design to create a specific link based on route change and some props:
```
const RelativeLink = ({
  location, to, children, customProp,
}) => {
  const path = calculationsHere(location.pathname, customProp);

  return (
    <Link to={path}>{ children }</Link>
  );
};
```
I need this component to update when `location.pathname` changed. but vividly it won't.
