### ISSUE TITLE
<Link /> tag is not friendly with <BrowserRouter /> ?

### ISSUE THREAD

**Issue by derencel20** [ReactTraining/react-router#5646]
I have a `<Link to="/changeProfileDetails" />` tag and a `<Link to="/farmList" />`. I came from the path `/farmList` then clicked on `<Link to="/changeProfileDetails" />`.

Expected behavior:
The current path will be `/changeProfileDetails`

Actual behavior:
The current path was `/farmList#/changeProfile`

**Comment by pshrmn** [comment]
This is almost certainly an issue on your end. I'm not sure _what_ the issue is (since there is no demo to reference), but the described behavior is not possible with the provided `<Link>`s (`<Link>`s renders anchors whose `href` is an absolute path). The hash makes me think you've got a hash history mixed up in your code somewhere.

**Comment by derencel20** [comment]
I didn't use hash history here's my code. [Code here](https://gitlab.com/sekiryuutei47/testproj)
