### ISSUE TITLE
React Native docs example simulator error

### ISSUE THREAD

**Issue by sundayha** [ReactTraining/react-router#5678]
On this page, and when I press the top to play an error 'Streaming for this account has had been temporarily disabled'

[Please click here](https://reacttraining.com/react-router/native/example/Basic)

**Comment by timdorr** [comment]
Looks like the service we're using for examples doesn't scale well. Want to put together a PR to replace it?

**Comment by rohyadav** [comment]
i am getting same error 
<img width="587" alt="rrn" src="https://user-images.githubusercontent.com/21152844/35197746-48711b6a-ff0a-11e7-8983-d897a77ce86a.png">

**Comment by pshrmn** [comment]
I think it probably lapsed because Appetize is a bit pricey (something like a couple hundred per month, but varies based on the number of people using the documentation). A better option might be to use https://snack.expo.io (which also uses Appetize, but is free and allows users to use the apps on their actual device).
