### ISSUE TITLE
onlyActiveOnIndex not works on NavLink

### ISSUE THREAD

**Issue by marykauf** [ReactTraining/react-router#5705]
I'm really confused.
some say `onlyActiveOnIndex ` no longer exists.
some say it only works with `Indexlink`
some say it was completely removed because RRV4 does not care about index concept anymore

75m spent and now after opening and reading more than 40 tabs on chrome can't still find a solution just for disabling a not interesting default behavior for '/' route `NavLink`

HELP extremely needed

**Comment by pshrmn** [comment]
`<NavLink>` supports the `<Route>` props for determining if it is active, so [`exact`](https://reacttraining.com/react-router/web/api/NavLink/exact-bool) is what you want. (Also, this will probably be more logical in v5. `exact` was a mistake and we'll be switching to implicit exact matching in v5 so that exact matching is done by default.)

```js
<NavLink exact to='/'>Home</NavLink>
```
