### ISSUE TITLE
Keep component from unmounting?

### ISSUE THREAD

**Issue by VictorChen** [ReactTraining/react-router#5710]
I have a component that fetches stuff and I would like to keep that component from unmounting when switching routes. I've read through the docs and couldn't find a way to achieve this, is this possible? eg:

```jsx
class About extends React.Component {
  componentDidMount() {
    console.log('mounted');
    // fetch stuff here
  }

  render() {
    return (
      <div>
        <h2>About</h2>
      </div>
    );
  }
}

<Router>
  <div>
    <ul>
      <li><Link to="/">Home</Link></li>
      <li><Link to="/about">About</Link></li>
      <li><Link to="/topics">Topics</Link></li>
    </ul>

    <hr />

    <Route exact path="/" component={Home} />
    <Route path="/about" component={About} />
    <Route path="/topics" component={Topics} />
  </div>
</Router>
```

When I switch between routes (`About` -> `Topics` -> `About` -> `Home` -> `About`), the `About` component gets mounted everytime.

**Comment by pshrmn** [comment]
You can use `<Route children>` to render even when a route's path does not match.
```js
<Route path='/about' children={props => ... } />
```
That said, I don't think that you want to do that. Instead, you should have some cache/store mechanism so that when `About` re-mounts, it doesn't have to make a duplicate network request. How you do that is up to you (use Redux/MobX?), but not really React Router related.
