### ISSUE TITLE
Using MemoryRouter with enzyme shallow testing

### ISSUE THREAD

**Issue by stevenmusumeche** [ReactTraining/react-router#5726]
I am upgrading my app to v4, and everything works great and makes sense, but I have run into major problems with my tests that have `<Link>` elements in them.  The following test works in v3:

    const wrapper = shallow(
            <UserList foo="bar" />
    );
    expect(wrapper.hasClass('user-list')).to.be.true;

When updating to v4, I first got the issue about Links not rendering within a router context.  So, I read the docs and they say to use `MemoryRouter`, like this:

    const wrapper = shallow(
        <MemoryRouter>
            <UserList foo="bar" />
        </MemoryRouter>
    );

However, now many tests fail, since the root element passed to `shallow` is not `UserList`.  Calling any of enzyme's methods, like `setProps`, `update`, and more, do not work.

So far, the only way I can make this work is to completely forgo using shallow mounting and instead using `render`, which seems like a bad tradeoff for unit testing.  

Is there a way to use shallow rendering with React Router v4?

**Comment by pshrmn** [comment]
It has been a bit since I've written Enzyme/React Router tests, but you _might_ need to use `mount` instead of `shallow`. Maybe something has changed, but I thought that there were issues with RR and `shallow` renders.

Alternatively, I wrote this [`react-router-test-context`](https://www.npmjs.com/package/react-router-test-context) package that you can use if you're having troubles with Enzyme. Generally speaking, using a `<MemoryRouter>` is "better" since it uses an actual `history` object (and thus will be up to date if `history` is changed is some manner, not that I expect it to), but it seems like a decent number of people are using that package, too.

**Comment by stevenmusumeche** [comment]
Thanks @pshrmn! Your package fixed some of my issues. It turns out most of my other issues were a little different than I suspected.  

I was getting this error when using enzyme's `html()` function in my assertions.  For example `expect(wrapper.html()).to.contain('foo');`.  Changing this to `expect(wrapper.text()).to.contain('foo');` removed the error.

**Comment by kusmierz** [comment]
@pshrmn is it working with 4.0?

**Comment by pshrmn** [comment]
@kusmierz Yes, that package is for v4.

**Comment by wellnine** [comment]
Hello. Could you, please, describe how I can test some method of my Component that was mounted inside MemoryRouter? 

```
const wrapper = mount(
    <MemoryRouter>
        <UserList foo="bar" />
    </MemoryRouter>
);

wrapper.find(UserList).instance().myMethod() -> throws an error
```
