### ISSUE TITLE
Prompt is showing when using hash in route

### ISSUE THREAD

**Issue by j-o-d-o** [ReactTraining/react-router#5756]
## Version
4.2.2

## Steps to reproduce & Actuall Behavior
I am using a hash in the URL to switch between tabs in react.js. Here is an example: 
```
<a onClick={() => this.changeLocation("#data")} href="#data">Data</a>
```
On tab change the Prompt shows. But no matter what the users clicks (Continue or Cancel). The tab will change to the new tab regardles.

## Expected Behavior
So the ideal behavior would be, that the prompt does not show at all on tab change. I would like it to show only when the component will unmount. In previous versions, there was something like a routerWillLeave hook... If that is not possible I would at least like to have some kind of callback to prevent the tab change.

### EDIT:
Okay, this would be a possible fix:

```
<Prompt when={this.props.unsavedChanges} message={ location => {
    return this.props.location.pathname === location.pathname ? 
        true : "You have unsaved changes. Are you sure you want to leave without saving?";
}}/>
```
But it feels a little hacky. I would prefer if I could tell the Prompt when to show up. E.g. on unmounting of the component or when the URL changed.

**Comment by timdorr** [comment]
I'm confused. Are you using a HashRouter? You can't link directly to paths with the hash, you have to use a Link.

**Comment by pshrmn** [comment]
The `<Prompt>` (or more specifically, the `getUserConfirmation` function) fires on location changes and updating the hash _is_ a location change (e.g. you can use your browser's forward/back button to navigate between hash locations with the same pathname).

I can understand why this combination of navigation blocking and in-page navigation can be annoying to deal with, but I would recommend using your edited in solution. I would agree that returning a boolean or a string with the `message` function is a bit odd (in large part because of the `message` name), but that _is_ the [supported API](https://github.com/ReactTraining/history/blob/v4.7.2/modules/createTransitionManager.js#L27-L41).

**Comment by timdorr** [comment]
And that API is matching the DOM's API for beforeunload: https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload

**Comment by j-o-d-o** [comment]
That makes sense, thanks for the clarification.
