### ISSUE TITLE
Router doc routes are incorrect

### ISSUE THREAD

**Issue by yuderekyu** [ReactTraining/react-router#5764]
Both `<MemoryRouter>` and `<StaticRouter>` links under the Router docs redirect to their respective readmes, instead of the correct routes. 

To reproduce, go [here](https://reacttraining.com/react-router/core/api/Router) and select either `<MemoryRouter>` or `<StaticRouter>`.

**Comment by pshrmn** [comment]
This was fixed in #5441, but it still needs to go live. The tricky thing right now is that the docs currently include unreleased API code and there isn't a great way to skip building that documentation; I'm not sure when the next minor release will be, but it would be nice to have that pretty close to when the site is updated.

**Comment by yuderekyu** [comment]
Ah, didn't see that issue. Sounds good.
