### ISSUE TITLE
React-router-redux: a route change is not causing a re-render

### ISSUE THREAD

**Issue by tasn** [ReactTraining/react-router#5795]
I found a bug with react-router-redux and pure components. It's hard for me to reason to exactly what's going on, but my guess is that the action is dispatch before the actual route change causing the component to re-render before the path is updated wherever Route looks, causing the route to never change. I added a link to a very simple example below, please take a look.

In the example you can see I printed two paths. The path I got from the store, and the path I got from withRouter and you can see they are different. The one from the store is up to date (showing that the component actually re-rendered after the path change) and the other is not (showing that wherever withRouter and Route take the path from is still stale at the time of the render).

One common workaround to this class of issues is wrapping every pure component with "withRouter", but that kind ruins the point because with it the whole tree would have to re-render on every route change.

I don't know the codebase, but an obviously solution to me would be to dispatch the redux action *after* react-router has changed its state internally. This will fix this issue without any ill-effects I can think of.

## Version
React-router: 4.2.0
react-router-redux: 5.0.0-alpha.9

## Test Case
https://codesandbox.io/s/mo8ov2zyz8

## Steps to reproduce
Try to navigate in the test case above.

## Expected Behavior
The routes should change (see the H1 below) and the two printed paths should be the same.

## Actual Behavior
The routes don't change (H1 below stays the same) and one of the paths is stale.

**Comment by timdorr** [comment]
See this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by tasn** [comment]
Hey @timdorr,

I'm aware of this guide, this is not the same issue. The issue here is react-redux-router and react-router having different routing information in some cases that cause issues with pure components.

Please take a look at the example and the description and you'll see this is something completely different, and I'd assume also solvable (unlike the other one).

Thanks.

**Comment by josepot** [comment]
Hi @tasn !

I know that this may look like a bug, but it's actually not a bug. IMHO it's a misusage of `PureComponent`.

First of you should keep in mind that the central component of `react-router`, which is `Route`: is a stateful component that relies on `context`. You may think that could be problematic when working with `react-redux` because the `connect` HOC returns an SCU component... But the truth is that as long as you make a reasonable usage of SCU everything should be ok.

In your example the component "PureContainer" is making what I think it's a misusage of SCU, which it's stopping the desired propagation of "context" that `react-router` needs in order to work. One way to illustrate that is with [this example](https://codesandbox.io/s/pjq0nl54pj), that's a fork of yours that doesn't use `react-router-redux` and that it has the exact same problem... Change the "PureContainer" to a non SCU component and everything will work fine ([example](https://codesandbox.io/s/pw66q37vl7)).

If you think about it "PureContainer" will always receive the same props (children). Also, it doesn't make a lot of sense to extend from PureComponent a component that's being enhanced by `connect`, because the resulting component of `connect` already uses SCU... That's not breaking anything... I'm just letting you know that's actually unnecessary and it doesn't make a lot of sense.

**Comment by josepot** [comment]
> I'm aware of this guide, this is not the same issue. The issue here is react-redux-router and react-router having different routing information in some cases that cause issues with pure components.

I think that the problem is that you don't quite understand what PureComponents do... As I showed you in my example, you can have that same issue without using `react-router-redux` if you make a "wrong" usage of SCU. Also, [reading this](https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076) perhaps would help you a bit to understand how SCU  interferes with `context`.

The point is that having a wrapper of `div` that just makes it "pure" is absurd.

**Comment by tasn** [comment]
Hey @josepot,

Thanks for your detailed reply, however I think you misunderstood my aim, which lead you to offering an alternative that will not work. I think some context may be in order.

First of all, the bug I'm reporting is not with the lack of context propagation, because as you can see, I'm passing the props directly with "withRouter". The bug I'm reporting is about a mismatch with the two paths, the one passed by react-redux-router and the one passed with withRouter.
The problem, I assume, is because the store is updated before the context is updated causing this issue, and I believe, shouldn't be too hard to fix.

I understand what PureComponents do (there's not much to it), which is why I got to exposing this issue in the first place. Obviously, what you're seeing here is a ridiculously stupid example that just triggers the issue, the usecase is reasonable and much more complex than this.

More context to my issue, and how I got to this, and why this usecase is valid in my pov:
As you know, redux's connect implements shouldComponentUpdate, which makes the component not update when the store doesn't update. This is the issue referred to in the "blocking guide" @timdorr linked to above. This obviously solves the issue, but it comes with a big price, now all the components under the store-linked one will re-render on every route move. Which means that if you have a component that makes expensive calculations on data from the store in order to pass to children, it'll have to recalc too. One way of approaching this is memoization, essentially caching the calculation, but this is hacky. React already has a mechanism for dealing with just this, which is PureComponents. The props don't change, the component need not update.

This leads us to the second alternative I tried, which is what exposed the bug described above. What I decided to do instead is to add react-router route changes to the store, and then connect to those in a deeper component, so my heavy-calculation component doesn't get updated any more (because it doesn't care about route changes) and only the inner ones do. This worked fine, except for one issue, the store gets updated before the context, so when the re-render is triggered in the child component, the Route components inside get the stale information (see the example in the original post) and don't re-render themselves.
The rendering bug (blocked) is triggered by PureComponents, but the real issue is that react-router and react-router-redux duplicate the location information and pass on conflicting values.

Two possible approaches for solving this come to mind. The first, is implementing a ConnectedRoute component that is store aware (but this is ugly), the second is just fixing it so that the context is updated before the store. 

To be honest though, the best solution would probably be "fixing" withRouter to behave more like connect, that is, trigger a redraw even if deep inside a component tree just like redux does it. It'll solve a lot of confusion for new users and essentially remove the need of the "blocking guide". I'm sure there's a good reason to why not to do it, but maybe it's worth considering still.

I understand that you are probably sick and tired of getting tickets by users that haven't read the blocking guide, but this one is different.

**Comment by tasn** [comment]
I took a quick glance at the code, and it looks like a known issue, though I assume this comment is here because people are encouraged to dispatch actions rather than use the normal routing functions, which will obviously cause it. I guess there's no proper way of fixing this, and the best way would be to fix withRouter to work more like "connect" as suggested above.

At the moment, using react-router causes either significant performance degradation in some cases, or just forces people to resort to a lot of manual memoziation instead of using the native react one.

Ref:

```

/**
 * This reducer will update the state with the most recent location history
 * has transitioned to. This may not be in sync with the router, particularly
 * if you have asynchronously-loaded routes, so reading from and relying on
 * this state is discouraged.
 */
```

From: https://github.com/ReactTraining/react-router/blob/96410c69be1ca32e294bf83e7d1321c39ecd286b/packages/react-router-redux/modules/reducer.js#L12

**Comment by kongdewen1994** [comment]
export default connect(
	mapStateToProps,undefined,undefined,{pure:false}
)(Main);
