### ISSUE TITLE
https://reacttraining.com/react-router/ does not render in google cached pages

### ISSUE THREAD

**Issue by joshball** [ReactTraining/react-router#5801]
If you search google for `https://reacttraining.com/react-router/` and click on the `Cached` page:

![image](https://user-images.githubusercontent.com/127526/34114514-3d599f72-e3d0-11e7-834f-92ad76091778.png)

It will not render the [page](https://webcache.googleusercontent.com/search?q=cache:CR2iIArL3l0J:https://reacttraining.com/react-router/+&cd=1&hl=en&ct=clnk&gl=us).

This is a bit of a disingenuous bug report, since this is happening on a site we are working on and I am surprised at how little content is out there about this issue. In a nutshell, I believe the problem is this:

1. google will fetch a site under one url:  `https://reacttraining.com/react-router/` 
2. google will render (in cached cases) that site under a different url: `https://webcache.googleusercontent.com/search?q=cache:CR2iIArL3l0J:https://reacttraining.com/react-router/+&cd=1&hl=en&ct=clnk&gl=us`

And the react router does not know what to do about this strange URL.

There is one suggestion of a solution out there (for router < v4):
https://stackoverflow.com/questions/42465841/react-router-and-google-cached-pages-for-spa

But I was hoping this could be addressed by the core team and added to the FAQ. 

Interestingly, I was curious about a server side solution, one that would capture the URL when the server first receives the request (with the correct url). It could save that URL in some initial state, and then the client code compare it against the URL it was seeing. If they were different, it could just use the server side URL (but do so internally rather than setting the actual location. 

Any thoughts on solving this issue?

**Comment by timdorr** [comment]
I'm not sure what we would do here. What about supporting other archival systems (archive.is, archive.org, other search engines)? What happens if the Google URL format changes (it has a few different forms already)? 

Also, why are you concerned with cached page services? If you need the pages to be cached correctly in isolation, you can server rendering them. But for SEO purposes, Googlebot is capable of executing and rendering the JS of React and React Router.

**Comment by thinkkevin** [comment]
@timdorr 

The problem is that when we use react-router for a SPA, we have multiple routes defined in the application. When loading the `https://webcache.googleusercontent.com/search?q=cache:CR2iIArL3l0J:https://reacttraining.com/react-router/+&cd=1&hl=en&ct=clnk&gl=us`, google is trying to load the cached html page and execute JS files. The react-router didn't match `/search` to any of the declared routes, so react-router would update the page from what had been cached to another page or fallback behavior like 404.

**Comment by manuel-jasso** [comment]
IMO The problem is Google cached pages should not execute JS, they should behave like JS is disabled, there can be a lot more JS code besides react-router that would fail if executed outside of the domain(s) they're designed for. I think this is not a react-router problem, the app should prevent further JS execution if it finds itself running on unexpected hosts. This is akin to the "clickjacking" problem.
