### ISSUE TITLE
<Redirect> is redirecting url containing static asset on https with service worker

### ISSUE THREAD

**Issue by James2516** [ReactTraining/react-router#5821]
## Version
4.2.2

## Steps to reproduce
https://redirect.netlify.com/
The first link works, but not the second. Why?

![](https://i.imgur.com/OMHnz6o.gif)

Service worker code: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/src/registerServiceWorker.js
```
import React from "react";
import { BrowserRouter, Redirect } from "react-router-dom";

const App = () => (
  <BrowserRouter>
    <div>
      <p>
        <a href="http://redirect.netlify.com/manifest.json">
          http://redirect.netlify.com/manifest.json
        </a>
      </p>
      <p>
        <a href="https://redirect.netlify.com/manifest.json">
          https://redirect.netlify.com/manifest.json
        </a>
      </p>
      <Redirect to="/" />
    </div>
  </BrowserRouter>
);

export default App;
```

**Comment by BTMPL** [comment]
There are a couple of concept you're missing.

1. Using `<a>` will cause an HTTP request, such a request is not handled by react-router
2. If a file called `manifest.json` exists on the server, a HTTP request to it (either by `<a>` or by direct URL entry) will most likelly take priority over lunching your app.
3. The code you created will always try to redirect to `/`, if react-router can't find a matching route for it. To use react-router navigation, use `<Link to="/manifest.json">` instead of `<a>` - you will notice that such a link will not navigate to the actual file.

**Comment by James2516** [comment]
https://d3qvnd0yua2g4d.cloudfront.net/
Couldn't get it to work with Cloudfront too. Unless somehow both Cloudfront and Netlify are configured wrongly.
Is anyone able to produce a working version of it?

**Comment by pshrmn** [comment]
This doesn't have anything to do with React Router; it has to be something on your end (and on the server not the client). If you open up the network tab in Chrome's devtools, you will see that clicking the `https` link will get a response containing HTML.

**Comment by BTMPL** [comment]
Yes, it looks like it's a SW issue (disabling react-router does not fix it, disabling SW does).
