### ISSUE TITLE
Uncaught DOMException: Failed to execute 'pushState' on 'History': function (data) { } could not be cloned.

### ISSUE THREAD

**Issue by keith890303** [ReactTraining/react-router#5840]
Question?

when I migration router V2.x to V4.2.0 , i got an error with history.push .
more detail see below :

**reason:** `some param in the state is a method`

**code:** `history.push('/abc',{callback: () => {// done something});`

**error:**

```
> Uncaught DOMException: Failed to execute 'pushState' on 'History': function (data) {
> 				// done something } could not be cloned.
```

this problem never found  in react-router V2.x 

bug? or there are other ways to solve this problem? 

thanks  advance

**Comment by pshrmn** [comment]
This is mostly a `history` issue, not a React Router issue, but I can offer a point of clarity.

Your second argument to `history.push` is being used to attach state to the location. However, state can only be serializable data and functions are not serializable, which is why you are getting that error. That is a browser implementation, not anything to do with React Router or `history`, so I can't think of any reason why that would have worked in RRv2.

**Comment by keith890303** [comment]
thks
