### ISSUE TITLE
Link not triggering redirect from Redirect component

### ISSUE THREAD

**Issue by Sawtaytoes** [ReactTraining/react-router#5842]
## Version
react-router-dom: 4.2.2

## Test Case
https://codesandbox.io/s/6wl8v8n27k
In further testing, using `push` on the `Redirect` component also doesn't change anything.

## Steps to reproduce
1. Setup a Link to a URL that triggers a Redirect component.
2. Click the Link component.

## Expected Behavior
When clicking the Link component, it should take you to that path and immediately redirect you to the other path.

## Actual Behavior
It takes you do that path and ignores all Redirect components on the page.

**Comment by pshrmn** [comment]
`<Redirect from>` only works inside of a `<Switch>` (where `<Redirect from>` is really just an alias for `<Route path>`). When you use a `<Redirect>` outside of a `<Switch>`, it will _always_ redirect to the `to` prop.

Now, you might we wondering why that isn't actually happening (after all, when you click the link to `/redirect`, the location stays as `/redirect`). When a `<Redirect>` is re-rendered, it compares the previous `to` prop to the next `to` prop. If those are equal (and in this case they always are), then a redirect will not be triggered because that could cause an infinite loop.

**Comment by Sawtaytoes** [comment]
Verified. The solution is to wrap `Redirect` in a `Switch`. Thanks!
