### ISSUE TITLE
Allow change <Link> tag

### ISSUE THREAD

**Issue by pravdomil** [ReactTraining/react-router#5844]
## Motivation
Clickable table rows.
```jsx
<table>
  <NavLink tag="tr" to="/item/123">
    <td>Item</td>
    <td>123</td>
  </NavLink>
</table>
```

## Current workaround
Implementing something like `<CustomLink>` which does exactly the same as `<Link>` but uses different tag.

## API changes
`<Link>` will have new prop called `tag` which controls Link's tag default is `"a"`
`<NavLink>` passes prop `tag` down to `<Link>`

## Research
[Google search](https://www.google.cz/search?q=react+router+link+row)

**Comment by pshrmn** [comment]
There have been multiple requests for it, but it just isn't something that the React Router team wants to encourage because using a non-anchor component for links begs for accessibility issues.

If you really want this behavior, you should probably just make local copies of the `Link` and `NavLink` modules and add this functionality yourself.
