### ISSUE TITLE
Prompt not preventing navigation when clicking browser back button or history.goBack() and previous page is external URL

### ISSUE THREAD

**Issue by ericbiewener** [ReactTraining/react-router#5875]
If I go to http://google.com in my browser, then directly edit the URL in the browser's address bar to go to a page in my app with a `Prompt` component, that prompt component is unable to block navigation when pressing the browser's back button or executing `history.goBack()`. 

## Test Case
https://codesandbox.io/s/32jzwvyy2m

## Steps to Reproduce
1. Go to http://google.com
2. Copy and paste this URL into your browser's address bar: https://32jzwvyy2m.codesandbox.io/2
3. Click the back button

The prompt does not fire.

**Comment by pshrmn** [comment]
This is intentional. The basic `<Prompt>` is only meant to intercept in-app navigation. In order to prevent navigation to other sessions, you would need to use a `beforeunload` event listener to catch the navigation. Using `beforeunload` to prevent users from leaving your site can be a bit anti-user (no one likes closing popups when they try to leave a site), which I'm guessing is why this behavior is not included by default.

#4372 was an attempt at adding this behavior, but seems to be abandoned. Anyone can always take up the mantle of moving that (or a new PR) forward.

**Comment by darcusfenix** [comment]
@pshrmn beforeunload event works if users want to leave your site., but, my case I want to prevent navigation on my site pressing the browser's back button.

**Comment by LinFeng1997** [comment]
If previous page is inner link, beforeunload is not work,and the page will be rerender.
