### ISSUE TITLE
[Discussion] Usefulness of the Switch

### ISSUE THREAD

**Issue by FredyC** [ReactTraining/react-router#5918]
_This is a kinda spin-off from #5785._

## Current state
Currently, the react-router is built so we can have routes all over the app and don't bother much with static routing configuration. That's definitely great concept, but there is one flaw.

The `Switch` most common use case is to have a fallback route that should be rendered when nothing else matches. Apparently, that doesn't work well with dynamic routing nature. It forces us to **have all routes in a single place again** to try match against all of them till it reaches the fallback one. 

Another issue is in case I simply want to wrap a single Route to another component because there is some additional logic within the route that would clutter whole `Switch`

```jsx
<Switch>
  <TooSmartRoute /> // notice no props here, everything is inside the component
</Switch>
```

Such route is always matched by the `Switch` simply because it's lacking `path` in the props.

## Solution?
Letting Switch to traverse the whole tree of children to find a match is definitely a bad idea.

Honestly, I don't have any proven solution, just a hot idea. It would be something along the lines of having a new component called eg. `Fallback` which would accept prop of the fallback route.

```jsx
<Fallback route={<NotFound />}>
  // ... some deeply nested routing
</Fallback>
```

This component would just render everything without any traversal. When some `Route` would match, it would internally use _context_ to inform `Router` about that. Then the `Fallback` would be able to pick up that information (not sure if that's possible actually) and render fallback route if there wasn't any match.

Any other thoughts/ideas?

**Comment by jmeas** [comment]
I agree that this is a problem. Many apps only need a single NotFound route, conceptually, but when I use RR v4 my apps tend to have many. This is mostly a problem because it’s easy to forget to add it.

I’d love to see a solution, such as ‘Fallback‘, to this.

**Comment by timdorr** [comment]
While you might be able to build something like this now, this will essentially be impossible when async rendering drops in React. Namely because you can never know when the state of all Routes within a tree are fully materialized. Routes can pop in and out of the tree at any moment. And the lifecycle methods to synchronize them (cWM, cWRP) [are going away](https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md). So you'll end up with weird synchronization issues, mostly in the form of trailing content in the DOM while the render loop finishes processing and reconciling.

This is going to be an interesting transition for most apps and libraries, where certain guarantees are no longer possible.

Really the only solution here will be to go back to the old way of doing things via a top-level route configuration, aka react-router-config. That can manage the config internally and stays synchronous within its own lifecycle (async doesn't do any preemption). I'd like to get it out of beta and close out things like #5429 and #4962. It can solve a lot of these problems, but it needs some more superpowers to be truly useful.

**Comment by FredyC** [comment]
Hmm, did not know about such drastic changes coming with React lifecycle.

So let me get this straight. Currently, it's necessary to centralize routing just to have a fallback route? That's almost funny how such a _small_ and relatively boring thing can be so troublesome :/

It almost feels like there would need to be some kind of CLI traversal tool to collect all possible routes from the app code, store list of those and use them in runtime for a Switch to work correctly. Is that insane enough? :D

**Comment by timdorr** [comment]
That's usually how it goes. 😄 

You can't traverse the code because the execution is dynamic. And there is no CLI in the browser, so that would exclude many classes of applications. The library approach of react-router-config is really what you're describing anyways, so that just needs to be leveled up and released as 1.0.0.

**Comment by FredyC** [comment]
To be honest, I am not entirely sure where lies the usefulness of the RRC? I mean how is it better to have routes in a config file that gets transformed to components? It even feels like that having it in code directly "looks better", but that's probably subjective.

Most importantly I am not sure what using that lib solves regarding this issue. It's using Switch internally anyway, so I am failing to see a benefit there :)

**Comment by timdorr** [comment]
It currently uses Switch, but I'd like to refactor it to use `matchRoutes()` instead.

**Comment by timdorr** [comment]
That's particularly necessary to solve things like #5429, which Switch's semantics don't allow for (nor should they).

**Comment by FredyC** [comment]
I think we can close it here. I took a different approach. This is how my main Routing looks like now and I am almost happy about it.

```jsx
<Switch>
  <Route path="/login" component={LoginRoutes} />
  <SecureRoute exact={true} path="/" component={DashboardPage} />
  <SecureRoute path="/order" component={OrderRoutes} />
  <Route component={NotFoundPage} />
</Switch>
```

This way I can still keep a modularized approach with an assumption that each module sits at some specific path. When that path is hit, I can let that module decide on what to do next, otherwise, it can safely fall back to the NotFound route.

```jsx
export const OrderRoutes = ({ match }) => (
  <NestedRoutes
    basePath={match.path}
    render={NestedRoute => (
      <Switch>
        <NestedRoute path="/" component={OrderOverviewPage} />
        <NestedRoute path="/create" component={OrderCreatePage} />
        <Route component={NotFoundPage} />
      </Switch>
    )}
  />
)
```

This even gives me better control as I can have a different NotFound route per a module :)

```tsx
import React from 'react'
import { Route, RouteProps } from 'react-router'

interface INestedRoutesProps {
  basePath: string
  render(Route: React.ComponentType<RouteProps>): ReactNode
}

export const NestedRoutes: React.SFC<INestedRoutesProps> = ({
  basePath,
  render,
}) => {
  const NestedRoute: React.SFC<RouteProps> = ({ path, ...props }) => (
    <Route path={`${basePath}${path}`} {...props} />
  )
  return render(NestedRoute)
}
```

**Comment by gokalina** [comment]
It was announced that React Call Return won't be released. So I've implemented similar pattern as [react-aggregation](https://github.com/gokalina/react-aggregation) library.

Here is [concept](https://codesandbox.io/s/6y7lmlvlrw) of new `Switch` implemented with `react-aggregation`. It allows to nest routes any way you want.

What do you think about this? @FredyC @timdorr @jamesplease
