### ISSUE TITLE
How to disabled the Link and when returning data reenable the Link?

### ISSUE THREAD

**Issue by yzfdjzwl** [ReactTraining/react-router#5937]
I want to do this: 
* `<Link to={{ pathname }}>some things</Link>`
* when I click:
  * event.preventDefault();
  * get some data
  * reenable the Link.

How to achieve it?

**Comment by pshrmn** [comment]
For what you're trying to do, you will need to write an asynchronous link component. You can basically copy the source for the [`<Link>`](https://github.com/ReactTraining/react-router/blob/137a37b0a925a1be50c7f25aa3913dfa3441a391/packages/react-router-dom/modules/Link.js), but edit `handleClick` to not perform the navigation until your async code has finished (either using a Promise or a callback).

```hs
handleClick = e => {
  event.preventDefault();
  this.props.onClick()
    .then(resp => {
      // do something with the loaded data
      // then call history.push
    });
}
```

If you have any more usage questions, please use either StackOverflow or Reactiflux because those are better setup to handle these types of questions. The issues section here is intended for bug reports.

**Comment by yzfdjzwl** [comment]
@pshrmn thanks
