### ISSUE TITLE
react-router-redux reducer: This may not be in sync with the router

### ISSUE THREAD

**Issue by adambene** [ReactTraining/react-router#5999]
react-router-redux reducer

> This may not be in sync with the router...

 https://github.com/ReactTraining/react-router/blob/7001576645b084e68b30332ce2bd91b8f0cdd6fd/packages/react-router-redux/modules/reducer.js#L13

Isn't the point to have the store reflect the router's actual state?

**Comment by timdorr** [comment]
Yes, but it's not possible to have it synchronized at all points. The store and history have very different behavior patterns when you get down to the specifics. It may be possible to rely on this state synchronization in some cases, but there are a lot of edge cases that break it and are fundamentally impossible to fix. 

Just keep that in mind when relying on this library. That's why I generally advise against using it.

**Comment by adambene** [comment]
@timdorr Thanks for your response.

Based on your experience and knowledge, what is the best way not to call routing functions directly, but use some kind of redux-like state machine for navigation in a completely safe and production ready way?

In a large scale app, it is always a hell to verify whether the app works as specified in regards to routing.

But if we code routing completely using some kind of state machine or other formal way, it becomes very easy to verify navigation behaviours, with simple unit tests.
And the desired library, which I am dreaming about could sync the state machine and the native navigation.
