### ISSUE TITLE
history.replace doesn't clear query parameters through refresh

### ISSUE THREAD

**Issue by wldcordeiro** [ReactTraining/react-router#6008]
## Version
4.2.2.

## Steps to reproduce

```js
// Inside a route connected component.
		const { history, location: { pathname, search } } = this.props
		const parsedUrl = url.parse(`${pathname}${search}`, true)
		const {
			// Remove code && session_state from the query object
			/* eslint-disable no-unused-vars */
			query: { code, session_state, response_type, ...qs },
			// Don't want search in the url.format, want to use query instead (see: "url" documentation)
			search: _,
			href,
			path,
			...rest
			/* eslint-enable no-unused-vars */
		} = parsedUrl
		const newUrl = url.format({
			...rest,
			href: url.parse(href).pathname,
			path: url.parse(path).pathname,
			query: qs,
		})
		history.replace(newUrl)
```

## Expected Behavior

Refreshing the browser uses the replaced URL with no query parameters

## Actual Behavior

Refreshing the browser uses the old URL with the query paramethers

**Comment by pshrmn** [comment]
The issues section here is meant for bug reports; usage questions are better suited for StackOverflow/Reactiflux. I'll try to point you in the right direction, though.

I'm not sure what you mean by refresh because `history.replace` doesn't involve any refreshing. The idea with `History.replaceState` (the native API that `history.replace` uses) is that the location is updated without reloading the document. If your above code is running and not updating the URL in the address bar, then something else is going wrong in your app.

I am also not sure why you are using the `url` package if you only need to parse the query params. The following code should do what you expect.

```js
import qs from 'qs'; // or your query string parser of choice

const { history, location } = this.props;
const { code, session_state, response_type, ...rest } = qs.parse(location.search);
const search = qs.stringify(rest);
history.replace({
  ...location,
  search
});
```

**Comment by wldcordeiro** [comment]
> I am also not sure why you are using the url package if you only need to parse the query params. The following code should do what you expect.

I  wasn't aware of another package and `url` came with Node.

> I'm not sure what you mean by refresh 

What I mean is we remove the QS params and then if you trigger a refresh instead of the URL being `the-url.com/path` it's `the-url.com/path?the-qs-param-i-removed=foo` but I thought that by replacing history it should remove the params and therefore refresh to the replaced URL and not the old one.
