### ISSUE TITLE
Documentation website on mobile fails on transitions.

### ISSUE THREAD

**Issue by jaszczw** [ReactTraining/react-router#6023]
The docs page fails to transition on mobile:
1. Enter https://reacttraining.com/react-router/core/
2. Pick any topic
3. Nothing changes

In console

```
Uncaught TypeError: Cannot read property '_debugID' of undefined
    at Object.setValueForStyles (CSSPropertyOperations.js:225)
    at Object.i [as current] (react-dom.js:37)
    at e.r [as _callback] (createAnimatedComponent.js:52)
    at e.update (AnimatedProps.js:76)
    at AnimatedValue.js:58
...
```

The error comes from the [`react-css-property-operations`](https://github.com/meyer-archives/react-css-property-operations) library, which was extracted from `react-dom` and is in an archived state.

Code that calls the failing method.
https://github.com/ReactTraining/react-router/blob/02e6da9a791ac90fac5838e7e4943233af7bf118/website/modules/animated/targets/react-dom.js#L33-L45

**Comment by pshrmn** [comment]
This appears to be an issue with the Animated library, which is used in the [`<EnvironmentSmall`](https://github.com/ReactTraining/react-router/blob/master/website/modules/components/EnvironmentSmall.js) component.

The Animated package was copied directly to the [`website`](https://github.com/ReactTraining/react-router/tree/master/website/modules/animated) instead of being used as a dependency, but I don't know why (I vaguely remember reading a reason before, but I don't recall what it was). [This issue](https://github.com/animatedjs/animated/issues/35) might be related, which implies that the problem has been fixed. Unfortunately, I cannot tell which version of Animated is in the `website` directory.

If someone wants to take a look at what it takes to fix this, it would be appreciated. It probably either requires a) copying updated Animated files or b) just importing the Animated package and removing the copied files (this would be ideal, but I'm not sure why this wasn't done in the first place, so I'm not sure if it will cause issues).

**Comment by mjackson** [comment]
@pshrmn See #6058. I think it may just be an issue with us not setting the correct `NODE_ENV` in the build. That code shouldn't even be trying to access the `_debugID` property in production.

**Comment by pshrmn** [comment]
Hmm, the Webpack config [uses `DefinePlugin`](https://github.com/ReactTraining/react-router/blob/ad53bc84475f2ab8e73a3a6454ed29dc68073497/website/webpack.config.js#L23-L27) and calling `npm run build` sets `process.env.NODE_ENV` to `production`, so that code should be transformed.

**Comment by sag1v** [comment]
Hi, see my [comments](6058#issuecomment-378382801) about this issue. I think it's related to a conflict with react v16

**Comment by mjackson** [comment]
I did some digging in #6058. Let's follow up there.
