### ISSUE TITLE
react-router native documentation is miss-leading/incomplete

### ISSUE THREAD

**Issue by kdong007** [ReactTraining/react-router#6075]
https://reacttraining.com/react-router/native/guides/animation

under "Page Transitions"

here is the code snippet from webpage, 

```
class Parent extends Component {
  render() {
    return (
      <View>
        <Switch>
          <Route path="/settings"/>
          <Route path="/notifications"/>
        </Switch>
      </View>
    )
  }
}
```

> Once that works without animations, we’re ready to add an animation around it.

```
<AnimatedChild
  anim={this.state.anim}
  atParent={this.props.match.isExact}
  animating={this.state.animating}
>
  <Switch location={this.props.location}>
    <Route path="/settings"/>
    <Route path="/notifications"/>
  </Switch>
</AnimatedChild>
```

but where is `this.state.anim`, `this.props.match`, `this.props.location` come from? Should AnimatedChild placed under route/switch? or enchanced by `withRouter`

**Comment by timdorr** [comment]
It's assuming Parent is under a Route or has withRouter on it. It's your choice.

**Comment by kdong007** [comment]
@timdorr then for the component that renders <AnimatedChild> where is `this.state.anim` come from??

**Comment by timdorr** [comment]
That's a local state variable for animation. We don't define it specifically because there are a large number of libraries with very different APIs and implementation. 

This example is to give an idea of how you might hook up something like this, but isn't prescriptive about it. We intentionally want to be ambiguous to allow it to work for many different libraries and implementations.
