### ISSUE TITLE
How to use react React Router with React VR?

### ISSUE THREAD

**Issue by zzc-tongji** [ReactTraining/react-router#6091]
I have seen the article (https://stackoverflow.com/questions/43931122/how-to-use-react-react-router-with-react-vr) and the video (https://twitter.com/ryanflorence/status/808890440929771520) about using React Router with React VR. But I still have some problems to use it.

Is it possible for sharing the code? @ryanflorence .

**Comment by pshrmn** [comment]
@zzc-tongji I just glanced at the video and I see that it was using the RRv4 alpha props, so the old code would need to be adapted to the RRv4 API (`<Match pattern>` -> `<Route path>`, `router.transitionTo()` -> `router.history.push()`).

As far as your specific issues, I'm not actually sure what they are because you didn't specify them, but I would encourage you to check out the [the Reactiflux discord](https://discord.gg/43GVhH). We try to limit the issues section here to actual bugs with the router and I'm not sure any of us have actually used `react-vr`, so we wouldn't be much help. The `#react-vr` room there looks a bit slow, but there are plenty of other channels on Discord that might be able to help, too.
