### ISSUE TITLE
ActiveClass being applied after the component has rendered

### ISSUE THREAD

**Issue by mic4ael** [ReactTraining/react-router#6104]
## Version

4.2.2

## Test Case
https://pastebin.com/DVqFKG3s

## Steps to reproduce
Try to render a big list of elements in one of the components which the router redirect to.

## Expected Behavior
ActiveClass is applied right after I click the `NavLink`

## Actual Behavior
There is a visible delay when it comes to seeing the CSS styles defined for the currently active menu item.

**Comment by timdorr** [comment]
I put your code into a codesandbox here: https://codesandbox.io/s/w64yjy4kp5

I'm seeing it load synchronously:

![apr-23-2018 10-12-59](https://user-images.githubusercontent.com/17882/39132053-ec5a10d0-46de-11e8-82cb-72392ec622c6.gif)

It's delayed, but that's because of the huge list of stuff to mount to the DOM. That's not the router's fault, that's just React and the browser DOM. It takes a while to layout/paint that many divs with relatively complex CSS.
