### ISSUE TITLE
history.goBack() not working with sub routers

### ISSUE THREAD

**Issue by binothman** [ReactTraining/react-router#6131]
I'm trying to use history.goBack() in sub router like `/companies/create`, so when I run goBack() it should return to `/companies` but did't, it return to the pervious router not inside `/companies`

**Comment by pshrmn** [comment]
`goBack()` goes to the previous location. If you navigate to `/companies/create` from `/companies`, then `goBack()` will navigate to `/companies`. If you navigate to `/companies/create` from `/yo`, then `goBack()` will navigate to `/yo`.

If by "sub routers", you mean that you are rendering `<BrowserRouter>`s inside of `<BrowserRouter>`s, that is going to cause problems because they won't share the same history instance. You shouldn't have to render multiple routers, but if you do, you should create your own `history` instance and pass it to the generic `<Router>` (i.e. `<Router history={history}>`).
