### ISSUE TITLE
location.pathname had different value on different situation. 

### ISSUE THREAD

**Issue by rockmandash** [ReactTraining/react-router#6135]
if I have a route called '/about'
location.pathname should be '/about'
However, if you have basename, and inside your dist folder, you clone index.html to folder 'about', and you directly go to url /about, then console.log location.pathname will be '/about/', but if you navigate to other route and navigate back, the location.pathname will back to normal which is '/about'

**Comment by pshrmn** [comment]
On a server that is serving static files, a request for `/about` looks for a file called `about` while a request for `/about/` means the index file in the `about/` directory. If the server gets a request for `/about` but no `about` file exists, it might check to see if an `about/` director with an index file exists, and if it does, it will return a redirect response. This is why when you try to navigate directly to `/about` you are being redirected to `/about/`.

Once your app is running, then it really doesn't matter what a URL looks like because the app doesn't need to match a resource that exists on the server.

**Comment by rockmandash** [comment]
Thank you for your explanation!
