### ISSUE TITLE
URL updating but component won't re-render / withRouter not working

### ISSUE THREAD

**Issue by Jahans3** [ReactTraining/react-router#6156]
I've searched nearly every related issue and none of the work arounds are working. I have tried `withRouter`, setting `connect` to `{ pure: false }`, manually passing `location` as a prop, and read all of the [blocked updates page](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md).

The closest I can get is when using `pure: false`, but then the update only triggers when the next action is fired and not when the `NavLink` is clicked.

I have a large `connect` HOC that I reuse for a few sibling components, there are no other `connect`s in any of the parents.

The `withRouter` is in the correct order: `withRouter(connect(mapState)(Component))`.

In the different things I've tried:

1. Simply wrapping with `withRouter` causes the initial route to disappear and nothing else renders in its place. Refreshing the page with the updated URL causes the correct component to be rendered, so paths must be correct.

2. `{ pure: false }` causes a huge drop in performance and the updated location is only passed to the `Route` when another action is fired anyway.

3. Using `withRouter` AND `{ pure: false }` has the same effect as above

4. Manually passing `location` from a `Route` with no path has no effect.

Is there something I've missed? Feel like I'm trying to bleed a rock here

**Comment by timdorr** [comment]
This is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

**Comment by Jahans3** [comment]
@timdorr Thanks for the quick response but this sure seems like a bug. I definitely submitted this with the intent of it being filed as a bug and looking through the issue history it seems to be a recurring problem - plus none of the suggested work arounds have the desired effect.

At the very least, I feel like there should be a discussion around how to make this library work better with React Redux. Using `withRouter` everywhere seems unintuitive and clunky, setting `{ pure: false }` on `connect` is just plain bad practise (in a quick test here, I went from 2 re-renders on start up to 14, just to give an idea of how bad it is for perf).

Could we re-open this please?

**Comment by omriBernstein** [comment]
@Jahans3 I just had a similar problem and realized the "render blocking" was upstream of the component I cared about. To fix it I found the "ancestor" `connect`ed component and `withRouter`ed it.

The problematic code could be something like:

```jsx
...
const ChildStateless = ({location}) => (
  <div>do something with {location.pathname} or whatever router props we care about</div>
);
...
const Child = withRouter(connect(mapState, mapDispatch)(ChildStateless));
...
const ParentStateless = (
  <div>
    <div>...whatever...</div>
    <ChildContainer />
  </div>
);
...
const ParentContainer = connect(mapState, mapDispatch)(ParentStateless);
...
```

(Note: I've omitted the definition of variables above—for example `mapState` and `mapDispatch`—that were not pertinent to the example I'm trying to show. Oh and I've used `...` to signify missing code and to colocate code that would normally exist across many different files.)

And the solution is to `withRouter` the `ParentContainer` as well (diff below):

```diff
+ const ParentContainer = withRouter(connect(mapState, mapDispatch)(ParentStateless));
- const ParentContainer = connect(mapState, mapDispatch)(ParentStateless);
```

And I'm pretty sure it doesn't matter whether the "child" is truly a direct child of the "parent" component. Really the parent can be any `connect`ed upstream ancestor. I'm also pretty confident that we could do the `{pure: false}` or `Route`-with-no-path on the upstream ancestor and it'd work just as well.

This fix definitely doesn't seem ideal—from not only a performance perspective but also a maintainability perspective. `withRouter`ing a `connect`ed component not because it directly needs to re-render but because some deep ancestor will need to re-render feels like a hairy mental dependency.

I'm thinking I might switch to using [`react-router-redux`](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) which I'm imagining will allow me to just use `connect` everywhere and (probably) not have to worry about `withRouter` ever again.

Which also seems like a decent reason to consider this behavior a "non bug" (not that I'm not a contributor or collaborator here). As in, I could get behind the argument that this problem shouldn't be solved in `react-router` because it doesn't involve `react-router` at its core, but rather its interaction with other libraries / tools.

That being said I'd love it if `withRouter` could be configured to "aggressively" re-render. It could be opt-in so as not to break any existing code and it feels right that whether or not `withRouter` re-renders based on changes to `history` / `location` / `match` is a decision for the `react-router` library consumer. Maybe I'll take a crack at it, or if somebody reads this and realizes I'm rehashing an already-rejected idea, please let me know :)
