### ISSUE TITLE
NavLink for native

### ISSUE THREAD

**Issue by WillSquire** [ReactTraining/react-router#6157]
Looking in the source files I can't find anything for NavLink react-router-native. Is this going to be added?

Thanks

**Comment by timdorr** [comment]
No, because RN components don't have a className, which is the main reason for having NavLink. 

It's just [a Route wrapping a Link](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js), so you can implement it in your code based on whatever you define "active" as in your app.

**Comment by WillSquire** [comment]
True. Although if NavLink accepted callbacks such as `onActive` and `onInactive` instead of `className` then it would flexible enough to be used on multiple platforms?
