### ISSUE TITLE
Allow period, full stop, dot, within urls

### ISSUE THREAD

**Issue by TashaRolland92** [ReactTraining/react-router#6184]
## Version

react-router: Version 4.2.0
types/react-router: Version 4.0.26

## Steps to reproduce
Since updating React-Router to the latest version I am still having the same problem...
Adding the below code to my routes.tsx file
`<Redirect exact={false} from='/original-page.aspx' to='/original-page' />`

## Expected Behavior
Page should simply redirect

## Actual Behavior
React breaks behaviour when it finds the period within the URL

**Comment by TashaRolland92** [comment]
@mjackson I have updated my react-router version but had no luck :( 
Am I being a complete and utter noob or is this a known issue? I don't understand how something so simple is just not working lol

**Comment by timdorr** [comment]
Here is how you should be using it: https://codesandbox.io/s/2z530z285y

**Comment by TashaRolland92** [comment]
Thanks @timdorr that's all well and good but I won't have anything of the sort within my solution:
<Link to="/about.aspx">Redirect</Link>
So how would I overcome this?

**Comment by TashaRolland92** [comment]
Thanks @timdorr but my /original-page.aspx could only be accessed outside of my solution so I wouldn't be able to include `<Link to="/original-page.aspx">Redirect</Link>` as I am adding this to cover old urls that users could still come across.... @mjackson

**Comment by timdorr** [comment]
This is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

**Comment by TashaRolland92** [comment]
So just to clarify you can't help me out? @timdorr

**Comment by TashaRolland92** [comment]
It would be nice if you just said you didn't know rather than just ignore me manner cost nothing! @timdorr

**Comment by timdorr** [comment]
I can't help because you haven't provided a reproducible test case. You need to post more substantial parts of your code, otherwise we can't see what's actually going on. Codesandbox.io is the best way to do this, as the code can actually be run and collaboratively edited.

But again, this isn't a support system. Only a handful of people are going to see your issue here. There are _way_ more eyeballs on sites like StackOverflow and Reactiflux. But they will ask for more context as well, just to warn you.
