### ISSUE TITLE
Documentation links missing /react-router from path

### ISSUE THREAD

**Issue by cxcorp** [ReactTraining/react-router#6265]
Links in the API documentation are missing `/react-router` from the path, meaning that attempting to open those links in a new tab will simply redirect to the home page.

Example: go to [https://reacttraining.com/react-router/web/api/Route/route-props](https://reacttraining.com/react-router/web/api/Route/route-props).
If you look at the links, you'll notice that they look like the following:

- https://reacttraining.com/web/api/match
- https://reacttraining.com/web/api/location
- https://reacttraining.com/web/api/history

whereas they should be

- https://reacttraining.com/react-router/web/api/match
- https://reacttraining.com/react-router/web/api/location
- https://reacttraining.com/react-router/web/api/history

**Comment by intrepidOlivia** [comment]
I'm not certain, but it looks like it's in [this markdown-loader.js](https://github.com/ReactTraining/react-router/blob/master/website/webpack/markdown-loader.js) file that the link format needs to be fixed? I'm not sure I'm familiar enough with the syntax though to know how exactly to change it.

**Comment by mjackson** [comment]
This is kind of a tricky problem. The only links that are broken are the ones we get from markdown files, and only when you try to right-click and open them in a new tab. These links are not created by React Router (i.e. `<Link>`s), so they never get the `basename` that [we currently pass to the `<BrowserRouter>`](https://github.com/ReactTraining/react-router/blob/34ff1f8077d95edf01e9d5ca8ea4708b8d0290e2/website/modules/components/App.js#L18) because their `href` is not generated using `history.createHref` like `<Link>`s are. In fact, the only way these links work at all is because we [delegate all clicks on them](https://github.com/ReactTraining/react-router/blob/34ff1f8077d95edf01e9d5ca8ea4708b8d0290e2/website/modules/components/DelegateMarkdownLinks.js) through a global `history.push` handler.

So in order to fix this we would need to (I think) do 2 things:
1. Add the leading `/react-router` to all markdown links in [the markdown loader](https://github.com/ReactTraining/react-router/blob/master/website/webpack/markdown-loader.js) when we're building for production and
2. Strip that prefix before the `history.push` happens inside `<DelegateMarkdownLinks>`, otherwise it'll be added twice
