### ISSUE TITLE
Refreshing a page with a route that has Portals leads to an Invariant Violation exception

### ISSUE THREAD

**Issue by henkvhest** [ReactTraining/react-router#6309]
## Version

4.3.1

## Test Case
https://codesandbox.io/s/82zwpzjr80

## Steps to reproduce

In the codesandbox example, if you route from /home to /about via the links, then it's all fine. However, if you are on the about page and then do a refresh, then you get the following exception:
```
Invariant Violation
Target container is not a DOM element.
```
I would imagine that portalling to a DOM node that's a route that's not rendered would not be possible, but the div that's being portalled to in this case is outside of the router.

## Expected Behavior

I expect to be able to use Portals to DOM nodes outside of the route where I use a portalled component in.
## Actual Behavior

Refreshing the page leads to an error

**Comment by pshrmn** [comment]
This isn't a React Router issue. You're attempting to select an element in the DOM that does not exist.

Your provided code works when navigating from home to about because the element is rendered into the DOM at that point.

You should either a. add an element outside of your React tree to create the portal to or b. create a new element like they do in the [portals guide](https://reactjs.org/docs/portals.html).

```html
<!-- a -->
<div id="root"></div>
<div id="divToUsePortalOn"></div>
```
```jsx
// b
class BottomBar extends React.Component {
  constructor(props) {
    super(props);
    this.el = document.createElement("div");
  }
  render() {
    return ReactDOM.createPortal(<Thing />, this.el);
  }
}
```
If you have any other support issues, please use StackOverflow or Reactiflux. The issues section here is intended for bug reports, while those venues are setup for helping people with implementation problems. Thanks!
