### ISSUE TITLE
Add `react-router` as a peerDependency, instead of as a dependency.

### ISSUE THREAD

**Issue by gustavovnicius** [ReactTraining/react-router#6338]
## Version

latest

## Steps to reproduce
- Add `react-router-dom` as dependency
- Add `connected-react-router` as dependency
- See warning about `react-router` being a peer dependency of `connected-react-router`

## Expected Behavior
- Add `react-router-dom` as dependency
- See warning about `react-router` being a peer dependency of `connected-react-router`

IMO, it should follow (React -> ReactDom)'s pattern: https://github.com/facebook/react/blob/master/packages/react-dom/package.json#L22

## Some more info
https://github.com/supasate/connected-react-router/issues/92

**Comment by pshrmn** [comment]
[Peer dependencies](https://docs.npmjs.com/files/package.json#peerdependencies) are for packages that are expected to be installed, but are not imported by the package declaring the dependency (an implicit relationship).

`react-router-dom` has an explicit dependency on `react-router` because it re-exports `react-router`'s exports. If it was a peer dependency, then someone using `react-router-dom` would have to explicitly install `react-router`, which is not desirable.
