### ISSUE TITLE
Remove react-router-redux package

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-router#6358]
I'd like to remove the react-router-redux package from this repo since we aren't planning on maintaining it anymore. A few options:

1. Move the code back to reactjs/react-router-redux
2. Move the code into a new read-only repo at ReactTraining/react-router-redux
3. Move the code into reduxjs/react-router-redux
4. Move the code under @timdorr's personal GitHub

I personally feel that option 2 is probably the best since I don't want to clutter up the reactjs or reduxjs orgs with our old, deprecated code. But I'd be fine with any of the options. I just want the code out of this repo so it doesn't run when we run tests.

Of course, wherever the code lives we should link to it from our README and let people know where it is.

What do you think @timdorr ?

**Comment by pshrmn** [comment]
Does it need to live under some repo's `master` branch or can links just be pointed to an old commit?

**Comment by mjackson** [comment]
Ah, that's not a bad idea @pshrmn. Might make it tricky to find, but ya, we could just link to it.

Another option would be to take the existing reactjs/react-router-redux repo and move it here, keep it archived, and then just push the code in one big commit. That way links to the old repo would redirect automatically and we wouldn't be polluting the reactjs org with old, stale code. I'd like to keep it as clean as possible over there.

**Comment by timdorr** [comment]
Because of the version offset (RRR 4.0 is for Router 2/3, RRR 5 is for Router 4), I kept the old @reactjs repo around. Pointing folks to a tag or SHA has proven to be rather error prone and there is much weeping and gnashing of teeth when someone can't find the thing they're looking for _right now, dammit_.

That being said, I don't think it's as big of a deal now that RRR's been deprecated for a while and I've been discouraging its use for over a year. So, just nuking it from the repo and pointing to the last available tree SHA/tag would be fine by me.
