### ISSUE TITLE
`Route` components don't have their constructors called when props are updated

### ISSUE THREAD

**Issue by garyking** [ReactTraining/react-router#6392]
## Version

4.3.1

## Test Case

https://codesandbox.io/s/00zomy7xj0

## Steps to reproduce

Create a `Route` component that gets props from the component containing `BrowserRouter`, from the state from `componentDidMount`.

## Expected Behavior

After `componentDidMount` runs, the props passed to the child component should also call the `constructor`.

## Actual Behavior

The constructor is not called.

**Comment by mjackson** [comment]
The `constructor` of a component is called only when it is first created, not after subsequent updates. Please see [the docs about the React lifecycle for further info](https://reactjs.org/docs/react-component.html#constructor).

In your case, your example works if you just read from `this.props.items` in your render method instead of `this.items`, which is stale on the 2nd render. A [fixed version is here](https://codesandbox.io/s/r4omnlwyy4).

**Comment by garyking** [comment]
Yep I know I can get `this.props.items` directly, but I have other logic in the constructor in my actual app, which would modify it. I'm setting `state` from the constructor, and so I can't put `setState` in `render` otherwise it results in an infinite loop.

I thought there would at least be a way to force the constructor to run again, perhaps?
