### ISSUE TITLE
Invalid prop `path` of type `regexp` supplied to `Route`, expected `string`

### ISSUE THREAD

**Issue by Fi1osof** [ReactTraining/react-router#6418]
## Version

PropTypes require String or [String] for Route, but Route allow use regex too.

## Test Case
https://codesandbox.io/s/yv2z0x7qo1 (See route for topics).
 
## Expected Behavior
No warnings.
Allow types: String, RegExp, [String, RegExp]

## Actual Behavior
Warning: Failed prop type: Invalid prop `path` of type `regexp` supplied to `Route`, expected `string`.
    in Route

react-router-dom@4.3.1

**Comment by timdorr** [comment]
Regex isn't allowed in the path. We [cache our generated regexps](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/generatePath.js#L13), so this would break that.

**Comment by Fi1osof** [comment]
@timdorr, so this is undocumented features. And it should be allowed. Because it works. Have a look: https://codesandbox.io/s/yv2z0x7qo1
I switch URLs /topics/topic-234.html and /topics/topic-CharID.html and got 234 and CharID in separated components. Switch component uses regexp https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/matchPath.js#L42

**Comment by pshrmn** [comment]
It may technically work, but it shouldn't be encouraged.

`path-to-regexp` (what React Router uses for path matching) supports [custom match parameters](https://github.com/pillarjs/path-to-regexp#custom-matching-parameters) if you want to only match specific content in a segment.

Using a RegExp path can also cause issues. What happens if you want to nest a route as a child of a route whose path is a RegExp? With strings you can grab `match.path` and concatenate, but there is no simple way to join regular expressions.

**Comment by Fi1osof** [comment]
@pshrmn, thank you for the clarification. OK.

**Comment by kevich** [comment]
I think technically there is no problem to convert RegExp to strings on react-router level, so that it will behave pretty the same as now.
But for what it's really needed to be supported as RegExp by react-router is because of this issue in pillarjs/path-to-regexp#99. And for now there is no other way to use `(?!something)` than using it as RegExp
