### ISSUE TITLE
`react-router@4.4.0-beta.4` is missing dependency `prop-types`

### ISSUE THREAD

**Issue by mgroenhoff** [ReactTraining/react-router#6438]
`react-router@4.4.0-beta.4` is missing dependency `prop-types`

**Comment by timdorr** [comment]
Looks like it got removed in bff4af58fe9aa27dde023adb81e45b38142cb0b2.

**Comment by mgroenhoff** [comment]
Looks like it is still used here
https://github.com/ReactTraining/react-router/blob/8ecdbd9727cbffe34c41cfe595e67cae2b7ce62f/packages/react-router/modules/Route.js#L3

**Comment by mjackson** [comment]
I think it was removed in 6615b9e7bc7aaaf3878252b2aeda652cae9c1a22 when @TrySound moved everything in `node_modules` (our deps) out of our bundles. We still need it in our builds, but it should be tree-shaken out of production builds because all our usage of `PropTypes` is behind the `__DEV__` flag. I will double check.

@mgroenhoff I'm curious, which build are you using?

**Comment by TrySound** [comment]
Well imports cannot be treeshaken. So `prop-types` package should always be in deps if you use it.

**Comment by mgroenhoff** [comment]
I am building a bundle using Webpack and it imports `esm/react-router-dom.js` which has the import statement in the top of the file. Webpack fails to find this module so it errors.

**Comment by timdorr** [comment]
Yep, Rollup can tree shake/DCE the initial import statement, but Webpack cannot. That would happen with terser/ugilfy/babel-minify as a DCE step.

**Comment by mjackson** [comment]
Just published the fix in 4.4.0-beta.6
