### ISSUE TITLE
Documentation website does not match current stable version

### ISSUE THREAD

**Issue by mattdarveniza** [ReactTraining/react-router#6500]
I noticed that the documentation website seems to be pointing at features for the `@next` version rather than current stable. This bit me pretty hard recently when I was relying on array support in `path`, something that is only available in 4.4-beta, but documented on the website.

Should the website reflect what is on the latest stable release, or at the very least list what version the documentation relates to if it's going to be documenting beta-version features?

**Comment by mattdarveniza** [comment]
They work in some cases but the behaviour isn't officially supported in 4.3, which is why the proptypes didn't allow it until #5889 which is available on 4.4-beta

**Comment by am-a** [comment]
Just ran into this issue - was very confused - Please have either versioned docs or have public API docs match stable

**Comment by Grantlyk** [comment]
I just double checked in order to fix this but I cannot see anything being documented on the website that isn't available?

The public API docs do match stable.
If we look at #5889 you can see that the changes to the documentation made in that PR aren't what's being shown on the website

So has this been resolved already?

**Comment by mattdarveniza** [comment]
Yeah those changes in that PR aren't on the website anymore. It seems someone's reverted the site back to stable. Thanks for taking a look though!
