### ISSUE TITLE
You are attempting to use a basename on a page whose URL path does not begin with the basename.

### ISSUE THREAD

**Issue by jasonxia23** [ReactTraining/react-router#6516]
## Version

react-router-dom: 4.3.1

## Test Case

https://codesandbox.io/s/j07j85q99

## Steps to reproduce

Open [https://j07j85q99.codesandbox.io/?with-search#/about](https://j07j85q99.codesandbox.io/?with-search#/about)

## Expected Behavior

Router still works.

## Actual Behavior

Router failed. Error throw out

```text
You are attempting to use a basename on a page whose URL path does not begin with the basename.
```

**Comment by pshrmn** [comment]
This really isn't how the `basename` is supposed to be used. The `basename` is for applications whose root is not the domain's root. (`examples.com/app` instead of `example.com`).

The specific reason that you are getting the warning is that the question mark in the basename is not escaped (`?` not `\\?`) so when it is used to create a regular expression, it is used as the "non-greedy" symbol.

If you want to use the hash segment of the URL for locations, you should use the [`<HashRouter>`](https://reacttraining.com/react-router/web/api/HashRouter).

**Comment by jasonxia23** [comment]
But `HashRouter` does not support state. So can you just use `startsWith` other than `new RegExp` to test `basename`.
Thanks for you reply anyway.
