### ISSUE TITLE
Error after upgrade 4.4.0

### ISSUE THREAD

**Issue by alex-mm** [ReactTraining/react-router#6631]
![image](https://user-images.githubusercontent.com/3302053/54472413-1f600900-4803-11e9-8c0f-c94919ce8bf8.png)

![image](https://user-images.githubusercontent.com/3302053/54472411-0f482980-4803-11e9-8fde-8e222779d649.png)

**Comment by chenjf5** [comment]
ADD ERROR:
react-router-dom.js:239 Uncaught TypeError: Cannot read property 'exact' of undefined
    at Module../node_modules/_react-router-dom@4.4.0@react-router-dom/esm/react-router-dom.js (react-router-dom.js:239)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object../app/view/entry/root.dev.js (root.dev.js:6)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object../app/view/entry/root.js (root.js:4)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object.<anonymous> (home.js:10)

**Comment by mjackson** [comment]
What browser are you using? Sounds like it has a bug.

In [the CommonJS build](https://unpkg.com/react-router@4.4.0/cjs/react-router.js) of `react-router` 4.4.0, the `__esModule` property of the `exports` object is defined as follows:

```js
Object.defineProperty(exports, '__esModule', { value: true });
```

In this situation, the `enumerable` accessor descriptor defaults to `false`, which means that it should not be returned by `Object.keys`. However, in your browser it is.

In Chrome 72, I get the following behavior:

<img width="432" alt="Screen Shot 2019-03-17 at 10 52 53 PM" src="https://user-images.githubusercontent.com/92839/54509652-7e0eab00-4907-11e9-9865-d39885340bdc.png">

Since `__esModule` is not `enumerable`, it isn't included in the array returned by `Object.keys`.

**Comment by alex-mm** [comment]
It doesn't matter with the browser version.
It should be related to the react-router version.
Can you filter out '__esModule' ? @mjackson

**Comment by timdorr** [comment]
Both of these lines aren't code we wrote. The `defineProperty` line comes from Babel, and the `Object.keys` line comes from Rollup. They are new in this version because we have changed the build process. However, the error you're seeing with them is dependent on the browser version you're running. So, what browser are you running at what version?

**Comment by alex-mm** [comment]
alright.
Google Chrome 72.0.3626.121.

I think it is caused by our low react-router version. But 4.3.x is ok.

 if you can't fix it, we can only lock the version. @timdorr

**Comment by timdorr** [comment]
That's the issue. You're mixing versions of react-router and react-router-dom. Those have to be the exact same version.
