### ISSUE TITLE
Prompt doesn't work if "message" function is async

### ISSUE THREAD

**Issue by PetrivskyiTaras** [ReactTraining/react-router#6669]
Hi, I use react-router-dom v4.2.2

Prompt takes an argument "message" and it can be a function but if this function is async it doesn't work. Why? Some times it is very useful.

Are you plan to add this possibility?

I need it for data validation with a request to the backend. If validation is successful I can allow the transition from the current page.

Thanks for your contribution!

![Prompt](https://user-images.githubusercontent.com/34395038/55084373-bf444f00-50ad-11e9-81f4-88743c3c2646.jpg)

**Comment by timdorr** [comment]
Because we need to respond synchronously to block the transition. We can't delay it for an async request to resolve. Also, this will lead to a bad UX, as there would be nothing presented to the user to represent progress or a loading state while the request resolves. It would be better to block this earlier in the lifecycle, before you navigate.

**Comment by PetrivskyiTaras** [comment]
Tim, thanks for the clear answer! 
Try to found another solution.
