### ISSUE TITLE
Router is not rendering in react-router-dom v5.0.0

### ISSUE THREAD

**Issue by KosKou** [ReactTraining/react-router#6693]
## Version

**I'm using react-router-dom v5.0.0**

## Test Case

https://codesandbox.io/s/31vx2njxn1

## Steps to reproduce

Go to password field and write: **dummy**

## Expected Behavior

Render the HeaderComponent to update the links that must appear into the nav bar after user logged in.

## Actual Behavior

The actual version (5.0.0) is not re-rendering the component after the user has logged in, the system must valid the boolean value called isUserLoggedIn that is defined in AuthenticationService.js, that value gets the item saved into the sessionStorage.

The LoginComponent has a simple method called loginClicked() where validates the username and password and ref to /welcome/username using this.props.history.push() that changes the url and page but does not update the nav bar where validates which links are going to be displayed.

This issue does not appear in react-router-dom 4.3.1.

Is there another way to set my components and methods to re-render the nav bar?

**Comment by timdorr** [comment]
This is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

**Comment by StringEpsilon** [comment]
There is a change in re-rendering behavior due to the new context API. The old context-API caused all children to rerender when the providing component rerendered. That behavior change is something I think we should note in the 5.0 release notes. But it's not a bug - it's simply the default behavior of React.

Here is a codesandbox demonstrating the change:

https://codesandbox.io/s/q3pnj9k1n9 

Check the console. A renders once, B renders twice.

**Comment by KosKou** [comment]
Thanks for the quick response! i have solved it by adding withRouter() to HeaderComponent
