### ISSUE TITLE
react-router-dom should peer-depend on react-router

### ISSUE THREAD

**Issue by arcanis** [ReactTraining/react-router#6724]
## Version

5.0.0

## Actual Behavior

The `react-router-dom` package has a hard dependency on `react-router`. That's problematic with projects like `@ionic/react` which peer-depend on `react-router`, not `react-router-dom` (which sounds reasonable, but I'm not super knowledgeable?).

Because it's a regular dependency, the `react-router` instance used by `react-router-dom` might not be resolved to the version as the rest of the application. Worse, since `react-router` declares a peer dependency on `react` it means it MUST be instantiated once for each of its dependents ([explanations here](https://yarnpkg.github.io/berry/advanced/peer-dependencies)). This makes `react-router-dom` incompatible with PnP out of the box (because the React context key is different for each instance), and is silently unsafe in every other package manager.

## Suggested Fix

Move `react-router` as a peer dependency of `react-router-dom`; this is functionally and semantically better as the intent is to enforce a single `react-router` version in the whole dependency tree.

That unfortunately might require a major bump ...

**Comment by StringEpsilon** [comment]
That explains why so many people (still) have issues with inexplicable invariant violations, despite seemingly no wrongdoing. 

But does moving `react-router` to peerDependencies remove all possibilities of duplicate packages for the foreseeable future? Like if the user specifies `5.0.0` but a used library specifies `^5.0.1` or something. I've been trying to figure out how one could eliminate the duplicate-context-issue altogether, but hadn't had any good ideas.

**Comment by pshrmn** [comment]
A peer dependency means that the user has to explicitly install both `react-router` and `react-router-dom`. The `react-router` package should essentially be invisible to the user; it is installed automatically when the user installs `react-router-dom` and provides some core components/functions, but everything that the user does is via exports from the `react-router-dom` package.

I believe that there were some issues (and part of why we had to bump to v5) because previous versions used caret dependencies and there were internal API conflicts if the `react-router-dom` and `react-router` versions were mismatched. Starting with v5, `react-router-dom` pins its `react-router` dependency to its exact same version, which should get rid of those issues.

The only time that a package should specifically depend on `react-router` is if it is providing cross renderer (DOM & Native) components.

**Comment by B-Reif** [comment]
I just spent a while trying to solve an invariant violation related to this issue. I'm sure others could benefit from at least clearer errors in the case of a version mismatch.

**Comment by mjackson** [comment]
Why does `@ionic/react` peer-depend on `react-router` instead of `react-router-dom`?

**Comment by timdorr** [comment]
It doesn't: https://github.com/ionic-team/ionic/blob/master/react/package.json#L45-L46

When the peerDeps were added, rr and rrd were included: ionic-team/ionic#16849
