### ISSUE TITLE
React Route with 2 optional params not matching a simple URL

### ISSUE THREAD

**Issue by arunkandregula** [ReactTraining/react-router#6730]
## Version
"react-router-dom": "5.0.0"

## Test Case
https://jsfiddle.net/arun7it/27yupc3k/1

## Steps to reproduce
Click "Contact With Slash" and "Contact Without Slash" Menu Items.
https://jsfiddle.net/arun7it/27yupc3k/1
You ll see the discrepancy in spite of the params name and age being optional.

## Expected Behavior
Both the following URLs should match the following route.
`http://localhost:3001/contact`
`http://localhost:3001/contact/`

Route I am referring to 
` <Route path="/contact/:name([A-Za-z]+)?:age(\d{2})?" component={Contact} />`

## Actual Behavior
`http://localhost:3001/contact`  --> NOT matching the route
`http://localhost:3001/contact/`  --> matching the route

Route I am referring to 
` <Route path="/contact/:name([A-Za-z]+)?:age(\d{2})?" component={Contact} />`

**Comment by timdorr** [comment]
This is caused by [the underlying path-to-regexp library](https://github.com/pillarjs/path-to-regexp/tree/v1.7.0) that we use. Optional parameters are designed to include a slash prefix so that they can be ignore. Repeated optional parameters without a prefix aren't supported. This will work if you change your path to `/contact/:name([A-Za-z]+)?/:age(\d{2})?`
