### ISSUE TITLE
Rendering a Link in a Router with ReactDOM.render() yields "You should not use <Link> outside a <Router>"

### ISSUE THREAD

**Issue by TimMcCauley** [ReactTraining/react-router#6751]
I am looking for a possibility to add a `Link` within a popup dynamically. If I render it in the component class directly it works fine, however if it is rendered with `ReactDOM.render` it yields `You should not use <Link> outside a <Router>`.

## Version

4.3.1

## Test Case

https://codepen.io/TimMcCauley/pen/xNLzZm

## Steps to reproduce
Using `<LinkToRender/>` works fine, however adding

```
ReactDOM.render(
      <LinkToRender/>,
      document.querySelector('#link-render-div')
    )[0]
```

to `componentDidMount` does not work (you will see this in the codepen)

## Expected Behavior

I am expecting to somehow to render a Link dynamically which will be reflected in the Router.

## Actual Behavior

An error is raised as react-router thinks the Link is not part of the Router anymore once rendered.

**Comment by StringEpsilon** [comment]
The warning is thrown because your `<Link>` can't communicate to it's parent Router. If you want just a normal link that can work outside the Router, you should use an `a` tag.

If you render something via `ReactDOM.render()`, it's not part of the overall component tree and thus get's excluded from both the old and new context API. As a result, the RR components can't find their `Router` and the warning is thrown.

You could also try using a react portal.

See  https://stackoverflow.com/a/46435051 and

**Comment by timdorr** [comment]
I would also recommend a portal. Creating a new React tree from another component isn't the correct way to do that kind of thing.

**Comment by TimMcCauley** [comment]
Thank you, it worked perfectly fine using a portal, an example can be found here: https://codepen.io/TimMcCauley/pen/xNLzZm
