### ISSUE TITLE
Issues with Cloudflare

### ISSUE THREAD

**Issue by kalinchernev** [ReactTraining/react-router#6752]
Hi, that's a very simple issue: it's related to the documentation pages not being reachable.
Since last night, I've been trying to open https://reacttraining.com/react-router/web and still can't.
I've been trying to open the site from different internet providers and locations, but it doesnt help.

Issue code: `Error 522 Ray ID: 4da47899e918d24c • 2019-05-21 06:25:36 UTC`

Here's a screenshot of the problem:

![reacttraining com   522  Connection timed out](https://user-images.githubusercontent.com/1923476/58073631-c66a7380-7bab-11e9-9cc7-b1cfdf58b0d0.png)

I've Google-ed searching for a way to solve this, but I can't find a way, do you have any suggestions?

**Comment by pshrmn** [comment]
Are you still having the issue? The site is currently working for me.

The documentation also exists within the repo (e.g. https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom/docs/api). It can be a little confusing to navigate because it is laid out per-package, but at least that is a fallback.

**Comment by kalinchernev** [comment]
@pshrmn thanks for the suggestion on reaching the documentation in an alternative way!
The issue with Cloudflare is still on. Closing the issue though, as I have a solution to my issue.
Thanks!
