### ISSUE TITLE
NavLink and Link components (v 5+) does not work as 'a' tag if target="_self" prop is set.  It worked in 4.3.1 and lower versions

### ISSUE THREAD

**Issue by YavorskyiBohdan** [ReactTraining/react-router#6765]
## Version

5.0.1

## Test Case

https://codesandbox.io/s/react-router-mswz5

## Steps to reproduce
Add target="_self" property to either NavLink or Link components. Clicking
## Expected Behavior
Clicking on Link tag with target="_self" should work as it was in lower versions. It has to redirect user with page reload.
## Actual Behavior
Redirect works without page reload (as default behaviour without target="_self")

**Comment by MeiKatz** [comment]
I am not sure about this about but.. for me it works.

**Comment by StringEpsilon** [comment]
Works for me too in that sandbox. FF 67.0.1

**Comment by StringEpsilon** [comment]
Seems that this change was deliberate:

**Comment by timdorr** [comment]
Yes, this is the correct behavior. 

This was changed in #6138 as requested in #3109. We want explicitly self-targeted Links to be handled by the browser. This is to give an opt-out for Links taking over navigation via a simple prop change, rather than changing between a Link and `<a>` element. It cuts down on a lot of boilerplate code.
