### ISSUE TITLE
<Link to=""/> and <Link to={{pathname: ""}}/> behave differently

### ISSUE THREAD

**Issue by danielberndt** [ReactTraining/react-router#6779]
## Version

5.0.1

## Test Case

https://codesandbox.io/s/react-router-2eyzx

## Steps to reproduce

In the test case go to the "About" page and click on "Root 1" linking `to=""`. This works as expected. (although I would have preferred it to go to `https://2eyzx.codesandbox.io` instead of `https://2eyzx.codesandbox.io/`)

If you go to "About" and then click on "Root 2" linking `to={{ pathname: "" }}`,  it stays on the about page. Interestingly both links get rendered as `<a href="/">` in the dom.

**Comment by StringEpsilon** [comment]
`{ pathname: "/" }`  works.

I'm not exactly sure whether or not this counts as a bug. There are other scenarios where a location object is treated different from a path as as string. 

Either way, I'd file this bug for history. We can add a workaround here, but this should better be fixed there, if it's considered a bug.

**Comment by timdorr** [comment]
This is where it happens: https://github.com/ReactTraining/history/blob/763fc13bc8a52aff91d9594a7c1d944faa97961a/modules/PathUtils.js#L25

It's expected behavior for the library. A string location can't actually be an empty string. It's assumed that is meant to represent the root path. 

Here's the issue where the change was requested for history 4.x: ReactTraining/history#368

I would do as @StringEpsilon suggests and open an issue on the history repo. If it needs to be changed, it should be done at the source.
