### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by ivosabev** [ReactTraining/react-router#6797]
I am sorry I post this here. it is not a direct issue with the code, but although it is related to accessing the documentation.

I am not sure how you have your CloudFlare configured, but it is impossible to open the https://reacttraining.com/ including any other links on this domain (documentation, blog, etc.) from Bulgaria. This has been happening for the past few months and it is very hard to use react-router without access to the proper documentation and only looking at the repo files.

```
Error 522 Ray ID: 4e8db5fe5988d23c • 2019-06-18 13:47:13 UTC
Connection timed out
```

**Comment by pshrmn** [comment]
When you say repo files, do you mean the source code? The documentation does exist in the repo (e.g. https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom/docs). While that isn't a solution to the website issue, it should at least make the documentation accessible to you.

As far as CloudFlare configuration goes, I think that @mjackson is the only person here that can modify that.

**Comment by ivosabev** [comment]
Yes I have been using the docs from the repo, but it is a bit cumbersome due to the lack of proper side navigation.

**Comment by pshrmn** [comment]
Another possible solution would be to clone the repo locally and run the site that way. Again, not ideal, but it might give you a better experience.

```
git clone https://github.com/ReactTraining/react-router.git
cd react-router
npm install
npm run build
cd website
npm run start
```
(I'm not 100% sure those are the correct steps)

```

**Comment by zifahm** [comment]
its not down for me per say but all the links under the Example section in the docs seems blank, i don't think its intentional is it?

**Comment by pshrmn** [comment]
@zifahm are you running the Privacy Badger extension? The examples are all codesandbox embed, and Privacy Badger has been blocking codesandbox's domain (I don't have a perfect understanding of the issue, but it is caused by people setting cookies in their sandboxes, which Privacy Badger detects and doesn't like, so all of CodeSandbox gets blocked...).

**Comment by zifahm** [comment]
ohh yeah @pshrmn I am, thanks for the heads up. :)

**Comment by ivosabev** [comment]
Not sure why this was close, the issue persists and website is still not accessible.

**Comment by vasil-dimov** [comment]
Yes, I have the same issue. Last week I was in Germany and https://reacttraining.com/react-router/ works there. Now I'm in Bulgaria and I can`t open the website.

```
Error 522 Ray ID: 4f31875e782a405a • 2019-07-08 10:56:27 UTC
Connection timed out
```

**Comment by mjackson** [comment]
I added an exception in our firewall rules for Bulgaria. Hopefully this fixes the issue.

**Comment by ivosabev** [comment]
Unfortunately it is still not accessible. Maybe geo distribution is not enabled for Bulgaria? Or cache issue? (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.html)

```
502
Ray ID: 4f3623cfbdf7d244 • 2019-07-09 00:22:19 UTC
```

**Comment by mjackson** [comment]
Our Firewall log says that request was allowed. Might be a caching issue with your ISP?

![Screen Shot 2019-07-08 at 10 30 22 PM](https://user-images.githubusercontent.com/92839/60861675-0b844c80-a1d0-11e9-88ef-4ed415908107.png)

**Comment by ivosabev** [comment]
I've tried with a different ISP and I get the same error. Cloudflare seems to be allowing the request but then it fails on the HOST machine. 522 seems to be about that. It seems more like an issue between Cloudflare and the host machine. (https://support.cloudflare.com/hc/en-us/articles/115003011431#522error)

```
Ray ID: 4f4141153a65d24c • 2019-07-10 08:44:41 UTC
```

**Comment by thexpand** [comment]
Same for me. I'm from Bulgaria, too. I've tried different ISPs, but still - no luck.

**Comment by zdravkov** [comment]
Hi @pshrmn,

Would you please explain why is this closed - the site is not reachable for Bulgaria - for the last month - I have tested from all kind of devices and locations and it is not a firewall issue or a caching issue.

Greetings,
Plamen

**Comment by pshrmn** [comment]
I have zero control over how the documentation site is published. Based on Michael's comments, there isn't any reason that there should be issues. This is a crappy situation, but it feels like an issue with Cloudflare (I have no experience with Cloudflare, so I don't know how one would go about diagnosing if Cloudflare is the problem).

It sucks that the real site isn't working, but until the issue is resolved I have deployed the site to Netlify: https://react-router-bulgaria.netlify.com

**Comment by zdravkov** [comment]
Hi @pshrmn, 

I greatly appreciate your effort for providing such a workaround. 

As for the real issue - I strongly believe that it is probably not too far away from being solved - probably one ticket to Cloudfire away - since they are responsible for this issue they should probably be aware what would fix it.

Hi @mjackson, may by you or somebody else, who holds the Cloudfire license should be able to ask them what is going on. 

While the workaround is a great effort I still believe that having such a great product in the dark for a whole country is unacceptable. 

I will be waiting for your reply and if some help with testing the issue or anything else is needed please let me know.

Greetings,
Plamen
