### ISSUE TITLE
throw error: You are loading the ES modules build of React Router on a page that is already running the UMD build in react-router@5.0.1/umd/react-router.js + react-router-dom@5.0.1/umd/react-router-dom.js

### ISSUE THREAD

**Issue by gedy** [ReactTraining/react-router#6826]
## throw error
` <script src="https://unpkg.com/react@16.8.6/umd/react.production.min.js"></script>
     <script src="https://unpkg.com/react-router@5.0.1/umd/react-router.js"></script>   
      <script src="https://unpkg.com/react-router-dom@5.0.1/umd/react-router-dom.js"></script>
`

throw error: **Uncaught Error: You are loading the ES modules build of React Router on a page that is already running the UMD build, so things won't work right.**

DEMO: https://codesandbox.io/s/dazzling-lewin-cmbyo?fontsize=14

## no error
` <script src="https://unpkg.com/react@16.8.6/umd/react.production.min.js"></script>
     <script src="https://unpkg.com/react-router@5.0.1/umd/react-router.min.js"></script>   
      <script src="https://unpkg.com/react-router-dom@5.0.1/umd/react-router-dom.js"></script>
`

DEMO: https://codesandbox.io/s/reverent-river-u6f6n?fontsize=14

**Comment by pshrmn** [comment]
The `react-router-dom` UMD builds bundle `react-router`, so there is no need to include both.

The reason that you don't see the error with the second one is that the `Error` gets removed in the production build because it [behind a `__DEV__` check](https://github.com/ReactTraining/react-router/blob/4736cfe01dc71b6fa69b76ab946b6205447c3faa/packages/react-router/modules/index.js#L1-L22).
