### ISSUE TITLE
Prompt doesn't work when user changes URL in browser bar and hits enter

### ISSUE THREAD

**Issue by heath-freenome** [ReactTraining/react-router#6830]
## Version

v5.0.0

## Test Case

https://reacttraining.com/react-router/web/example/preventing-transitions

## Steps to reproduce

<img width="1000" alt="Screen Shot 2019-07-12 at 1 44 12 PM" src="https://user-images.githubusercontent.com/51679588/61157519-31993d80-a4ab-11e9-9b49-964b1bb276c9.png">

1. Type text to turn on blocking
2. In the browser bar, add `one` to the url and then hit return

## Expected Behavior

The user is asked whether they want to navigate to the `/one` page

## Actual Behavior

The user is sent to the "One" immediately

**Comment by heath-freenome** [comment]
Back in the day, with React-Router 3 I was able to prevent the user from typing a new location to navigate to using the `setRouteLeaveHook` callback capability.  It seems that this capability has been lost.

**Comment by pshrmn** [comment]
The reason that `Prompt` isn't stopping the navigation is because entering a new URL in the address bar is creating a new document/session (the request gets sent to the server, which returns a new response, and the browser unloads the current document and creates the new one).

```
// click link to /one in a single-page application
sessions = [
  ["/", "/one"] // same document
]

// manually enter /one in address bar
sessions = [
  ["/"], // one document
  ["/one"] // a different document
]
```

You could implement the desired behavior using [`onbeforeunload`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload). #4372 is a PR that implemented something similar, but I don't think that it will ever actually be merged. Your best bet might be to copy the modules from there and adapt it if necessary.

**Comment by mjackson** [comment]
We are planning on using the `onbeforeunload` functionality in the history library in version 5 to prevent navigation across pages. Once that's done, we'll introduce some higher-level API here to accomplish the same thing. You can track the progress of that work [in the `dev` branch](https://github.com/ReactTraining/history/tree/dev).

**Comment by heath-freenome** [comment]
@mjackson What is the status of the work you indicated was happening in the history library?  I'm on react-router version 5.1.2

**Comment by heath-freenome** [comment]
Also, @mjackson I'm curious how the route leave hook in 3.x was able to capture the new URL given what I read about in [this article](https://stackoverflow.com/questions/1686687/how-can-i-get-the-destination-url-for-the-onbeforeunload-event).  Did it let the browser jump, then history back and then ask the user?

**Comment by heath-freenome** [comment]
Also, can I ask for this to be reopened?
