### ISSUE TITLE
<Redirect> not working when inside <Switch>

### ISSUE THREAD

**Issue by vviotto** [ReactTraining/react-router#6840]
## Version

**5.0.1**

## Test Case

I can't provide one because if I try the same code in codesandbox it works without problems

## Steps to reproduce

Add a Redirect component inside a Switch

## Expected Behavior

Get redirected from one URL to the other

## Actual Behavior

Application stops with
Uncaught TypeError: path_to_regexp__WEBPACK_IMPORTED_MODULE_7___default.a.compile is not a function

This was on a fresh project created with create-react-app, the only thing I added was react-router-dom and then changed the app.js to look like this:

```
import React from 'react';

import DashboardPage from './components/dashboard-page'
import { BrowserRouter, Route, Switch, Redirect } from 'react-router-dom'

function App() {
  return (
    <BrowserRouter>
      <Switch>
        <Route exact path="/dashboard" component={DashboardPage} />
        <Redirect from="/old-dashboard" to="/dashboard" />
      </Switch>
    </BrowserRouter>
  );
}

export default App;
```

I've tried rendering the redirect outside the switch and without the "from" prop and it works as it should.

The weird thing is, after trying to fix the error for about an hour I manually installed the path-to-regexp library in my project and the redirect started working as it should, after that I **uninstalled** path-to-regexp and the redirect is still working, I never saw that error again so I'm really at a loss at what could be the cause here, but I wanted to report it anyway, maybe someone else is having the same problem.

**Comment by pshrmn** [comment]
Do you also have `express` installed? That uses an older version of `path-to-regexp` and has caused issues for some people.

**Comment by timdorr** [comment]
Nonetheless, this doesn't appear to be a React Router issue.

**Comment by vviotto** [comment]
> Do you also have `express` installed? That uses an older version of `path-to-regexp` and has caused issues for some people.

Yeah, I can see `express` in the dependency tree inside package-lock.json, it was installed by `create-react-app` since this is a newly created project.
Somehow installing and uninstalling `path-to-regexp ` must have fixed the dependency tree and that's why its working fine now, anyone having the same problem could try this and see if it helps.

Thank you.

**Comment by quanpro421a** [comment]
I'm having a similar problem with Redirect inside Switch. I followed the [Redirect (Auth) example](https://reacttraining.com/react-router/web/example/auth-workflow) and write a simple routing as below: 

`
import React from 'react';
import { BrowserRouter as Router, Route, Switch, Redirect } from 'react-router-dom';

function FakeAuth() {
    return (
        <div>
            <Switch>
                <Redirect from="/auth" to="/login" />
                <Route path="/login" render={() => <h1>Login</h1>}/>
                <Route path="/register" render={() => <h1>Register</h1>}/>
            </Switch>
        </div>
    );
}

function App() {
    return (
        <div className="App">
            <Router>
                <Switch>
                    <Route exact path="/auth" component={FakeAuth}/>
                    <Route path="/" render={() => <Redirect to="/auth"/>}/>
                </Switch>
            </Router>
        </div>
    );
}

export default App;
`

When I went to root, it redirected to `/auth/login` as expected but instead of rendering the text "Login" I got the `Maximum update depth exceeded` error.
Then I tried to remove all the Switch and the error was gone but nothing rendered even though I got the right path `/auth/login`

**Comment by quanpro421a** [comment]
I'm having a similar problem with Redirect inside Switch. I followed the [Redirect (Auth) example](https://reacttraining.com/react-router/web/example/auth-workflow) and write a simple routing as below: 

```
import React from 'react';
import { BrowserRouter as Router, Route, Switch, Redirect } from 'react-router-dom';

function FakeAuth() {
    return (
        <div>
            <Switch>
                <Redirect from="/auth" to="/login" />
                <Route path="/login" render={() => <h1>Login</h1>}/>
                <Route path="/register" render={() => <h1>Register</h1>}/>
            </Switch>
        </div>
    );
}

function App() {
    return (
        <div className="App">
            <Router>
                <Switch>
                    <Route exact path="/auth" component={FakeAuth}/>
                    <Route path="/" render={() => <Redirect to="/auth"/>}/>
                </Switch>
            </Router>
        </div>
    );
}

export default App;
```

When I went to root, it redirected to `/auth/login` as expected but instead of rendering the text "Login" I got the `Maximum update depth exceeded` error.
Then I tried to remove all the Switch and the error was gone but nothing rendered even though I got the right path `/auth/login`

**Comment by ginsan95** [comment]
I am having this issue as well.
My solution is to put the `Redirect` out of switch.

**Comment by orloffm** [comment]
Fixed by:

1. Adding dependency `"path-to-regexp": "^1.7.0",`.
2. Deleting `.node_modules` and doing `npm install`. That properly updated `package-lock.json`.
