### ISSUE TITLE
Tree shaking with webpack seems not work properly.

### ISSUE THREAD

**Issue by Sebruck** [ReactTraining/react-router#6842]
## Version

5.0.1

## Test Case

https://github.com/Sebruck/react-router-reproducer/

## Steps to reproduce

If I do this import `import  {Link} from 'react-router-dom';` webpack adds a lot (67kb stat, 13kb parsed)  to my bundle by adding the history, react-router and react-router dom module.

<img width="565" alt="Screen Shot 2019-07-25 at 08 39 35" src="https://user-images.githubusercontent.com/2050823/61851615-c2aee200-aeb7-11e9-9f77-82e832c006f3.png">

## Expected Behavior
Only things which are actually needed by the Link component should be inside the bundle. It should be tree shakes as far as webpack is capable of.

## Actual Behavior
By comparing the sizes of the modules with bundle-phobia, for me it looks like tree shaking is not happening at all.

**Comment by timdorr** [comment]
We use flat bundles (much like React) that pack up all modules into a single file and Webpack's tree shaking only occurs at the module/file level. This is expected behavior for Webpack. The removal of unused imports would happen later with a took like Terser or babel-minify, which does dead code elimination.

**Comment by Sebruck** [comment]
Thanks for the clarification!
