### ISSUE TITLE
Please add linting to the Travis CI in order to make sure that linting works

### ISSUE THREAD

**Issue by phapdinh** [ReactTraining/react-router#6858]
Have a feature request?
=======================
Please add linting to the Travis CI in order to make sure that linting works

**Comment by timdorr** [comment]
Linters are better used for local development. They're not always correct (hence having to inline ignore statements) and shouldn't fail a build because of a heuristic failure. And don't get me started when folks use them for styling enforcement...

So, for now, I don't think we're going to include it in the CI runs.
