### ISSUE TITLE
5.1.0 introduces a breaking change for <Route children> prop

### ISSUE THREAD

**Issue by 1000hz** [ReactTraining/react-router#6928]
## Version

5.1.0

## Test Case

https://codesandbox.io/s/reverent-water-wvdvp

## Steps to reproduce

Change the version of `react-router-dom` between `5.1.0` and `5.0.1`

## Expected Behavior

Both versions of `react-router-dom` render the same thing

## Actual Behavior

`react-router-dom@5.1.0` treats `<Route children>` differently than previous versions. Previously, children were ALWAYS shown, regardless of being matched or not. Now they only show if the path matches. This should be considered a breaking change.

**Comment by 1000hz** [comment]
Also wanna express my extreme excitement for 5.1.0 and don't mean to take the wind out of your sails. Congrats on shipping and thanks for your continued effort!

**Comment by MeiKatz** [comment]
Not sure why this is not marked as a breaking change but it is definitely one and it was also planned as one. If you want to have the same behaviour as before you either have to omit the `path` prop or the `path` must be `"*"`. The previous behaviour was just useless and I think in RR6 so at least `<Route render>` will be dropped because they both have the same behaviour but `<Route children>` is the "prettier" one of the both.

**Comment by 1000hz** [comment]
Just found the discussion in #6362 where the team states they consider the old behavior a bug and not part of the public interface. In that context I guess it makes sense for this to be considered a bugfix and not a breaking change, given that with the old behavior `children` was probably rarely used with a ReactNode instead of a function.

I will say however that this behavioral change was surprising to me given how I understood `children` to work. There was some cognitive dissonance reading the 5.1 announcement blog post around the now-recommended way to use `Route`. It might be worth making this change a bit more pronounced in the release notes / blog post.
