### ISSUE TITLE
React Hooks not working when a react component containing it is passed to get rendered in Route inside BrowserRouter 

### ISSUE THREAD

**Issue by anu1097** [ReactTraining/react-router#6969]
Here's the sandbox link - https://codesandbox.io/embed/react-router-dom-hooks-issue-0049d

I am able to render the same component as a standalone component but facing issue when I am trying to get it rendered inside a Route. 

Dependencies are latest and can be viewed in the sandbox.

The error I am getting is  - 

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

I have got this in my local project as well. I have checked for all 3 none are in violation.

## Version

**Please replace this sentence with the React Router version that you are using.**

## Test Case

https://codesandbox.io/s/react-router-gh6n7

**Comment by StringEpsilon** [comment]
Works when you do `<Route path="/sample" component={SampleHooks} />`

`Route` actually calls the render prop and returns the result, rather than giving the function itself to react to call and render. 

```js
render(){
  // bits and bops...
  return this.props.render(props);
}
```

So it's the first reason react gives you. The hook runs outside the context it's supposed to run, because `Route` prematurely calls your functional component.

**Comment by anu1097** [comment]
Thank you for the explaining the issue. I understood my mistake and its working now.
