### ISSUE TITLE
Incorrect parsing of route params

### ISSUE THREAD

**Issue by tatomyr** [ReactTraining/react-router#6989]
I'm trying to pass an encoded value as a router parameter. The issue comes in when I decode the `%` sign (which is replaced with `%25` in the URL).
The router doesn't recognize this combination correctly and passes only `%` sign into `match.params.id`. Seems like a bug to me.
Please find Code Sandbox example down below:

https://codesandbox.io/s/react-router-v5-starter-09qin

**Comment by dannsam** [comment]
Experiencing the same issue, it seems like `history` uses `decoreUri` instead of `decodeUriComponent` for `pathname`. If I change `history` to use `decodeUriComponent` everything works as expected
https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/LocationUtils.js#L36
