### ISSUE TITLE
location.key not set on initial mount

### ISSUE THREAD

**Issue by bmuenzenmeyer** [ReactTraining/react-router#7008]
`location.key` is not available on initial mount.

A user reported this behavior to me - I've created a reduced test case and am not sure if it's intended behavior or a bug. I tried searching the docs, FAQs, old issues, and SO before opening this.

## Version

5.1.2

## Test Case

Deployed: https://react-router-location-key-test.netlify.com/render-log
Code: https://github.com/bmuenzenmeyer/react-router-location-key-test

## Steps to reproduce

1. go to above url
2. view text that says no `key` is available on `location`
3. open dev console
4. confirm that `location` does not have `key` (screenshot 1 below)
5. click on any route, including the one you are already on
6. see text displaying the `location.key` value
7. in the console, see the output `location` object, now with key (screenshot 2 below)

## Expected Behavior

`location.key` is available on initial mount, similar to steps 6 and 7

## Actual Behavior

`location.key` is not set unto a navigation occurs (after mount)

![image](https://user-images.githubusercontent.com/298435/67512850-52069580-f65f-11e9-86f7-ec43deccb085.png)

click any link to cause a route to re-render

![image](https://user-images.githubusercontent.com/298435/67512908-69458300-f65f-11e9-8e19-4bfa642210a0.png)

`location.key` now set

**Comment by bmuenzenmeyer** [comment]
if this is deemed a bug, I can try my hand at contributing a failing test and fix - but I wanted to demo it first to confirm incorrect behavior.

**Comment by timdorr** [comment]
This is expected behavior. 

Just so you're aware, the key is actually [created in the history library](https://github.com/ReactTraining/history/blob/8bbace1aabbce9fc718a24a2d08c6ac41e9e30b6/modules/createBrowserHistory.js#L74-L78). When creating a history instance, which is [what `BrowserRouter` and other Routers do for you](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/BrowserRouter.js#L11), it's [loading up the initial location from the DOM](https://github.com/ReactTraining/history/blob/8bbace1aabbce9fc718a24a2d08c6ac41e9e30b6/modules/createBrowserHistory.js#L145). 

The `key` is unique to the history library. [It's not part of the spec](https://developer.mozilla.org/en-US/docs/Web/API/Location), so it doesn't exist on the initial location. 

Therefore, it being blank is technically correct.
