### ISSUE TITLE
Updating react router - react-loadable problems, React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by maaaaagda** [ReactTraining/react-router#7011]
## Version

**5.1.2**

## Steps to reproduce
 I updated react-router-dom ( which updated react-router) and now my application is crashing:
**Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `LoadableComponent`.**

`const Dashboard = Loadable({
  loader: () => import(/* webpackChunkName: "Dashboard" */ "./components/dashboard/Dashboard"),
  loading
});`

![image](https://user-images.githubusercontent.com/17687646/67575294-88fea900-f73c-11e9-9175-db53291a5402.png)

`
class Dashboard extends Component {}
export default withTranslation()(connect(select)(Dashboard));`

Now may page is not rendered. What's changed?

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
