### ISSUE TITLE
nested route CSSTransitions and TransitionGroups not respected.

### ISSUE THREAD

**Issue by laurencefass** [ReactTraining/react-router#7049]
Version
5.1.2

Test Case
Example from your website.
https://codesandbox.io/s/react-router-animated-transitions-07rue?from-embed

Steps to reproduce
Goto: https://codesandbox.io/s/react-router-animated-transitions-e90l3
Select: Nested route
Select: any sub route.
Check: the Nested component has its own transitions defined. They are not being applied to the the sub-route which is incorrectly applying the top level CSSTrantition animations to the nested component.
 
Expected Behavior
I expected that TransitionGroups and CSSTransitions could be nested

Actual Behavior
Nexted TransitionGroups and CSSTransitions are not effective and top level animations are being applied to children.

**Comment by timdorr** [comment]
This isn't a problem with React Router. For the parent routes, you need to use the part of the path that is matched at that level, not the full path. It is getting a transition from one `location.key` to another. 

That is, it sees it go from `/nested/sub2/sub1` to `/nested/sub2/sub2` and renders a new CSSTransition. Instead, you should look at only the part of the path that it is concerned with, so it should be keyed on `/nested` so that it doesn't re-render when the sub-path changes.

**Comment by laurencefass** [comment]
Thanks for feedback is this possible using React Router 5? Ive only recently picked up React Router 5 and I've been experimenting for over a week without success. 

Specifically I'm not sure how to achieve this: "look at only the part of the path that it is concerned with, so it should be keyed on /nested so that it doesn't re-render when the sub-path changes".

What should be keyed on /nested? The immediate children of /nested or all subroutes?

Could you possibly fork and modify the sandbox according to your instructions. I cant find any nesting examples this would probably be useful to others on same path...
