### ISSUE TITLE
Feature request: native guard

### ISSUE THREAD

**Issue by darklight9811** [ReactTraining/react-router#7077]
It's been enough time for work arounds. We need react router to add natively guards (auth support). It can be a simple boolean check.

## How it would work

The router could support a prop of type boolean that shows if the user is logged:
``` javascript
<Router logged={true}>
```

Now the only thing we need to do, is to inside of a route, check for it:
``` javascript
<Route guard="guest">
```

Having to default types: guest and logged. If the user is logged and the route requires guest, it won't pass, and vice-versa for logged. Of course there should be the check inside of the Switch component.

## Conclusion
This is really simple and has space for expansion. I'm tired of writing custom Switchs and Routes to make this work, when it should be native from the start. And by the way, I still think that routes should support a when parameter to make a simple boolean check (that would be run in switch components also).

**Comment by MeiKatz** [comment]
There are ideas to add a `validate` prop to the `<Route />` component. This would go well with your proposal, but is more general in its use cases.

**Comment by darklight9811** [comment]
@MeiKatz, I really wouldn't like to mix those, because auth is such a common feature, and seeing they are giving what we brazilians call "gambiarra" (let's say it's a horrible way of fixing things) in their documentation for it, gives me an horrible feeling.

**Comment by MeiKatz** [comment]
@darklight9811 I don't think that this kind of feature is in the scope of RR. But you could implement it on your own if there were something like the `validate` prop, that enables you to use conditional skipping of routes.

**Comment by darklight9811** [comment]
I came up with an idea that scalates better. It's a kind of a middleware.

## How it would work
First you place the guard available to the router:

``` javascript
<Router guards={{guest, logged, validateSomething}}>
    {...}
</Router>
```

Those variables would be functions that would run some logic when required, let's show for example the validateSomething:

``` javascript
function validateSomething (data, _arguments) {
    return data.path == _arguments[0];
}
```

The first argument is data, that would be entire router encapsulated into an object, so you would be able to access current path, type, location stuff. The second is a set of arguments that you can set when calling it, now let's see how you can do so:

``` javascript
<Route {...} guards={"validateSomething:home"} />
```

This is pretty much like laravel, the guards prop could accept an array of strings or a simple string. We could encapsulate the router components inside guards, to enable a full customization on it's behaviour.

**Comment by timdorr** [comment]
We're not going to do this. Mainly because while it makes sense for the simple case (I do or do not have access to this individual Route), it breaks down as an abstraction over many routes or many levels of auth (or both!). 

You would have to add the validation prop to each route individually. This is both cumbersome and error prone. It creates a ton of boilerplate for any decently-sized application.

The easier thing is to just move the check up above your Switch and provide two sets of routes for authed or unauthed users. Something like `!!user ? <SwitchWithAuthRoutes> : <SwitchWithPublicRoutes>`. If you need to reuse routes, just use common arrays and combine them together in whatever structure you need.

Again, this is attacking the problem from the wrong angle. It's more scalable to not build this into React Router as an API, but to structure your app agnostically to the routing layer.
