### ISSUE TITLE
Link vs Redirect

### ISSUE THREAD

**Issue by biggless** [ReactTraining/react-router#7100]
## Version
**5.1.2**

## Test Case
https://codesandbox.io/s/sharp-feynman-eyqvb

## Steps to reproduce
There is a simple app with few routes.
On the "Users" page you can find link and a button (with redirect onClick) to new user form.
If you'll use link - UserForm will be rendered up to the list. Closing form will render users list.
If you'll use button - UserForm will be rendered without the list. Closing form will render blank page.

Is this expected behavior?

**Comment by timdorr** [comment]
Your `UserList` component is always rendering because its Route matches for both the `/users` and `/users/new` paths. You're not rendering with the button because you've set state to only show the Redirect. This isn't React Router, it's just how you've coded it. If you use an `exact` prop on your Route, it will not show the UserList component for either the link nor the button.
