### ISSUE TITLE
NavLink active styling does not work

### ISSUE THREAD

**Issue by kirubiel** [ReactTraining/react-router#7129]
## Version

React Router ^5.1.2

## Test Case

https://codesandbox.io/s/nervous-haibt-k2cvv (Works in the sandbox but not on local machine)

## Steps to reproduce

`<NavLink activeClassName="active" to="/somewhere">Somewhere</NavLink>`

## Expected Behavior

Should style the link when the URL matches.

## Actual Behavior

It styles the link when it's clicked on but removes the style as the click is released.

Additional information: https://stackoverflow.com/questions/60078104/navlink-active-styling-does-not-work-react-router#

**Comment by timdorr** [comment]
Since it works in the sandbox, it's got to be something with your local setup that's interfering. If you can reproduce it in the sandbox, we can reopen this as a potential bug.

**Comment by ConneXNL** [comment]
I actually got the same issue with a refresh install @ 5.2. I tracked down the problem and it seems that the following line in <NavLink />:  https://github.com/ReactTraining/react-router/blob/ea44618e68f6a112e48404b2ea0da3e207daf4f0/packages/react-router-dom/modules/NavLink.js#L56  seems to be the problem.

If the escaping is not done it works. The escaping changes an url like `/users` to `\/users` and at that point react-router's matchPath ( https://github.com/ReactTraining/react-router/blob/29e02a301a6d2f73f6c009d973f87e004c83bea4/packages/react-router/modules/matchPath.js#L28-L65 ) is then returning `null`.

I am using typescript btw.

**Comment by ConneXNL** [comment]
For me it turned out to be "express" in the monorepo that is referencing `0.1.7` of `path-to-regexp`. For some reason it installed the correct `1.8.0` correctly in the `/node_modules/react-router/node_modules` folder but it was still using a version of `/node_modules/path-to-regexp` that was at `0.1.7.`

Maybe its a typescript related issue? or even a tsconfig configuration that prevents it from picking up the correct `path-to-regexp` if two are in the project.
