### ISSUE TITLE
Parameter values are encoded (react-router v6)

### ISSUE THREAD

**Issue by SpudNyk** [ReactTraining/react-router#7173]
## Version

react-router-dom@6.0.0-alpha.2

## Test Case

https://codesandbox.io/s/react-router-tv3xb

## Steps to reproduce

Use the test case and click on the parameter test links

## Expected Behavior

The param values should not have % encoded characters.

## Actual Behavior

The param values have encoded characters.

**Comment by timdorr** [comment]
[The params are specifically _not_ decoded right now](https://github.com/ReactTraining/react-router/blob/bff5b49c98cb5cde32e63cdda524068ce1209f09/packages/react-router/index.js#L724). We still have that as an open question about how to handle it.

This has been an ongoing issue with the history library: ReactTraining/history#745 and ReactTraining/history#505 The plan there in 5.0 is just to not touch them at all. Let downstream libraries and users handle it if they want. 

I think we'll take the same approach here, so it will be up to you to decode those values further. It's a similar philosophy to our query string handling (which we also don't parse).

**Comment by SpudNyk** [comment]
Maybe as the API is hooks based now maybe adding a parameter to useParams to either force raw values or force decoding could be added?

I feel that the principle of least surprise should apply here.

**Comment by bjarkehs** [comment]
I wonder what is actually least surprising. I think I'd want the raw param. If I wanted the decoded params I could easily create a `useDecodedParams`.

**Comment by CXuesong** [comment]
+1 for the raw params, while it can be helpful to offer a shortcut to retrieve the decoded version.

As a question during parsing parameters, to decode or not may seem subtle, but when it comes to whether to encode parameters with `generatePath`, it will be difficult for `react-router` itself to determine between `encodeURI` and `encodeURIComponent` (e.g. I usually don't want slash to be escaped in the `*` parameter).

I guess it's good to keep path generation and parsing logic consistent, so it's best for `react-router` to expose the raw params for the users, while offering some snippets so users and tailor the raw parameters to their needs.

And I'm happy to see v6-alpha.3 now offers me the raw params instead of the encoded/decoded ones.

**Comment by Kostanos** [comment]
Hey, I actually would like to have a raw parameter, and useParams returns decoded already.
Example:

path:  /companies/Samsung%2CInc,Lenovo%2CInc

```
const params = useParams();
const companies = params.companies?.split(',');

Expected:
[
  'Samsung%2CInc',
  'Lenovo%2CInc',
]
Getting:
[
  'Samsung',
  'Inc',
  'Lenovo',
  'Inc',
]
```
Any recommendations here?

**Comment by kiliman** [comment]
Unfortunately you're going to have to parse it yourself.
```ts
const url = new URL(request.url);
const companies = url.pathname.match(/^\/companies\/(.*)$/)![1];
console.log(companies.split(",").map((c) => decodeURIComponent(c)));
```

**Comment by Kostanos** [comment]
Oh man, this not good, I think there should be a hook to get the RAW params.
Meanwhile I created a small/simple gist if someone need it: https://gist.github.com/Kostanos/e3cc71b6263846cdd887395f505076c8

**Comment by kiliman** [comment]
True, but a library isn't going to cover everyone's needs. The fact that it's OSS means you can submit a PR, or at the very least, write your own code to handle your particular usecase.
