### ISSUE TITLE
Switching between similar routes results in the components in separate routes sharing state.

### ISSUE THREAD

**Issue by UnklePig** [ReactTraining/react-router#7232]
Full disclosure - I am fairly new to react-router and this may be expected behavior, but I couldn't find anything that confirmed this either way and it certainly is not intuitive to me that things would behave this way in this specific situation.  Is definitely a very edge case - and there are multiple workarounds that I can think of so is not blocking anything for me.  Just letting you know.

## Version

5.1.2

## Test Case

https://codesandbox.io/s/routes-stateful-component-a-dt7y9

## Steps to reproduce

A switch with more than one route.  Multiple routes must have the exact same component (or combination of components) that maintains their own state.  These routes need to be defined as child components of the route - not with "component" attribute.  Switch routes between these similar routes and check the component state. 

## Expected Behavior

Switching routes would rerender the component and reset the state. Similar to this example that has each route changed slightly with a different wrapper.

https://codesandbox.io/s/routes-stateful-component-b-xjbjy

In this example the buttons counter resets when switching routes.

## Actual Behavior

The state of the component in the previously selected route is present in the component in the current route.  In the example - you can see that the button counter doesn't reset to 0 when switching routes.

**Comment by timdorr** [comment]
This is just how React works. If you render the same component tree, it will retain the state of those components. There is no fix we can apply at the library level, because you may not want the component state to reset when the location changes, such as with a persistent header. 

In most applications this won't be an issue. You generally have a component-per-route structure, which will be unique for each route. But if you need a workaround, use a key prop with a unique value for each component in each route. That will tell React each one is different and should be reinstantiated.
