### ISSUE TITLE
V6: Optional parameters

### ISSUE THREAD

**Issue by clarkd** [ReactTraining/react-router#7285]
I tried adding a trailing `?` to a route using the v6 router, but it didn't seem to work.

```
<Route path='/page/:friendlyName/:sort?' element={<Page/>} />
```
Are optional parameters supported in v6, or are they coming later?

**Comment by timdorr** [comment]
We don't plan on supporting them in v6.

**Comment by clarkd** [comment]
@timdorr Thanks - could you explain a little on how you would achieve it in v6? At the moment I have the below which works but seems less than optimal. Any thoughts?

```
<Route path='/page/:friendlyName/:sort' element={<Page/>} />
<Route path='/page/:friendlyName/' element={<Page/>} />
```

**Comment by gopeter** [comment]
It would be great if this could be described in the migration guide – or if there was at least a hint. So the recommended way of doing "optional" params really is ...

```
<Route path='/page/:friendlyName/:sort' element={<Page/>} />
<Route path='/page/:friendlyName/' element={<Page/>} />
```

... ?

**Comment by MeiKatz** [comment]
@gopeter Yes, or you can do something like this:
```jsx
<Route path="/page/:friendlyName">
  <Route path=":sort" element={<Page />} />
  <Route path="" element={<Page />} />
</Route>
```

**Comment by gopeter** [comment]
Aaaaah, great, thank you very much! 😄

**Comment by robbinjanssen** [comment]
@MeiKatz @timdorr my problem with the approach above is that the `<Page>` component unmounts and mounts again. Performance-wise this might be a bad thing, but in my case it also results in a bunch of refetching of data. I can fix this inside the Page-component itself by checking if data is there already, but not only does this change break my routing, it also breaks application itself. 

Any other suggestions on how to implement this (Route-wise)?

**Comment by MeiKatz** [comment]
@robbinjanssen Have you thought about using the `<Outlet />` element?

```jsx
<Route path="tickets" element={ <TicketsPage /> }>
  <Route path=":ticketId" element={ <ShowPage /> } />
  <Route path="" element={ <IndexPage /> } />
</Route>
```

```jsx
const TicketContext = React.createContext( {} );

function TicketsPage() {
  const [ tickets, setTickets ] = useState({});

  useEffect(() => {
    // do some loading stuff
    const res = await fetch("/tickets");
    const tickets = await res.json();

    setTickets( tickets );
  }, []);

  return (
    <TicketContext.Provider value={ tickets }>
      <h1>My Tickets</h1>
      <Outlet />
    </TicketContext.Provider>
  );
}

function ShowPage() {
  const tickets = useContext( TicketContext );
  const { ticketId } = useParams();

  const ticket = tickets[ ticketId ];

  return (
    <div>{ JSON.stringify( ticket ) }</div>
  );
}
```

**Comment by robbinjanssen** [comment]
@MeiKatz not yet, hoped I would not have to refactor that ticket page, but seems like there's no other way. It's a pretty "old" component that requires a lot of work when refactoring. So I hoped I could somehow keep the optional parameters ;)

**Comment by MeiKatz** [comment]
@robbinjanssen Understandable. But I don't think that there is any other way you can solve it. And I also think, that it is a clean way to do it. Also we could think about dropping the whole context stuff and pass the parameters to the `<Outlet />` and from there to the element.

**Comment by robbinjanssen** [comment]
For now I'll just parse the "raw" params into the bits I need, those URLs are not that complicated fortunately, and i'll put the component on the refactor list. Thanks :)

**Comment by manterfield** [comment]
Is there anywhere public that we can see the reasoning behind the choice to drop this feature? I appreciate the workarounds and help you've provided above @MeiKatz, but they're still a less ergonomic developer experience (IMO at least).

I can't imagine that you'd take that choice without good reason, but it'd be good to know what that was and if it's something that can be overcome?

**Comment by n8sabes** [comment]
Dropping optional parameters has caused **significant** pain and inability to easily migrate from v5 to v6. The new v6 architecture doesn't make immediate sense to me. The impact of non-working projects then constant reloading of components is proving a painful endeavor and weighing out simply rolling back v5.

I too wish there was a more open collaborative discussion on this before such a radical change without a clean migration path.

**Comment by bthorben** [comment]
I would like to chime in and second that this is a huge change. It means changing the architecture of an application. For our application, this will result in multiple weeks of work.

**Comment by Kepro** [comment]
same here, our application will need couple of weeks of refactoring because of missing optional parameters :( I was very excited about v6 but looks like v5 is still better choice for our team now :(

**Comment by elliotdickison** [comment]
**Really appreciate the work on react router**. This comment is meant to be feedback, not a complaint, but I'm starting a new project on v5 because of this issue. Possible I'm just not the target audience of v6.

**Comment by vylink** [comment]
Hi there, We are using dynamic routing(based on data from the server). The following path was simply perfect for your case.

```
        <Route
          path="/studio/studio/collections/:id/:view/:id2/:view2"
          render={() => <ReturnedComponent someParams={someParams}  />}
        />
"/:id?/:view?/:id2?/:view2?/:id3?/:view3?/:id4?/:view4?"
```

Returned component decided what to do based on the optional parameters. Is there any way, how to achieve this kind of stuff with V6?

**Comment by queengooborg** [comment]
I'm a bit surprised to see that support for optional parameters was dropped in v6.  This is an extremely useful feature, and its removal has made a v5 to v6 project more challenging.  The workarounds people here have suggested are great for smaller apps, but it's not clear why there has to be a workaround in the first place?

I'd love to hear the reasoning behind this change.

**Comment by sridharravanan** [comment]
> @gopeter Yes, or you can do something like this:
> 
> ```js
> <Route path="/page/:friendlyName">
>   <Route path=":sort" element={<Page />} />
>   <Route path="" element={<Page />} />
> </Route>
> ```

its working

**Comment by Kepro** [comment]
@timdorr any reply that you want to add?

**Comment by jrmyio** [comment]
I will give my take on this because I find it rather unfortunate that in 2021 the most popular Javascript router doesn't support a pattern I've been using successfully for almost 2 decades.

As far as I can see from reactions and discussions in this and other issues, the reason optional parameters are not supported in v6 is because they don't work well with the idea behind remix where a `/` in the URL means further down in a nested tree. They function mainly to follow the _hierarchy_ of your page, for example:
`User -> Messages > Inbox`  with the route `user/messages/inbox`.

When you want to use _optional parameters_, these are (almost) never related to the _hierarchy_ of the page. Thus, it is suggested that you use query params. For example for ordering, filtering, pagination of the inbox you would start using the querystring:
user/messages/inbox`?page=1&order=email`.

**However**, folks at @remix reference the old PHP days quite a lot, and they might remember that before the nginxes and node servers,  people used apache's `.htaccess rewriterule` to rewrite urls like  `/$order/$page` => to things like `index.php?order=email&page=1`.  There were and are still are reasons why people do not want to use the query params for these kind of things, here are some advantages you get when not using the query string:

- You can have a single unique URL for each page:
For example, `email/1` with a querystring will have multiple possible urls: `?order=email&page=1` and `?page=1&order=email`. They may clutter your google index pages or maybe even CDN caches when these params are not always in the same order.

- Urls without using a querystring are shorter and look cleaner:
`inbox/1/email/desc` vs `inbox?page=1&order=email&order_direction=desc`.

- They are better for SEO:
When optimizing for a keyword `audi rs7`, google likes `cars/audi/rs7` more than `cars?brand=audi&type=rs7` (atleast this was the consensus when I was really into SEO in the old days).

- You can use the URL bar as a way of navigating:
For example `flights/amsterdam/2021-11-01/2021-11-03/2` is a pretty easy URL to grasp, it almost invites you to edit it manually instead of using that city selector or time widget to specify your search query, I think `flights?from=2021-11-01&city=amsterdam&till=2021-11-03&page=2` is not all that inviting. Although this is more of a power user feature, I do find myself using this all the time where I implemented these kind of clean URLs.

Now, I haven't put much thought in how to get the best of both worlds, and I realize that by keeping a nested `<Route/>` about the _hierarchy_ of the page helps a dev understand what a route really means, and gives frameworks like remix an easier time dealing with the URLs to understand the _hierarchy_.

That's why I think adding an additional component to deal with optional parameters, or `pathname` that are not related to the  _hierarchy_, might be the possible solution. 

For example, Something like `<QueryPath/> ?`  This would differentiate it from being a regular `<Route/>`, and tell _react-router_ its simply a  configuration to map the query params to a nicer pathname. This path would is expected to come AFTER  the pathname of the current parent Route. It could potentially also configure default values for each of its optional parameters, for example:

```tsx
<QueryPath path={':city/:from/:till/:page'} defaults={{ city: 'all', from: 'any', till: 'any', page: 1 }} />
```
a seperate hook like `useQueryPath`, or maybe just the `useParams`  could return these values for these params. Values that are their default could be left out, or set to `null`.

Since constructing these URLs is pretty hard it would be great if one can reuse the configuration of `path={':city/:from/:till/:page'} defaults={{ city: 'all', from: 'any', till: 'any', page: 1 }}` somehow so that a `generateQueryPath` could generate this part of the removing all the default values used at the end of the pathname.

I hope anything I just wrote is of any help moving this discussion further 🙄 .

**Comment by n8sabes** [comment]
**Quick Optional Parameter Solution** — Following up on [prior post](https://github.com/remix-run/react-router/issues/7285#issuecomment-961545132).

@jrmyio makes some good observations and worth the read. For the record, I love react-router v5. However, rearchitecting for v6 with what seem to be unintuitive code patterns (hacks) that necessitated deep app code/flow changes, simply to get existing value, required too much effort without meaningful new value.

After much head banging, hit a hard-stop with v6 and decided to try [wouter](https://github.com/molefrog/wouter). **Ended up migrating to [wouter](https://github.com/molefrog/wouter) quickly with very little effort** as the wouter GitHub page is straight-forward, making it an easy migration guide to swap out react-router and regain optional parameters.

Hopefully there will be more time to spend with react-router v6, but for now wouter is meeting expectations, and is a smaller library. _Keeping fingers crossed for optional parameter backward compatibility from v6!!_

**Maybe this issue should be re-opened?**

**Comment by ymoon715** [comment]
This doesn't feel like a react-router 6. This feels more like a new router with a new philosophy.
I'm gonna have to stick to v5 and cross my fingers I find a worthy alternative. This isn't just a "breaking change". This is actually "must find alternatives" for a lot of people including me

**Comment by PeteJobi** [comment]
For those with the problem of pages unmounting and remounting on route change, I found out now that if you put your element on the parent ```<Route>```, there will be no unmounts. That is, in the case of @robbinjanssen, if he changes the parent route
```
<Route path="tickets">
   ...
</Route>
```
to this:
```
<Route path="tickets" element={<List />}>
   ...
</Route>
```
It should work as he expects....

I can't say for sure though as this may depend on the implementation for ```<List/>```, but it works for me.

**Comment by saidMounaim** [comment]
> @gopeter Yes, or you can do something like this:
> 
> ```js
> <Route path="/page/:friendlyName">
>   <Route path=":sort" element={<Page />} />
>   <Route path="" element={<Page />} />
> </Route>
> ```

Thank youu

**Comment by mmaloon** [comment]
How about using the new `"*"` path catchall pattern? It looks like this works similar to an "optional" segment, and will be stored in the "*" key of the `useParams` hook return object.

```jsx
<Route path='/page/:friendlyName/*' element={<Page/>} />
...
function Page() {
  const { friendlyName, '*': sort } = useParams();
  // `sort` will contain anything from the pathname after the friendlyName segment, or undefined
   ...
}
```

**Comment by iamunadike** [comment]
@gopeter Yes, or you can do something like this:

```
<Route path="/page/:friendlyName">
  <Route path=":sort" element={<Page />} />
  <Route path="" element={<Page />} />
</Route>
```
I would like to contrubute here by saying  , the above is good but a bit ambiguous, 
imagine having to have multiple lines for single component, 

my hints to help for boosting efficiency in v6:
- Return the optional params with the symbol that really makes it optional (?) :+1: 
     In this way the code base is more simplified and DRY seems to be appreciated more into the way it works, making project   coding faster as it should be though I also recognize the team may have to do more work parsing a given path to prevent unncessary page reloads which may be overcome in the next steps below

- Another fix should optional params or even params should be specified,  by using dictionary values:
 instead of 
`<Route path="/abcd/:something?(one|two|three)" component={<Page />} /> `OR 
`<Route path="/abcd/:something(one|two|three)" component={<Page />} />`
there should be a more appreciated approach using 
`<Route path="/abcd/:something/:lowkey" params={something: ['one', 'two', 'three'], lowkey: ["maybe"]},  component={<Page />} />`

- Introduction of named routes, 
 using named routes which should be unique per route,  the components is easily called instead of explicitly naming a route with say :+1: `<Link to='/somepath' params={}/>` we can also use `<Link to={some_routeName} params={} />`

These are just some concerned opinions and this should apply to routes.js with a seperated routes component in a seperate file

**Comment by iamunadike** [comment]
Furthermore imagine you have a file called routes.js in the react root folder and this has nested routes with nested routes ,and then you want to point the nested routes to optional params using this approach
```
<Route path="/page/:friendlyName">
  <Route path=":sort" element={<Page />} />
  <Route path="" element={<Page />} />
</Route>
```

```
routes = [
....omitted for brevity
    { path: "", element: <Main />,
  children: [
        { path: "/page/:type", element: <Page />,
        children: [
          { path:  ":status/:step", element: <PageForm /> },
        ],
      },
],
```
then writing the multiple routes would be a problem I guess because you may to repeat the whole nesting for the children of an already nested routes which would be cumbersome I suppose and boring
so again the optional ? parameter wins except it can be set to arrays say :
```
routes = [
    { path: "", element: <Main />,
  children: [
        { path: ["/page/:type", "/page"], element: <Page />,
        children: [
          { path:  ":status/:step", element: <PageForm /> },
        ],
      },
],
```
N.B the above approach does not work at the time of this writing , React Router v6 being used

**Comment by iamunadike** [comment]
Furthermore imagine you have a file called routes.js in the react root folder and this has nested routes with nested routes ,and then you want to point the nested routes to optional params using this approach
```
<Route path="/page/:friendlyName">
  <Route path=":sort" element={<Page />} />
  <Route path="" element={<Page />} />
</Route>
```

```
routes = [
....omitted for brevity
    { path: "", element: <Main />,
  children: [
        { path: "/page/:type", element: <Page />,
        children: [
          { path:  ":status/:step", element: <PageForm /> },
        ],
      },
],
```
then writing the multiple routes would be a problem I guess because you may to repeat the whole nesting for the children of an already nested routes which would be cumbersome I suppose and boring
so again the optional ? parameter wins except it can be set to arrays say :
```
routes = [
    { path: "", element: <Main />,
  children: [
        { path: ["/page/:type", "/page"], element: <Page />,
        children: [
          { path:  ":status/:step", element: <PageForm /> },
        ],
      },
],
```
N.B the above approach does not work at the time of this writing , React Router v6 being used

**Comment by manterfield** [comment]
@timdorr Could you spend a moment to give us some reasoning for this feature being removed? I understand it's a conscious choice, but is that due to development resources, conflicting with some other design choice, or something else?

With that information the community will be better able to move forward, either by someone stepping up and solving whatever problem you've seen with it, contributing the code, or just forking. At the moment we're all sort of in the dark which makes any community contribution difficult.

Given the number of issues opened about this and related features and the responses on each of those and here, it's clear it's a pretty important feature to users.

**Comment by jamalkaksouri** [comment]
> @gopeter Yes, or you can do something like this:
> 
> ```js
> <Route path="/page/:friendlyName">
>   <Route path=":sort" element={<Page />} />
>   <Route path="" element={<Page />} />
> </Route>
> ```

Great 👍 This worked perfectly for me

**Comment by jamalkaksouri** [comment]
In the v5 we could specify pathlike this:

```
<Route path="/products/:id1?/:id:?">
    <Products/>
</Route>
```

in v6, we have to register each route separately:

```
<Route path="/products/" element={<Products/>} />
<Route path="/products/:id1" element={<Products/>} />
<Route path="/products/:id1"/:id2" element={<Products/>} />
```

**Comment by mikel-codes** [comment]
I have an annoying issue with react routers: using this an example
routes = [
....omitted for brevity
    { path: "", element: <Main />,
  children: [
        { path: "orders/:type", element: <Orders />,
        children: [
          { path:  "new", element: <OrderForm /> },
        ],
      },
   { path: "orders/:type", element: <Navigate to="orders/:type/?page=1&items=8" /> }

],

PLEASE how can this be done  , because I need to make a redirect that automatically identifies the params when making a redirect with Navigate

**Comment by iamunadike** [comment]
Anyt thoughts on how this can be done with react v6
```
<Route path={ "/shop/products/:category/:page" } />

<Redirect from="/shop/products/:category"
          to="/shop/products/:category/1" exact={ true } />
```

**Comment by Kepro** [comment]
@iamunadike you're in issues, for discussion use "discussion" or stackoverflow

**Comment by Abdilar** [comment]
Without optional parameters, react-router-dom v5 is better than v6

**Comment by caub** [comment]
I just made 

```js
function Route({ path, ...props }) {
  const optionalPaths = path.split('?');
  if (optionalPaths.length === 1) return <RRRoute path={path} {...props} />;

  return optionalPaths
    .flatMap(s => [s.split('/').slice(0, -1).join('/'), s.split('/').slice(-1)[0]])
    .filter(Boolean)
    .map((path, i, a) => i === 0 ? path : `${a.slice(0, i).join('/')}/${path}`)
    .map(path => <RRRoute path={path} {...props} />);
}
```
c'mon, it should be in the core

**Comment by Kepro** [comment]
@timdorr so are we playing a dead bug? :) lot of downvotes, a lot of developers are in pain because you removed optional parameters without explanation or open discussion...

**Comment by timdorr** [comment]
I didn't remove them personally. Don't be rude and direct your anger at me. I haven't contributed to the code base in some time.

**Comment by Kepro** [comment]
@timdorr, sorry but you were the one that wrote "We don't plan on supporting them in v6." without any explanation...

**Comment by caub** [comment]
@timdorr Can I try some pull-request for supporting them? in the same direction than my previous comment (it would expand all possibilities)

**Comment by jinspe** [comment]
another hacky solution if you don t want to unmount your components is to use useSearchParams so your url will look like this
/params1?p2=params2
you will have to do a bit of logic inside your components with a useEffect on the searchParams this can get kind of ugly but maybe it is easier that way.

**Comment by iamunadike** [comment]
Is there a way to specify default values for :some_key in routes react

**Comment by zachsiegel-capsida** [comment]
I agree with the frustrated commenters that this removal should absolutely be documented, since it used to be supported, and since many widely-used routers support and have historically supported optional parameters in a first-class way.

Or you could just support them.

Thank you!

**Comment by caub** [comment]
Here's a good workaround: https://replit.com/@caub/makeOptionalRoutes#index.js

```js
/*
Helpers that turn [{path: '/foo/:bar?', element: E}] into
[{path: '/foo', element: E}, {path: '/foo/:bar', element: E}] 
to deal with RR6 lack of support for optional params https://github.com/remix-run/react-router/issues/7285

usage: const element = useRoutes(makeOptionalRoutes([
    ...
  ]));
*/
function makeOptionalRoutes(routes) {
  return routes.flatMap(({ path, ...props }) => {
    // split the path by each /part
    const parts = [...path.matchAll(/\/:?[\w-]+\??/g)].map(a => a[0]);
  
    // expand all routes possible, this returns 2 power (number of ?) routes
    return parts
      .reduce((xs, part) => {
        const a = part.endsWith('?') ? ['', part.slice(0, -1)] : [part];
        return xs.flatMap(xsi => {
          return a.map(ai => [...xsi, ai].join(''));
        });
      }, [[]])
      .map(path => ({ path, ...props }));
    });
}
```

**Comment by actuallymentor** [comment]
> @timdorr Can I try some pull-request for supporting them? in the same direction than my previous comment (it would expand all possibilities)

Not sure how much your bandwidth is, but I think many people would appreciate a pull request for that, and would argue in favor for that functionality.

Not supporting optional parameters is counter industry standards and many of us have headaches because of this choice.

**Comment by powelski** [comment]
I thought that optional params and dynamic params (ability to match multiple segments as a single param) were the most basic features of any reasonable router library. I was wrong.

**Comment by zachsiegel-capsida** [comment]
@powelski I wonder whether there's a good reason for this design choice, though. Maybe the idea was that processing route parameters should happen in functional components with their own (sub-) routes, and maybe optional parameters can always be handled in this way.

If anyone can drop some knowledge about this project, I would greatly appreciate it!

**Comment by alexiuscrow** [comment]
I searched for a way to use the optional path prefix. In my case, it needed to split the routes by locales.
Taking into account the changes in the v6, there is a simple scratch with a better solution I found:
```javascript
import MainContainer from '../MainContainer';
import {Routes, Route} from 'react-router-dom';
import HomePage from '../../pages/Home';
import AboutPage from '../../pages/About';
import NotFoundPage from '../../pages/NotFound';
import {useTranslation} from 'react-i18next';

const Application = () => {
  const {i18n} = useTranslation();
  const langPathPrefixes = [...i18n.languages, ''];

  const langRoutes = langPathPrefixes.map(langPrefix => (
    <Route path={`/${langPrefix}`} element={<MainContainer />} key={`react-router-${langPrefix}`}>
      <Route index element={<HomePage />} />
      <Route path="about" element={<AboutPage />} />
      <Route path="*" element={<NotFoundPage />} />
    </Route>
  ));

  return <Routes>{langRoutes}</Routes>;
};

export default Application;
```

**Comment by AndrewEastwood** [comment]
> jamalkaksouri

seems more clunky and messy right now ...

**Comment by peterlau** [comment]
As an OSS maintainer (of a different project) myself I appreciate that folks are contributing a useful product for free so it's a case of what-you-see-is-what-you-get. 

In this instance, all that really needs saying is that "We're not supporting optional params in V6 because nested Routes are semantically better". 

The 'Whats new' docs do go into some depth about the changes: https://reactrouter.com/docs/en/v6/upgrading/v5#relative-routes-and-links

**Comment by TruePath** [comment]
So if I have routes like the following (e.g. the replacement for optional parameters) and just assign the same key prop to both won't react treat them as the same component (retaining state and keeping what it can in the DOM)?

```
        <Routes>
            <Route path="/" element={<BarWrapper />}>
                <Route path="*" element={<DefaultBar />}/>
                <Route path="project/:id/:action?/*" element={<ProjectBar key='projectbar'  />}/>
                <Route path="project/:id/*" element={<ProjectBar key='projectbar' />}/>
            </Route>
        </Routes>
```

If that's correct then it seems like this is a pretty easy fix.  However, I'm not sure enough about react internals to be totally sure what this does and/or how it works with class components.

**Comment by AChristoff** [comment]
I am sorry to say it but v5 is better than v6. Super cool features are gone... like gone ?!?!? and why ??! Instead of adding more and make the old easy to use you guys cut so much of the router..... I mean who does that!!

**Comment by douglasrcjames** [comment]
> @gopeter Yes, or you can do something like this:
> 
> ```js
> <Route path="/page/:friendlyName">
>   <Route path=":sort" element={<Page />} />
>   <Route path="" element={<Page />} />
> </Route>
> ```

For my use case of dynamically generated routes that need an optional parameter, the above solution does not work I do not think. See my use case below. I can't do this nesting trick because the `productUrl` must be set for the path in the parent `Route`, which if looped through with the map will produce multiple `Route` parents for each product. Any idea for a workaround for this? Seems ripe for optional usage. Pretty confused on the react-router's lack of reasoning to this decision to have no optional. 

```
 {
    this.props.products.map((product, p) => {
        let productUrl = urlify(product.name);
        return (
            <Route 
                key={p}
                path={`${productUrl}`} 
                element={
                    <ErrorBoundary>
                        <ProductPage
                            product={product}
                            site={this.props.site} 
                        />
                    </ErrorBoundary>
                }
            />
        );
        
    })
}
```

**Comment by elbakerino** [comment]
@douglasrcjames 

Depends how you can extract the "params" part from `urlify` and the info "does it have nested children" - and some other catchups if your URL structure is a chaos :D

With some comments here, this pattern works like a charm for me - also with automatically created routes - performance optimized.

- `/office` is the full base path for all example routes
- `PageOffice` is rendered only at exactly `/office`
- `/office/mails` is the full base for the mails: showing list of mails AND when selected also details of one mail
- `PageMails` is rendered only once and not remounted when the visitor switches between anything below `/office/mails`
- `PageMails` is rendered with an empty param for "just the `mails` path"
- `PageMails` is rendered with `mailId` as param for "the `:mailId` path"
- inside `PageMails` further relative routes are existing, but this parent doesn't need to know the detailed routes
    - thus the `/*` pattern together with `:mailId`, to let it render for all routes matching `/office/mails/:mailId/*`
    - if you have multiple, separated components, you most likely need to add the exact "managed child routes" like `:mailId/reply`

```jsx
<Routes>
    {/* .. other routes .. */}
    
   <Route path={'/office'}>
        <Route index element={<PageOffice/>}/>
        <Route path={'mails'} element={<PageMails/>}>
            <Route path={':mailId'}/>
            <Route path={':mailId/*'}/>
        </Route>
    </Route>

    {/* .. other routes .. */}
</Routes>
```

In `PageMails` i'm using the `useParams` hook to get the `mailId` param - the hook seems not-scoped-to-hierarchy in v6.

```js
const params = useParams()
const mailId = params.mailId
```

**Comment by HappyZombies** [comment]
What a complete and total disaster

**Comment by powelski** [comment]
@iamunadike faster how? Faster by micro-optimisation measures if anything. Matching routes happen so rarely and is always relatively fast. Saying that v6 is better is a joke.

**Comment by iamunadike** [comment]
Kris , give me your technical side by side comparison then ,
Because your opinions makes the people who released v6 look like fools
Give me why or what the micro optimization measures in context are or is ??

**Comment by ymoon715** [comment]
It seems like this is the direction a lot of React framework is heading towards. Next.js uses very similar way of routing as the v6. Remix, framework created by the creator of react-router, also has a routing system that they provide that's quite similar. I'm guessing they are using react-router within Remix, so it made a lot of sense for them to go ahead and implement these changes to fit their framework better.

As the user base for Next and Remix grows, this type of routing is starting to become the "standard" almost. Web development is heading towards more strictness, and react-router seems to be going into the same direction.

After being salty having to refactor large parts of my code base, I'm not so salty anymore. You shouldn't be anymore either, since this will simply prepare us for the future.

**Comment by powelski** [comment]
@ymoon715 what's not strict about dynamic route segments or nesting? It's pain in the ass, if anything.

**Comment by powelski** [comment]
@iamunadike micro-optimisation means irrelevant optimisation. Assuming v6 is any faster (did someone actually check this?), they gave away many convenient features in favor of this *irrelevant* performance gain? React routing happens on the client side, so we don't even benefit from those micro gains ourselves as app owners. In reality there is *zero* sense to make routing faster like that, it was already faster than enough before.

**Comment by elbakerino** [comment]
Not only for UI routing, the reason why I'm no longer salty, as the UI adjustments where the least ones for getting all code more future proof.

e.g. the [OpenApi Spec specifies](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#fixed-fields-7) "`path` params are always `required`".

With the bit less flexibility, comes a lot of interoperability - and for the cases where you still need to do it otherways, workarounds are always available - but now always as last resort, without having the impact when doing it "correct". e.g. Google LoadBalander allows wildcard/optional path params through a custom syntax.

It just isn't nice that this team here doesn't communicate their reasonings behind it (or just somewhere hidden in a PR), e.g. I imagine it could have a direct relation to the `element={<Comp/>}` rendering and the performance regarding that for the now nested routes logic.

**Comment by powelski** [comment]
@elbakerino can we leave performance out of this topic? I can't imagine client-side routing system that would have significant impact on performance. You guys need to stop confusing mental comfort with actual optimisation.

**Comment by chaance** [comment]
I'm going to create a topic for this over in Discussions and lock the conversation here, as it's strayed a bit from the original point and devolved into venting. We understand that adopting to v6 requires some refactoring (it is a major release, after all!), and that's always something we need to consider carefully when making significant feature changes.

I suspect that adding this feature in v6 wouldn't work without breaking changes to the matching algorithm, but I could be wrong. A more targeted and focused discussion would be a good place to work through proposals while considering potential breakage and edge cases.
