### ISSUE TITLE
Not able to get the location state in new tab(target="_blank")

### ISSUE THREAD

**Issue by adityashrivastwa** [ReactTraining/react-router#7304]
## Version

**"react-router-dom": "^5.1.2"**

## Test Case

https://codesandbox.io/s/react-router-vpj3i?file=/index.js
## Steps to reproduce
Try to open this link in the new tab, state is undefined.
`<Link
              to={{
                pathname: 'Topics/2',
                state: {
                  referrer: 2
                }
              }}
            >
              Topics
            </Link>`
Or
`<Link
              to={{
                pathname: 'Topics/2',
                state: {
                  referrer: 2
                }
              }}
              target="_blank"
            >
              Topics
            </Link>
`

## Expected Behavior
I should get the location state.
## Actual Behavior
Getting undefined for the location.state.

**Comment by MeiKatz** [comment]
That's not a bug because the state is only set when you click on the link. The state is only persisted per tab. If you open the page in a new tab, then there is no previously defined state. Ergo it fails to do load the state.

In your case you should pass your state either via a query parameter, define it in a client-side cookie or add it to the LocaleStorage:

```jsx
<Link to="Topics/2" onClick={() => localStorage.setItem("referrer", 2)}>Topics</Link>

// ...

function Topics() {
  const referrer = parseInt(localStorage.getItem("referrer"), 10);

  return (
    <div>
      <h2>Topics{referrer}</h2>
    </div>
  )
}```

https://codesandbox.io/s/react-router-uc267?file=/index.js

**Comment by adityashrivastwa** [comment]
Thanks a lot, @MeiKatz for clearing this thing. I am passing the params via query.
