### ISSUE TITLE
alpha 6 and react-transition-group integration.

### ISSUE THREAD

**Issue by laurencefass** [ReactTraining/react-router#7333]
Im trying out React Router 6 alpha with react-transition-group (the official recommendation for animating routes in React).  sandbox here. https://codesandbox.io/s/react-router-v6-react-transition-group-mfeqg?file=/src/App.js

I'd be very grateful if you can provide feedback on whether or not the two packages can work together at this stage or if there is a roadmap/preferred path toward animating router 6 routes.

I realise this may be a bit premature but as soon as I can start building apps as soon as I can smoothly animate transitions as well as I can with RRv5.

thanks

**Comment by MeiKatz** [comment]
@laurencefass Currently it is not possible, because there is no way to change the location object that `<Routes />` is working with. I opened an [issue](https://github.com/ReactTraining/react-router/issues/7297) myself some days ago and there is a pending pull request (#7298) that can be merged. When this is done, you can use `react-transition-group` for animating route transitions.

**Comment by laurencefass** [comment]
thanks i've subscribed to #7298.
