### ISSUE TITLE
react-router web pages are offline and appear to be hacked

### ISSUE THREAD

**Issue by iPzard** [ReactTraining/react-router#7392]
## Version
n/a

## Test Case
https://reacttraining.com/react-router/

## Steps to reproduce
Go to site

## Expected Behavior
Site to work

## Actual Behavior
Politically charged message, asking for money, on all pages.

**Comment by pnfcre** [comment]
No, it's not hacked: https://twitter.com/ReactTraining/status/1267561893167689728.

**Comment by iPzard** [comment]
Their Twitter was likely hacked as well. It seems like whoever did it is asking for money on the post you shared, very suspicious, to say the least.

**Comment by gordonTang2049** [comment]
With All due respect of Black lives matter, I have an important solo project needs to finish this week. Please fix the issues. Having said that, Hong Kongers have fight against CCP and police violence through out from 2019 to now on. YOU guys have no opinion and words for that, despite Houston Rockets General Manager Daryl Morey’s decision to post a message on Twitter in support of Hong Kong (“Fight for Freedom. Stand with Hong Kong.”). 

https://www.washingtonpost.com/sports/2019/10/15/lebron-james-criticizes-daryl-moreys-decision-send-controversial-hong-kong-tweet/

“I don’t want to get into a … feud with Daryl Morey, but I believe he wasn’t educated on the situation at hand and he spoke,”,  famous Black NBA player Lebron James said before the Lakers hosted the Golden State Warriors in a preseason game. 

I hate to show all those fact that to prove you guys are hypocrite, but can't hold my anger to tell you enough is enough. I support Black lives matter and I understand how much feud and despise toward racism and policing violence, I am an Asian live in Australia, I have both Racial Slurs and closet racism against me and my ethnic, even thought Australian claim themselves are equal to everyone. Not to mention how much photos and video that I have seen my fellow Hong Kong people suffer from all sorts of torturing, murder and rape from the police. 

My question is,  is striking really help the community realise the seriousness of racism and police violence immediately? Racism and police violence are rather a wrong culture and an inherit malfunction home education that all sort of bias and stereotype passed into the general public. You can't change it like flipping a switch. 

Even though I am bearing all those unfairness doesn't mean I fuck the society, strike and even trying to behave anti-socially. I wish my product and my work can contribute to the society and change the Australian view that Asians are cool, moreover we can create jobs and business for your community. It shall be the attitude toward those racism rather than throwing a fucking tantrum to the society.

**Comment by gordonTang2049** [comment]
Andrew YANG(was a 2020 president candidate) TALKS ABOUT his experience being treated unfairly 
https://www.youtube.com/watch?v=e3TJJt9sebo

**Comment by nino-moreton** [comment]
https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom/docs

If you really just care about working, the docs are still here as stated on that page.

**Comment by gordonTang2049** [comment]
hey dude, have you read what I wrote?

**Comment by nino-moreton** [comment]
@gordonTang2049 I don't care about that long post you wrote. I was just posting for people who was looking for react-router docs since the website docs are gone and in case they missed the message at the bottom.

**Comment by gordonTang2049** [comment]
I am saying that they shouldn't shut down their website, it doesn't help, you retard illiterate shit

**Comment by gordonTang2049** [comment]
@nino-moreton  I am sorry for my anger, but I just extremely shame on hypocrisy .

**Comment by timdorr** [comment]
As pointed out, they are still available on GitHub. Please use them there for now.

**Comment by traviswimer** [comment]
I'm glad to see you're voicing your support for this cause, but is taking the docs offline really the best option?

I'm only reading this issue, because I figured the site was hacked. All I'm saying is I imagine the docs get a decent amount of traffic, and there's probably a more effective way to raise money.

Anyway, that's just my opinion. Do with it what you like.
¯\\\_(ツ)\_/¯

**Comment by Digized** [comment]
I believe a banner would've accomplished the same task, without inconveniencing people... But it's really good that you guys did something about it.

**Comment by MatchaDog** [comment]
> With All due respect of Black lives matter, I have an important solo project needs to finish this week. Please fix the issues. Having said that, Hong Kongers have fight against CCP and police violence through out from 2019 to now on. YOU guys have no opinion and words for that, despite Houston Rockets General Manager Daryl Morey’s decision to post a message on Twitter in support of Hong Kong (“Fight for Freedom. Stand with Hong Kong.”).
> 
> https://www.washingtonpost.com/sports/2019/10/15/lebron-james-criticizes-daryl-moreys-decision-send-controversial-hong-kong-tweet/
> 
> “I don’t want to get into a … feud with Daryl Morey, but I believe he wasn’t educated on the situation at hand and he spoke,”, famous Black NBA player Lebron James said before the Lakers hosted the Golden State Warriors in a preseason game.
> 
> I hate to show all those fact that to prove you guys are hypocrite, but can't hold my anger to tell you enough is enough. I support Black lives matter and I understand how much feud and despise toward racism and policing violence, I am an Asian live in Australia, I have both Racial Slurs and closet racism against me and my ethnic, even thought Australian claim themselves are equal to everyone. Not to mention how much photos and video that I have seen my fellow Hong Kong people suffer from all sorts of torturing, murder and rape from the police.
> 
> My question is, is striking really help the community realise the seriousness of racism and police violence immediately? Racism and police violence are rather a wrong culture and an inherit malfunction home education that all sort of bias and stereotype passed into the general public. You can't change it like flipping a switch.
> 
> Even though I am bearing all those unfairness doesn't mean I fuck the society, strike and even trying to behave anti-socially. I wish my product and my work can contribute to the society and change the Australian view that Asians are cool, moreover we can create jobs and business for your community. It shall be the attitude toward those racism rather than throwing a fucking tantrum to the society.

Hong Kongers should be replaced 

> With All due respect of Black lives matter, I have an important solo project needs to finish this week. Please fix the issues. Having said that, Hong Kongers have fight against CCP and police violence through out from 2019 to now on. YOU guys have no opinion and words for that, despite Houston Rockets General Manager Daryl Morey’s decision to post a message on Twitter in support of Hong Kong (“Fight for Freedom. Stand with Hong Kong.”).
> 
> https://www.washingtonpost.com/sports/2019/10/15/lebron-james-criticizes-daryl-moreys-decision-send-controversial-hong-kong-tweet/
> 
> “I don’t want to get into a … feud with Daryl Morey, but I believe he wasn’t educated on the situation at hand and he spoke,”, famous Black NBA player Lebron James said before the Lakers hosted the Golden State Warriors in a preseason game.
> 
> I hate to show all those fact that to prove you guys are hypocrite, but can't hold my anger to tell you enough is enough. I support Black lives matter and I understand how much feud and despise toward racism and policing violence, I am an Asian live in Australia, I have both Racial Slurs and closet racism against me and my ethnic, even thought Australian claim themselves are equal to everyone. Not to mention how much photos and video that I have seen my fellow Hong Kong people suffer from all sorts of torturing, murder and rape from the police.
> 
> My question is, is striking really help the community realise the seriousness of racism and police violence immediately? Racism and police violence are rather a wrong culture and an inherit malfunction home education that all sort of bias and stereotype passed into the general public. You can't change it like flipping a switch.
> 
> Even though I am bearing all those unfairness doesn't mean I fuck the society, strike and even trying to behave anti-socially. I wish my product and my work can contribute to the society and change the Australian view that Asians are cool, moreover we can create jobs and business for your community. It shall be the attitude toward those racism rather than throwing a fucking tantrum to the society.

You should correctly distinguish between Hong Kongers and mobs;
You only saw the youth who longed for freedom, but did not see the terrorists who broke the law and order

**Comment by TchernyavskyDaniil** [comment]
This documentation act is racism.
