### ISSUE TITLE
Testing withRouter components throws Invariant failed: You should not use withRouter outside a <Router>

### ISSUE THREAD

**Issue by actuallymentor** [ReactTraining/react-router#7429]
## Version

```
"react-router-dom": "^5.2.0",
"react-router-native": "^5.2.0"
````

## Test Case

When using any `withRouter` wrapped component in `jest` the error `You should not use withRouter outside a <Router>` is thrown. I'm aware that:

1. There is a `.WrappedComponent` extension for components that are tested directly
2. This was a [discussion in 2017](https://github.com/ReactTraining/react-router/issues/4795#issuecomment-315280530)

The issue arises when you test a component that has a *imports a wrapped component*.

Integration tests are nigh impossible in this scenario.

## Steps to reproduce

Test a component that renders a subcomponent that is a wrapped withRouter.

## Expected Behavior

A warning, but not a breaking error.

## Actual Behavior

`throw`s and breaks.

**Comment by timdorr** [comment]
Without any code, it's hard to see what is the problem here. You should wrap your component with a Router when rendering it. Or just catch the error if you expect it. 

Alternatively, you can default export the wrapped component from the module but also named export the untouched component. This is a common pattern for testing connected components in React Redux.
