### ISSUE TITLE
Linking component libraries causes an invariant error

### ISSUE THREAD

**Issue by monsonjeremy** [ReactTraining/react-router#7438]
## Preface

I'm re-opening an issue after this one was closed (https://github.com/ReactTraining/react-router/issues/7436). I took time out of my day to create an example repo to reproduce the issue with the absolute minimum code, and it was very clear based on the response that the code was not even looked at. This is an issue i've spent >5 hours trying to find a fix for, with no solution in sight. I would appreciate if I could get more than a cursory glance.

## Version

`^5.0.0`

## Test Case

https://github.com/monsonjeremy/react-router-linking-issue

## Steps to reproduce

First run the app to see that it works without linking
```sh
npm install
npm start
```

go to `localhost:3000` and see the app rendered

Now link to the component library and see that it will not work

```sh
cd component-lib
npm install
npm run build
npm link
cd ..
npm link jeremy-test-lib
npm start
```

Now when navigating to `localhost:3000` there will be an invariant error

`Error: Invariant failed: You should not use <Link> outside a <Router>`

#### Performing a link between the `react-router-dom` instances does not help either

```sh
cd component-lib
npm link ../node_modules/react-router-dom
cd ..
npm start
```

## Expected Behavior

Should properly render the app.

## Actual Behavior

`Error: Invariant failed: You should not use <Link> outside a <Router>` even though the rendered code is the following
```
<StaticRouter><Comp/><StaticRouter/>
```

**Comment by timdorr** [comment]
Please don't open duplicate issues. This is a bug tracker, not a support system. The problem lies in your implementation, not our code. Hence, I closed out the issue. There are better avenues for assistance, such as StackOverflow or Reactiflux.

Regardless, I'll walk you through what the solution likely is: You have two copies of React Router. Because your sub-package installs its own copy of React Router, the RouterContext instance we use internally is different and the Link in your component lib can't "see" the context from your server. They are two different instances and React won't propagate updates between the two.

The correct way to resolve this is to use a peerDependency on react-router/react-router-dom.
