### ISSUE TITLE
Double click on nested route doesn't work as expected

### ISSUE THREAD

**Issue by TedSean** [ReactTraining/react-router#7447]
Version: react-router-dom - 16.9.0

https://codesandbox.io/s/react-router-dom-nested-routing-k7n2v?file=/src/components/Admin/index.js

Steps to reproduce:
1. Create a nested route.
2. On the initial mount of this component, Route it to any of it's child route
3. Try double clicking on nested route, you'd notice, route would stick to the root route rather routing to it's sub-route

Expected Behavior:
Irrespective of number of clicks on the nested route, it should route it to it's sub-route.

Actual Behavior:
It is sticking to the root route on double click.

**Comment by timdorr** [comment]
This is because you're redirecting in an effect immediately and by double-clicking, you're navigating twice. But where you navigate to is the same route, so the effect doesn't trigger again because the rendered component hasn't changed. Try making your effect depend on the params value and only trigger it if it's empty.
