### ISSUE TITLE
Hooks from another package

### ISSUE THREAD

**Issue by kitsoRik** [ReactTraining/react-router#7473]
## Version

react-router - 16.13.1
react - 16.13.1

## Test Case

Codesandbox not allow this

## Steps to reproduce
Clone this [repo](https://github.com/kitsoRik/react-router-dom-use-location-error)

Install dependies in /example and /, and run `npm start` in /example and /

## Expected Behavior
I've used hook in custom package. I've expected normal work without errors;

## Actual Behavior
When i try use hooks (useLocation, useHistory), I got errors, (when use useHistory got undefined), like a: 
`TypeError: Cannot read property 'location' of undefined`

BUT, if I move my hook to react project, all work's file.

P.S. For generate library, I use [create-react-library](https://www.npmjs.com/package/create-react-library)

**Comment by kitsoRik** [comment]
I decided this problem. It was in two packages of react-router-dom. In library I've used `react` and `react-router-dom` from `lib/node_module`, in app I've used `react` from `lib/node_modules` and `react-router-dom` from `app/node_modules`. I had had two different `react-router-dom`, when I link `react-router-dom` from App with `react-router-dom` in library, my code had started work fine.

This [comment ](https://github.com/facebook/react/issues/15706#issuecomment-503006137)had helped me.

**Comment by traviswimer** [comment]
I also came across this error while using ReactNative. It was caused because I was not using matching versions of `react-router-native` and `react-router-dom`.

I think this is for the same reason as mentioned by @kitsoRik 

I'm only posting this comment because the source of the problem was a rather unexpected. The versions must match exactly. I was using **v5.2.1** for `react-router-native` and **v5.2.0** for `react-router-dom`. In other words, it's likely not a matter of incompatibility, but a requirement that the versions must match exactly.
