### ISSUE TITLE
React-router + history@5.0.0 no match route after history.push

### ISSUE THREAD

**Issue by ArtemKislov** [ReactTraining/react-router#7506]
## Version

5.2.0

## Test Case

https://codesandbox.io/s/musing-hill-6izyi?file=/src/App.js
history@5.0.0

## Steps to reproduce
history.push('...anything existing...')

## Expected Behavior
show the component that matches the path

## Actual Behavior
empty screen (no route match) or default, like 404

## Comment
*history@4.10.1 works well*

**Comment by timdorr** [comment]
History 5 isn't compatible with React Router 5. Please use history version 4.

**Comment by ArtemKislov** [comment]
> History 5 isn't compatible with React Router 5. Please use history version 4.

@timdorr  Maybe it makes sense to write this in the documentation?

**Comment by dekelb** [comment]
I really think this should be documented somewhere in the docs.
There are examples of using the history package in the official docs, and there is no mention for max version == 4.

**Comment by hhgnsc** [comment]
Because the arguments of `history.listen` in 5.0.0 is something like `{action,location}` instead of `location`.
So react-router should fix this line:
https://github.com/ReactTraining/react-router/blob/7b76d314edb185fb90e38e7ebdb9ca0dc8a8d601/packages/react-router/modules/Router.js#L32
to
```javascript
this.unlisten = props.history.listen(({ location }) => {
```
Before they modify, you can rewrite `history.listen` before use in Router to fix the bug like this:
```javascript
const rawListen = history.listen
history.listen = rawListener => {
  return rawListen.call(history, ({ location }) => rawListener(location))
}
```

**Comment by durai001** [comment]
https://github.com/ReactTraining/react-router/issues/7415#issuecomment-785815657
