### ISSUE TITLE
Link [component] property is never working and was never working

### ISSUE THREAD

**Issue by activenode** [ReactTraining/react-router#7524]
## Version

**`react-router-dom@5.2.0`**

Please note that since this `component` property was introduced it never worked so it fails also for 

- `5.1.0`
- `5.1.1`
- `5.1.2`

## Test Case

https://codesandbox.io/s/react-router-v5-component-bug-5jyv3?file=/src/Routes.js

## Steps to reproduce

1. Try to render a Link with a custom component by using `forwardRef` such as described in the official documentation e.g. via:

```jsx
const FancyLink = React.forwardRef((props, ref) => (
  <a ref={ref}>💅 {props.children}</a>
))

<Link to="/" component={FancyLink} />
```

## Expected Behavior

The Link uses the given `ref` and sets its `href` and triggers proper routing.

## Actual Behavior

Routing does not work, the component is logically function-less.

**Comment by timdorr** [comment]
You have to apply the incoming props to it too:

```js
const FancyLink = React.forwardRef((props, ref) => (
  <a ref={ref} {...props}>💅 {props.children}</a>
));
```

**Comment by activenode** [comment]
Hi @timdorr . Did you test this on the given codesandbox? Because this does not work.
Please see the forked example here: https://codesandbox.io/s/react-router-v5-component-bug-part-2-m7jnd?file=/src/Routes.js

Also see the given error message on top (although I do not think that the error in itself is related to the described Issue).

Yes it will "add the href" but that is also it. The Link will not work with `push history` or whatever. It will just simply but a normal `href` there which I could equally do without using `<Link />`.

I am happy if you can get back on this and recheck by checking the sandbox sample.

**Comment by jan-paulus** [comment]
Here's a workaround I've found:
https://codesandbox.io/s/react-router-v5-component-bug-part-2-6h7v1?file=/src/Routes.js

If thats the intended behaviour, then the documentation should be adapted accordingly imo.

**Comment by activenode** [comment]
@timdorr  I feel urged to open another issue if one of these does not get reopened. The bug is still there and the bug does not get fixed by simply adding `...props` .

**Comment by ocdi** [comment]
@timdorr I came across this issue when I was researching a bug with exactly this scenario. The problem report doesn't state this, however the issue is a custom link component causes a full page refresh, rather than going through routing. The custom link _does_ work, but the UX is not what I expected.

I can see the workaround in https://codesandbox.io/s/react-router-v5-component-bug-part-2-6h7v1?file=/src/Routes.js where a `preventDefault` is applied.

Checking the code to the `Link` component, I can see it defaults to using a `LinkAnchor` component when a custom component is not supplied.
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L36

This is doing the `preventDefault` and calling `navigate()`. The problem is a custom anchor component doesn't use `LinkAnchor`, it uses the supplied component, that does not have that behaviour.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L98

The props provided _do_ pass a `navigate` prop, but nothing to `preventDefault` or handle clicks, which was my expectation. Fortunately it is easy to make a wrapper component that can handle this.

I think the docs should be updated to explicitly note the requirement to handle the click yourself, or just pass a default `onClick` through. It could be before the `...props` allowing a custom `onClick` to be passed still, in which case the documentation should spell it out as well. I would also remove the `onClick` handler from the `LinkAnchor` component as it would be handled by the `Link`.

**Comment by activenode** [comment]
But also the question is why it shouldn't be fixed more generically? As when it comes to the docs I would expect it to be handled properly with any type of element.
