### ISSUE TITLE
<Route> component pass props.match as a fresh object even if URL have not changed

### ISSUE THREAD

**Issue by aNyMoRe0505** [ReactTraining/react-router#7527]
## Version

v5.2.0

## Test Case

https://codesandbox.io/s/react-router-fki8l?file=/src/App.jsx

## Steps to reproduce

In the sandbox above, click the button named `Toggle Value` and see console

## Expected Behavior

`A` component should not re-render if it wrapped by `memo`

## Actual Behavior

`A` component re-render because `match` prop is a new object even if URL have not changed.

Is this a normal behavior ? I just started optimizing my app and I found this to be a big problem for me

**Comment by timdorr** [comment]
Yes, this is normal. For your route components, you should do a deeper inspection of the match object to ensure it's actually different.

**Comment by bluesky12** [comment]
Also encountered this problem and it introduces quite some performance cost.  
It would be quite appreciated if we can solve this from `Route` itself instead of having to tamper with **every** component.  

Optimizations like `React.PureComponent` or `React.memo` are well accepted and well implemented, some frameworks even make it built-in, e.g.`mobx-react`.   
In my humble opinion, it's reasonable for `react-router` to not breaking these optimizations.  

Submitted a PR, if there's something I missed, please let me know, thanks.

**Comment by mjackson** [comment]
When did we start passing the `match` prop to `<Route component>`? @timdorr any idea?

**Comment by timdorr** [comment]
Hasn't that been the case since v4 launched?

**Comment by bluesky12** [comment]
Hello @mjackson @timdorr, thanks for your attention to this issue. And may I ask how is it going on now?  
It would be appreciated for letting me know if there's any concern on [PR#7903](https://github.com/ReactTraining/react-router/pull/7903).

**Comment by bluesky12** [comment]
Thanks for the comment on [PR#7903](https://github.com/ReactTraining/react-router/pull/7903), @mjackson. Looking forward to your follow-up.
