### ISSUE TITLE
[v6] using array of elements as element prop throws warning but works just fine

### ISSUE THREAD

**Issue by wojtekmaj** [ReactTraining/react-router#7587]
## Version

v6.0.0-beta.0

## Steps to reproduce

Use `Route` with `element={[<div />, <div />]}`

## Expected Behavior

Works fine - displays both divs when route matches

## Actual Behavior

Works fine - displays both divs when route matches, but displays a warning:

```
Warning: Failed prop type: Invalid prop `element` of type `array` supplied to `Route`, expected a single ReactElement.
```

Is that intentional? Displaying arrays of elements is very helpful, otherwise we need to write `element={<>{[<div />, <div />}</>}` but just seems just silly.

**Comment by timdorr** [comment]
You should use a fragment without the array: `element={<><div /> <div /></>}`

**Comment by wojtekmaj** [comment]
My list of component is generated from an array which I `.map()`. Anyway, I think you're missing the point:

* Is it intentional that element doesn't accept arrays? Arrays are fine in React in most cases.
* If it's intentional, why it's working?
* If it's not, why it's throwing an error?

**Comment by timdorr** [comment]
We are simply checking against `PropTypes.element`, which does not allow arrays. It works because React allows you to render an array, but that is not a true "element" type. Until they had Fragments, it was a workaround for wanting to render a collection of elements, but is extremely uncommon nowadays. 

In your case, I would still wrap in a fragment: `element={<>{things.map(...)}</>}`
