### ISSUE TITLE
Redirect exact prop not working

### ISSUE THREAD

**Issue by AnderssonChristian** [ReactTraining/react-router#7636]
I have some issues regarding the Redirect component that seems to be a bug.

I have a wizard that has 2 steps. Each step has 3 substeps.
Here's a simplified example of my application:

**app.js**
```
<a onClick={() => history.push('/wizard/1')}>Start wizard</a>
```

**wizard.js**
```
<React.Fragment>
    <Redirect from="/wizard/1" to={{pathname: '/wizard/1/1', state: location.state}} exact={true} />
    <Route path="/wizard/1/1">
      <Step1 />
    </Route>
    <Route path="/wizard/1/2">
      <Step2 />
    </Route>
    <Route path="/wizard/1/3">
      <Step3 />
    </Route>
</React.Fragment>
```

The above works fine when pushing `/wizard/1` (Step1 is rendered). However, if I push to `/wizard/1/3` I am still taken to `/wizard/1/1`. After some testing it does seem to be related to the Redirect itself.

I managed to get it to work after the following workaround:

```
<React.Fragment>
  {location.pathname === '/wizard/1' && (
    <Redirect from="/wizard/1" to={{pathname: '/wizard/1/1', state: location.state}} />
  )}
  <Route path="/wizard/1/1">
    <Step1 />
  </Route>
  <Route path="/wizard/1/2">
    <Step2 />
  </Route>
  <Route path="/wizard/1/3">
    <Step3 />
  </Route>
</React.Fragment>
```

At a quick glance of the code (could be wrong) it seems like only `to`, `from` and `push` props are passed - which would explain the `exact` behavior not working.

**Comment by timdorr** [comment]
The `from` and `exact` props are only used when contained in a `<Switch>`. They are ignored for regular rendering because Redirect is intended only to be used when actually redirecting. If you want to conditionally redirect, wrap it in a conditional.

**Comment by AnderssonChristian** [comment]
Thanks! I actually had Switch but in in the immediate parent Routes. I added another one to the nestled one shown above and it worked. Thanks again.

**Comment by raynor85** [comment]
I think this is a bug. Like @AnderssonChristian, I have a route with a single <Switch> at the top, and a <Redirect exact from={PRODUCT_CATALOGUE} to={PRODUCT_CATALOGUE_LIST_PRODUCTS_PAGE} /> inside a nested Route. I have to wrap it into its own <Switch> component to make it work, or as a workaround I can do this instead:
```
      <Route exact path={PRODUCT_CATALOGUE}>
        <Redirect to={PRODUCT_CATALOGUE_LIST_PRODUCTS_PAGE} />
      </Route>
```
This behaviour is counter intuitive, I think the redirect `exact` should not be ignored in the first place because there is a top level <Switch> anyway. If by design it cannot be achieved, I'd rather have a compiled error that explicitly states that the local <Switch> is needed for the redirect to work as expected.
