### ISSUE TITLE
Order of Route path array with params matters

### ISSUE THREAD

**Issue by lucksp** [ReactTraining/react-router#7726]
## Version

`"react-router-dom": "5.2.0",`

## Test Case

- https://codesandbox.io/s/useparams-with-array-of-route-match-options-forked-3dcbz?file=/example.js

## Steps to reproduce

Works:
```
<Route path={["/nested/again/:id", "/nested/:id", "/:id", "/"]}> 
```
Does not work:
```
<Route path={[ "/", "/:id", "/nested/:id", "/nested/again/:id"]}>
```

## Expected Behavior
- The order of the array does not matter and any matched path will pass along the params to be found by `useParams`

## Actual Behavior
- `useParams` has no found params
I am not sure this is intended to behave, but something feels wrong where the actual path is not matching to the possible array values...

This is in reference to #7725

**Comment by timdorr** [comment]
This is expected behavior that matches `Switch`. It goes through the list of paths in order and matches whichever is first. If you remove the `"/"` path, you'll find it matches on the `"/:id"` path first and returns "nested" for the param. The same happens with `Switch`:
```js
<Switch>
  <Route path="/" />
  <Route path="/:id" />
  <Route path="/nested/:id" />
  <Route path="/nested/again/:id" />
</Switch>
```
You would have to reverse the order in that case for it to match anything other than the `"/"` path.
