### ISSUE TITLE
'HashRouter' cannot be used as a JSX component

### ISSUE THREAD

**Issue by aslanovsergey** [ReactTraining/react-router#7781]
I added react-router 5 into my project where i use typescript (v 3.9) but when I try to use react router i get an error: 
`'HashRouter' cannot be used as a JSX component. Its instance type 'HashRouter' is not a valid JSX element. The types returned by 'render()' are incompatible between these types. Type 'ReactNode' is not assignable to type 'false | Element'. Type 'string' is not assignable to type 'false | Element'.`

Here is how my render method look like

```
  public render(): React.ReactElement<IVacationRequestsProps> {
    return (
      <div className={styles.vacationRequests}>
        <HashRouter>
          <Route path="/" exact component={VacationsRequestList}></Route>
        </HashRouter>
      </div>
    );
  }
```

**Comment by timdorr** [comment]
Something else is going on here, because there's no reason that bit of code should be invalid. Check how you're importing the component or your build system. This isn't an issue with React Router.

**Comment by simonv3** [comment]
This might be related to https://github.com/remix-run/react-router/issues/8794

**Comment by saeid-shoja** [comment]
1- Returning an array of JSX elements instead of a single element.

To solve the error, we have to wrap the array using a React fragment or a div element.

2- Returning any value other than a JSX element or null from a component.

3- Having outdated versions of React typings.



# 👇️ with NPM
npm install --save-dev @types/react@latest @types/react-dom@latest

# 👇️ if you also want to update react and react-dom
npm install react@latest react-dom@latest

# ------------------------------

# 👇️ with YARN
yarn add @types/react@latest @types/react-dom@latest --dev

# 👇️ if you also want to update react and react-dom
yarn add react@latest react-dom@latest
