### ISSUE TITLE
The page should scroll up on switching routes

### ISSUE THREAD

**Issue by Prasundas99** [ReactTraining/react-router#7791]
## Version
5.2.0

## Expected Behavior

On switching routes from footer of the page or anywhere the new route should render from the top of the page

## Actual Behavior

The page is not rendering from top of the page it is rendering from where the scroll ended in the last route

Maybe integrating a scroll to top function would work

**Comment by bitttttten** [comment]
This is covered in the docs! 

https://reactrouter.com/web/guides/scroll-restoration

Scroll restoration is not built into the library since "different apps are going to have different scrolling needs" and there are different edge cases involved to provide a one fits all solution.

You can adopt one of the strategies in the docs depending on your use case.
